import type { ShowcaseAsset } from "@/lib/showcase.generated";

/**
 * A showcase photograph. No hooks — safe to render inside the client
 * components that own the scroll timelines.
 *
 * WHY <picture> AND NOT next/image: the site builds with output: "export",
 * so next/image runs unoptimised anyway and contributes nothing but a
 * wrapper. The derivatives are already generated by prepare-showcase.mjs
 * in both AVIF and WebP with explicit widths, which is the whole job.
 *
 * WHY loading="eager" EVERYWHERE ON THIS SHEET: plates on the motion sheet
 * live inside pinned, translated containers. Native lazy loading resolves
 * against the *viewport*, and a card parked 1400px to the right inside a
 * pinned track can satisfy that check while still being visually off-screen
 * — or fail it while visually on-screen. Either way the risk is a blank
 * rectangle sliding into frame during a demo. Sixteen plates totalling
 * roughly 1.4 MB is an easy trade for that never happening.
 *
 * width/height are always emitted so the layout never shifts.
 */
export function ShowcaseImage({
  asset,
  sizes,
  className = "",
}: {
  asset: ShowcaseAsset;
  sizes: string;
  className?: string;
}) {
  const srcSet = (sources: { w: number; url: string }[]) =>
    sources.map((s) => `${s.url} ${s.w}w`).join(", ");

  const fallback = asset.webp[asset.webp.length - 1];

  return (
    // `block h-full w-full` is load-bearing, not tidiness. <picture> is an
    // inline element with no intrinsic size, so an <img> inside it sizing
    // itself with h-full resolves against a zero-height box and silently
    // falls back to its own aspect ratio — which means object-cover never
    // engages and a 3:2 photograph in a 4:5 frame leaves a dead band.
    <picture className="block h-full w-full">
      <source type="image/avif" srcSet={srcSet(asset.avif)} sizes={sizes} />
      <source type="image/webp" srcSet={srcSet(asset.webp)} sizes={sizes} />
      <img
        src={fallback?.url}
        alt={asset.alt}
        width={asset.width}
        height={asset.height}
        sizes={sizes}
        loading="eager"
        decoding="async"
        draggable={false}
        className={`h-full w-full object-cover ${className}`}
        // The low-quality placeholder sits behind the image rather than
        // being swapped out, so there is no second paint to schedule.
        style={{
          backgroundImage: `url("${asset.lqip}")`,
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}
      />
    </picture>
  );
}
