/**
 * ══════════════════════════════════════════════════════════════════════
 * BUILD-TIME CONTENT FETCH — Phase B4, the frontend swap.
 *
 *   pnpm --filter @brs/web content        # regenerate from the API
 *   pnpm --filter @brs/web content --check # fail if the files are stale
 *
 * Reads /v1/collections through @brs/contract's typed client and rewrites
 * plates.generated.ts and showcase.generated.ts with byte-identical
 * EXPORT SHAPES. Every component keeps its imports, its types and its
 * property access. Not one component file changes.
 *
 * ── WHY CODEGEN AND NOT `await` IN A COMPONENT ──
 * The obvious design is a server component that fetches and passes props
 * down. It cannot work here, for two independent reasons:
 *
 *   1. KeyFacts, HorizontalGallery and GridAssembly are `"use client"` —
 *      they drive GSAP timelines against real DOM nodes. Client components
 *      cannot await, and passing the data as props would change every
 *      component signature, which is precisely the thing this phase exists
 *      to avoid.
 *
 *   2. `output: "export"` means there is no server at request time. The
 *      data has to be inside the bundle no matter which route it takes.
 *
 * So "fetch at build time" and "generate a module at build time" produce
 * the same artefact. The difference is only WHERE the fetch happens — and
 * doing it here keeps it out of the React tree entirely, where it would
 * otherwise be a suspense boundary and a loading state for data that is
 * already static.
 *
 * ── WHAT THIS PROVES ──
 * The generated modules used to be built from files on disk by
 * prepare-plates.mjs and prepare-showcase.mjs. They are now built from
 * Postgres, through the /v1 contract, with images served from object
 * storage. Three layers of the stack were replaced underneath the UI and
 * the UI did not notice. That is the Directive 3 test.
 * ══════════════════════════════════════════════════════════════════════
 */

import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import type { CollectionDTO, CollectionItemDTO } from "@brs/contract";

import { brs } from "../src/lib/content.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const LIB = path.resolve(HERE, "../src/lib");

const CHECK_ONLY = process.argv.includes("--check");

/* ── Shape mapping ────────────────────────────────────────────────────
 *
 * ImageDTO.sources is a flat list of {format, width, url}. The components
 * want it split per format and sorted ascending, because that is the order
 * a srcset has to be in. Splitting here rather than in the components is
 * what keeps them untouched.
 */

type Src = { w: number; url: string };

const sourcesOf = (item: CollectionItemDTO, format: "avif" | "webp"): Src[] =>
  item.image.sources
    .filter((s) => s.format === format)
    .sort((a, b) => a.width - b.width)
    .map((s) => ({ w: s.width, url: s.url }));

/** PlateAsset — plates.generated.ts. Caption is an array of placard
 *  lines; plate is the museum placard number. */
function toPlate(item: CollectionItemDTO) {
  return {
    id: item.key,
    alt: item.image.alt,
    width: item.image.width,
    height: item.image.height,
    ratio: item.image.ratio,
    plate: item.image.plate ?? null,
    caption: item.caption,
    lqip: item.image.lqip,
    avif: sourcesOf(item, "avif"),
    webp: sourcesOf(item, "webp"),
    // Press clippings only. `title` carries the outlet because that is the
    // only naming the archive has for these three.
    ...(item.title ? { outlet: item.title } : {}),
    ...(item.year !== undefined ? { year: item.year } : {}),
  };
}

/** ShowcaseAsset — showcase.generated.ts. Caption is a single string
 *  here, not an array; the two modules genuinely differ. */
function toShowcase(item: CollectionItemDTO) {
  return {
    id: item.key,
    alt: item.image.alt,
    width: item.image.width,
    height: item.image.height,
    ratio: item.image.ratio,
    lqip: item.image.lqip,
    avif: sourcesOf(item, "avif"),
    webp: sourcesOf(item, "webp"),
    ...(item.title ? { title: item.title } : {}),
    ...(item.year !== undefined ? { year: item.year } : {}),
    ...(item.note ? { note: item.note } : {}),
    ...(item.caption.length ? { caption: item.caption.join(" ") } : {}),
  };
}

/* ── Emit ─────────────────────────────────────────────────────────────── */

const json = (v: unknown) => JSON.stringify(v, null, 2).replace(/\n/g, "\n  ");

const HEADER = (from: string) => `/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: ${from}
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */
`;

function platesModule(byslug: Map<string, CollectionDTO>): string {
  const features = byslug.get("features")?.items ?? [];
  const press = byslug.get("press")?.items ?? [];
  const contact = byslug.get("contact-sheet")?.items ?? [];

  const featureIds = features.map((i) => `"${i.key}"`).join("\n  | ");

  return `${HEADER("/v1/collections/{features,press,contact-sheet}")}
export type PlateSource = { w: number; url: string };
export type PlateAsset = {
  id: string;
  alt: string;
  width: number;
  height: number;
  /** null means "intrinsic size, no design frame" — a scan, not a crop. */
  ratio: string | null;
  plate: number | null;
  caption: string[];
  lqip: string;
  avif: PlateSource[];
  webp: PlateSource[];
  outlet?: string;
  year?: number;
};

/** Stable editorial handles. A key names a ROLE, not a picture — so
 *  reordering the collection cannot change which plate is the hero. */
export type FeatureId =
  | ${featureIds};

export const FEATURES: Record<FeatureId, PlateAsset> = ${json(
    Object.fromEntries(features.map((i) => [i.key, toPlate(i)])),
  )};

export const PRESS: PlateAsset[] = ${json(press.map(toPlate))};

export const CONTACT_SHEET: PlateAsset[] = ${json(contact.map(toPlate))};
`;
}

function showcaseModule(byslug: Map<string, CollectionDTO>): string {
  const keyfacts = byslug.get("key-facts")?.items ?? [];
  const gallery = byslug.get("gallery")?.items ?? [];
  const assembly = byslug.get("assembly")?.items ?? [];

  return `${HEADER("/v1/collections/{key-facts,gallery,assembly}")}
export type ShowcaseSource = { w: number; url: string };
export type ShowcaseAsset = {
  id: string;
  alt: string;
  width: number;
  height: number;
  /** null means "intrinsic size, no design frame" — a scan, not a crop. */
  ratio: string | null;
  lqip: string;
  avif: ShowcaseSource[];
  webp: ShowcaseSource[];
  title?: string;
  year?: number;
  note?: string;
  caption?: string;
};

export const KEYFACTS: ShowcaseAsset[] = ${json(keyfacts.map(toShowcase))};

export const GALLERY: ShowcaseAsset[] = ${json(gallery.map(toShowcase))};

export const ASSEMBLY: ShowcaseAsset[] = ${json(assembly.map(toShowcase))};
`;
}

/* ── Main ─────────────────────────────────────────────────────────────── */

let collections: CollectionDTO[];
try {
  collections = await brs.collections.list();
} catch (e) {
  console.error(`\n  Cannot reach the API at ${process.env.NEXT_PUBLIC_BRS_API}`);
  console.error(`  ${(e as Error).message}`);
  console.error(`\n  Start it with:  pnpm --filter @brs/api dev\n`);
  process.exit(1);
}

const bySlug = new Map(collections.map((c) => [c.slug, c]));

const REQUIRED = ["features", "press", "contact-sheet", "key-facts", "gallery", "assembly"];
const missing = REQUIRED.filter((s) => !bySlug.has(s));
if (missing.length) {
  // Emitting a module with an empty FEATURES would produce `Record<never,
  // PlateAsset>` and a page that builds but renders nothing. Failing here
  // is the only way that stays visible.
  console.error(`\n  Missing collections: ${missing.join(", ")}`);
  console.error(`  Seed them with:  pnpm --filter @brs/db seed:collections\n`);
  process.exit(1);
}

const targets: [string, string][] = [
  [path.join(LIB, "plates.generated.ts"), platesModule(bySlug)],
  [path.join(LIB, "showcase.generated.ts"), showcaseModule(bySlug)],
];

let stale = 0;
for (const [file, content] of targets) {
  const current = await readFile(file, "utf8").catch(() => "");
  const changed = current !== content;

  if (CHECK_ONLY) {
    if (changed) stale++;
    console.log(`  ${changed ? "STALE  " : "current"}  ${path.basename(file)}`);
    continue;
  }

  if (changed) await writeFile(file, content, "utf8");
  console.log(`  ${changed ? "written" : "no change"}  ${path.basename(file)}`);
}

const counts = REQUIRED.map((s) => `${s} ${bySlug.get(s)!.items.length}`).join(" · ");
console.log(`\n  ${counts}\n`);

if (CHECK_ONLY && stale) {
  console.error(`  ${stale} file(s) out of date. Run: pnpm --filter @brs/web content\n`);
  process.exit(1);
}
