/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/committees/10
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { Committee } from "../committee.generated";

export const COMMITTEE: Committee = {
    "ordinal": 10,
    "label": "10th Executive Committee",
    "termStart": 2020,
    "termEnd": 2021,
    "groups": []
  };
