/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/committees
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { Committee } from "./committee.generated";

export type CommitteeSummary = {
  ordinal: number;
  label: string;
  /** Null when the term years are not recorded anywhere. */
  termStart: number | null;
  termEnd: number | null;
  /** Members on record. Zero is a real answer: a committee can be created
   *  before anyone has been entered against it. */
  members: number;
  current: boolean;
};

/** Newest first — the order a reader wants and the order a menu wants. */
export const COMMITTEES: CommitteeSummary[] = [
    {
      "ordinal": 11,
      "label": "11th Executive Committee",
      "termStart": 2025,
      "termEnd": 2026,
      "members": 85,
      "current": true
    },
    {
      "ordinal": 10,
      "label": "10th Executive Committee",
      "termStart": 2020,
      "termEnd": 2021,
      "members": 0,
      "current": false
    }
  ];

export const CURRENT_ORDINAL = 11;

/**
 * Per-ordinal dynamic imports, written out one by one rather than built
 * from a template string. A template literal here would make webpack
 * emit a context module covering every match, which is exactly the
 * bundle-everything behaviour the split above exists to avoid.
 */
const LOADERS: Record<number, () => Promise<{ COMMITTEE: Committee }>> = {
  11: () => import("./committees/11.generated"),
  10: () => import("./committees/10.generated"),
};

export async function loadCommittee(ordinal: number): Promise<Committee | null> {
  const load = LOADERS[ordinal];
  if (!load) return null;
  return (await load()).COMMITTEE;
}
