/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/collections/{features,press,contact-sheet}
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

export type PlateSource = { w: number; url: string };
export type PlateAsset = {
  id: string;
  alt: string;
  width: number;
  height: number;
  /** null means "intrinsic size, no design frame" — a scan, not a crop. */
  ratio: string | null;
  plate: number | null;
  caption: string[];
  lqip: string;
  avif: PlateSource[];
  webp: PlateSource[];
  outlet?: string;
  year?: number;
};

/** Stable editorial handles. A key names a ROLE, not a picture — so
 *  reordering the collection cannot change which plate is the hero. */
export type FeatureId =
  | "hero-rc19"
  | "compete-robocon05"
  | "build-mechatron13"
  | "teach-bwv8";

export const FEATURES: Record<FeatureId, PlateAsset> = {
    "hero-rc19": {
      "id": "hero-rc19",
      "alt": "A row of student-built robots on a bench at Robo Carnival 2019, their Arduino boards, ultrasonic sensors and jumper wiring exposed",
      "width": 960,
      "height": 1200,
      "ratio": "4:5",
      "plate": 1,
      "caption": [
        "ROBO CARNIVAL 2019 · BUET PREMISES",
        "JANUARY 2019 · 5 SEGMENTS"
      ],
      "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQAAsABABoJZwAD5FRf/wV8zh0mgAA/olhiT4unGIOU5acP9yeuvGP4sWpbJtepghWdEiwy8HbSEX90QOPPOzI1VMwzBqpjngSjUrO/AAAAA==",
      "avif": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/b0/5b/b05b33785dae3315b642d6a8fdb618adb95888eaf06a682bc2760143461d5dd4.avif"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/b7/4b/b74bdcdd3e77914feabacb5b192d135a180a4488caaf54bbcc5adf2cf48c3e36.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/3e/66/3e66e5839b3a5306a9449118ca23507a8c91a27a2a75e20a2b8c2c8fde97a866.avif"
        }
      ],
      "webp": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/48/18/48188f3e616a9003da0d3619c01fe11588b3acc5bf294cff0123fb32d24ff4f8.webp"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/88/73/887344cfb5ae0eef34dffa29e90028b7a43f3b7d8618de178d7f221c4aa3502d.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/fd/60/fd60ea5179d1be4d1abe717a848a7f700eac1c721453e20ea47e0283b4fc7db2.webp"
        }
      ]
    },
    "compete-robocon05": {
      "id": "compete-robocon05",
      "alt": "Four Team BUET members on stage in Beijing holding the Panasonic Award certificate and trophy beside a Bangladesh banner",
      "width": 720,
      "height": 480,
      "ratio": "3:2",
      "plate": 2,
      "caption": [
        "ABU ASIA-PACIFIC ROBOT CONTEST 2005 · BEIJING",
        "PANASONIC AWARD"
      ],
      "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQAAwABABoJZACdAYubbHg/rPuqAAA/ulZXTBPERdkRuHSTQ7vAmE8xtgJyN4ayeOgxCRRYBQ+kevN76NPC5aCAG6/4ci/9HlNqosUcrVry0VLiIIfj28tPzdtBF1cRcAAAA==",
      "avif": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/0b/0b/0b0bb34015c04a08d9c09cdae5e4d8c0aa1d018208ad0994c9cd4dd9d9549580.avif"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/ff/cf/ffcf51a87739efd973dba513fe32cc3dafc123d1e97084dd3f8595bbb4e19d0c.avif"
        }
      ],
      "webp": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/b4/02/b402b5afbf96226daa60bb1d2991af8df541c06c78e6cba1753f3ce1adb37d39.webp"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/d5/18/d518876013ff9a52dbb45472c80df36d0b3736934f05a927f03e4290a039f081.webp"
        }
      ]
    },
    "build-mechatron13": {
      "id": "build-mechatron13",
      "alt": "MechaTron, the BUET Lunabotics excavation rover, standing on grass with its chain-driven bucket ladder and conveyor visible",
      "width": 480,
      "height": 320,
      "ratio": "3:2",
      "plate": 3,
      "caption": [
        "NASA LUNABOTICS 2013 · TEAM BUET LUNABOTICS",
        "SPECIMEN MECHATRON"
      ],
      "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAsABABoJaQAAfX2T4axAAD8j0txJy4WUrtIaZhLpe4wsUTfnpk81QcggT5OHfASAeazpX+SRiusEUaGxD9cWPgAAA==",
      "avif": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/63/0c/630c763def70281cce4cc0bb08b56c27e758f6d02f025399850810d5fc4ef842.avif"
        }
      ],
      "webp": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/8c/a1/8ca1e23b25f769df04f5f3896b54fb8771c741894942135cc28df4f9db872ecc.webp"
        }
      ]
    },
    "teach-bwv8": {
      "id": "teach-bwv8",
      "alt": "Participants standing behind a full-floor line-follower track, their robots positioned on the black course, at Basic Workshop v8.0",
      "width": 720,
      "height": 480,
      "ratio": "3:2",
      "plate": 4,
      "caption": [
        "BASIC WORKSHOP v8.0 · BUET",
        "FOUR DAYS ACROSS TWO WEEKS"
      ],
      "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAwABABoJZQCdAENX1PdAAAA/ldWrni1DYYKpldIhjLbfvXU1Ocopadd+Ev2hTRi4L5crH/xDiAA",
      "avif": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/14/a2/14a2ec5ed9736e77c62f369f8d5863a671fe9bd4155ad65c4828277880e899e9.avif"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/f2/e1/f2e118baf9b321f1d92e025fe9b3854c718881c4e9ce481f5b4b0aed4e8f9e66.avif"
        }
      ],
      "webp": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/07/a6/07a62069b0f5de501a711dce97d594251ecfefe37136b01670ecaafb259980ba.webp"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/7a/a0/7aa0451078e7723d1b0fd78b240f4c3c2e8ab09915b3fc72d0713b0f242992e1.webp"
        }
      ]
    }
  };

export const PRESS: PlateAsset[] = [
    {
      "id": "press-iarc14",
      "alt": "Prothom Alo newspaper coverage of BUET Exponential at the 2014 international robotics competition",
      "width": 360,
      "height": 593,
      "ratio": null,
      "plate": null,
      "caption": [],
      "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABwBACdASoQABsAPxFysFAsJqSisAgBgCIJQAB8mT7B088uRWxS3EGlKHhNIAD+3xu1/5R+/bQCfW51zshhvzunax9kFSByB8qMAJwYe4B+NcI9CmtlDXPwpshUwM8JzRCJZV/9SnUG5bLTisCBNHmb2MTIAGocPtQG+OdjPYVvi2vU3KagpkKygES4h4kj2ePXiL9vuzXq7m9P/C+5SZTcgt+m5r6big+0oAAA",
      "avif": [
        {
          "w": 240,
          "url": "http://localhost:9000/brs-assets/sha256/13/9d/139d2ba0020017d76d20ba14c51b18e4b31eee26334738b6a24d05a3f91a830a.avif"
        },
        {
          "w": 360,
          "url": "http://localhost:9000/brs-assets/sha256/85/c0/85c0e635188a7ccf16f834640937e53418199443d77efd7bbbe8f667e48ef7b6.avif"
        }
      ],
      "webp": [
        {
          "w": 240,
          "url": "http://localhost:9000/brs-assets/sha256/ed/00/ed003bf1ecc1c63e2fb0b25fbf069b4bfe150ec0906adb0647b16a279f0458c1.webp"
        },
        {
          "w": 360,
          "url": "http://localhost:9000/brs-assets/sha256/e7/eb/e7eb9793b87c2466a4f29e83553082811667527d6067926e5cd8678e22176c4b.webp"
        }
      ],
      "outlet": "PROTHOM ALO",
      "year": 2014
    },
    {
      "id": "press-iarc15",
      "alt": "Prothom Alo newspaper coverage of BUET teams at Techkriti 2015, IIT Kanpur",
      "width": 360,
      "height": 303,
      "ratio": null,
      "plate": null,
      "caption": [],
      "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQAA0ABABoJQBdgMW+5jP7yJSN5AAA/tgfOaFljwgyekarDPSpaVaMxsBfuyj7tXq/KSEmTtxEqFtBOvVEeH52jI4jNEBCz+Xj8wHHCD+xK02xCEMLja2pgb7biBmpSgKgAA==",
      "avif": [
        {
          "w": 240,
          "url": "http://localhost:9000/brs-assets/sha256/ca/fe/cafe55be7a67facdaf5e4cf9bfff3bf11c2413d979becc945fd4e1234e718f81.avif"
        },
        {
          "w": 360,
          "url": "http://localhost:9000/brs-assets/sha256/21/34/21341beddf3c078e02c24ff82f7563cfa0c223243b60de92c005b286bd43c7b3.avif"
        }
      ],
      "webp": [
        {
          "w": 240,
          "url": "http://localhost:9000/brs-assets/sha256/9a/1e/9a1e9baf38add4873e711527c731a7fd96dab37a1927549d4eb854d54d96c111.webp"
        },
        {
          "w": 360,
          "url": "http://localhost:9000/brs-assets/sha256/2b/3d/2b3d56c83cc4049f1e85362490f4a373db1a9f70c21a31d1deab5b66ac6ab1cf.webp"
        }
      ],
      "outlet": "PROTHOM ALO",
      "year": 2015
    },
    {
      "id": "press-irc15",
      "alt": "Prothom Alo newspaper coverage of BUET Resonance at the 2015 international robotics contest",
      "width": 360,
      "height": 410,
      "ratio": null,
      "plate": null,
      "caption": [],
      "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoQABIAPxFwsFAsJiSisAgBgCIJZwAAXfJadR+WqcoNglAA/tYptEotRmD9yN8iqqJ1YuEy2hM0jy/aKQ18UAXLehpFySJbPyix8JLR1g3YZF4xtI+GABN6jvfzqU2/+AA=",
      "avif": [
        {
          "w": 240,
          "url": "http://localhost:9000/brs-assets/sha256/c7/e0/c7e0b745cea91e93881229841ba6781c2f9e1ce88816bdb68b91eeea48762b7e.avif"
        },
        {
          "w": 360,
          "url": "http://localhost:9000/brs-assets/sha256/b0/96/b0966c0a9aec20e07ab591ff5ac9ce9afeaf76eb75e4a063eaa5ad2fb0c2b2c8.avif"
        }
      ],
      "webp": [
        {
          "w": 240,
          "url": "http://localhost:9000/brs-assets/sha256/dc/ce/dccee3f9c016e381b4534a601a46ceb5de1ef153ed6bf8169c9f74534449b107.webp"
        },
        {
          "w": 360,
          "url": "http://localhost:9000/brs-assets/sha256/28/64/2864c5cd4d688630aebac44ace95433b8545b6962fe57b818d68c09e6d0c1012.webp"
        }
      ],
      "outlet": "PROTHOM ALO",
      "year": 2015
    }
  ];

export const CONTACT_SHEET: PlateAsset[] = [
    {
      "id": "cs-01",
      "alt": "Members seated in a BUET lecture room during the 2024 Annual General Meeting",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 101,
      "caption": [
        "AGM 2024"
      ],
      "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAwABABoJZQC7ADOljQxiKHMAPPJU3g/13LH0Ym3VnMSZjm9dTNsJyXYqIb/oZ+YF1J0xyKonn9l96LT419Ly/l1qvhMF+LS6YgA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/b4/ba/b4baef00708b6fa91c7a0d0d5345db67378b9c4b9a0f56ff6b111205d057fe26.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/0f/49/0f49ddb7f009e274a52115bcbef5ebb593cc52e445c4c3b4dc609c0896573c12.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/a0/e9/a0e99e84ed8814814e66e0cf4383622ba0a3e2dcff2e2ed0b484cf7a6e3ce318.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/63/3f/633f30002fb9ba15e6304dbd1ff552c9015d48b0ac5ee917a53a6506ba86ccbb.webp"
        }
      ]
    },
    {
      "id": "cs-02",
      "alt": "Participants at laptops filling a lecture room during Basic Workshop v1.0",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 102,
      "caption": [
        "BASIC WORKSHOP v1.0"
      ],
      "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwABABoJYwCdAEe90WU624AAPzZZm4biMWH5VSDqR/aJOTGr9jzvd3TYJbJxqcaLrsN1jmZy7yPI796/eNhDMJiffl/dz2GPWQJxnxGhzsXb4O3gAAA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/b3/66/b36606766f2606982f66e5baf49170ebf388e3c59fb785994caa8d4b0e90ae13.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/71/0f/710f25c448c0ac67222d8ecfae5dd087d88f823dc6760d7121a59545980a454b.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/51/ba/51bafec4764b11b5482b2acb1853f6ab0b0a20af449590b595e1f6016b48602d.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/0d/b2/0db2cabbd7d418079495a4fcd6cb9c2fb63c6f0c22e78452a01bf1b6e23d6171.webp"
        }
      ]
    },
    {
      "id": "cs-03",
      "alt": "Instructors receiving a framed certificate at the front of a classroom, a line-follower robot on the desk",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 103,
      "caption": [
        "BASIC WORKSHOP v5.0"
      ],
      "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAwABABoJQAB8coKf77OkGAA/sV/UQLP9pGuqH7lRI8/o3YrJjUaYRIheoM9b75wkmM9Px+mPw3ozhociBVVEA8ULSn7h/HX8+PCoQfHJYAA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/68/fe/68fe661c0300d06fde21653fedbea8a00f5500cd459b359182a03da844e0439f.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/3b/75/3b7503bfcadfa5bdeeed811d179f74e87b003a5d01ca323c3816d99400ee1cc4.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/9b/2c/9b2cf117a7d408471100e0ca99b1041a09a764a63ffe4b96d688ae2d0ad6efe2.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/7b/02/7b02cfca5ff610aaecae13519ea5f9fbceea55c1de4b45c74317fea5d0245616.webp"
        }
      ]
    },
    {
      "id": "cs-04",
      "alt": "Participants seated before a projector screen during Basic Workshop v6.0",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 104,
      "caption": [
        "BASIC WORKSHOP v6.0"
      ],
      "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAwABABoJQBOgBe0DOcJiAAA+ex1ACum02fQaKsq3hHmIPkCUQX8sD+xqw3DEyCihN3TkoTyY946TQjER6yL4O9maAAA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/5d/c9/5dc91cab8e4d9c777875d07ce2af52fbcdf275be170145e205c3afadef0e0d45.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/e1/7f/e17f14a7cc1403bfcbda15360df351e359b347134bee7673aac59f0abc58555a.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/40/4b/404bac6cf6cb2ce47835af7a9a84f7cbb6abeffee90b766c7607793e484cbbb8.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/23/0f/230f16865e9afe7f276e9ec66c2328dfbbd887f48e8d1b0bb0075e5f332906c4.webp"
        }
      ]
    },
    {
      "id": "cs-05",
      "alt": "Participants standing behind a full-floor line-follower track at Basic Workshop v8.0",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 105,
      "caption": [
        "BASIC WORKSHOP v8.0"
      ],
      "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAwABABoJZQCdAENX1PdAAAA/ldWrni1DYYKpldIhjLbfvXU1Ocopadd+Ev2hTRi4L5crH/xDiAA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/24/4a/244a701a7bea9aa178885c3420c104867f1306e69f792e61023038374f039021.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/5f/5a/5f5a78c3d4ecd40bd5df6aa98c6add21a0179949b902a81061cae91068c95971.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/60/8a/608a9993e9dea8337382717209a005758034b3bbccf0d50c0a8ed61c5f0df9d0.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/ce/1f/ce1f33ed450bc804c41ec663ff076650bb450f82d78fe78c7244a1612d1a6e9f.webp"
        }
      ]
    },
    {
      "id": "cs-06",
      "alt": "Line-follower robots lined up along the track at the Intra-BUET Robo Challenge 2024",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 106,
      "caption": [
        "INTRA-BUET 2024"
      ],
      "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAwABABoJQBOgMXXeRwGAAD99e1GL9EfHlx4xWodxrcsVR/nMRy0EmUPp+TDXg68V/GyLPEIaxo2msP3pBT4TDMz+1vQ3fGKsgAA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/56/8e/568ea7e7d2c780ba2660b34da0eaf0c228132fa36846b4ccd99259880f801819.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/f2/22/f222422f1ca173608fe45cdc2b0058c373940d02a84bc617ead3b6bcb4e77b36.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/ff/8b/ff8bf042900bc4f5e3029f2d80026b6f527c760bb31da6c8c62c1e8964204a94.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/39/7e/397eb9a3cd6a6cee0140e611d75fe93080b6b52a55a812a3d825a8680f252922.webp"
        }
      ]
    },
    {
      "id": "cs-07",
      "alt": "Participants and faculty gathered on the ECE building steps at the Intra-BUET Robo Challenge 2024",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 107,
      "caption": [
        "INTRA-BUET 2024"
      ],
      "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAsABABoJZwAAuWvxOFgAAD+sPaog2x+jTyYuMuTdHr8TjNdwksoFuNOf3t4Ljl3GXeDICvDZfb0vXxnc0AA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/23/1c/231c73a646d3ab7205768d7d35b54ba96f297078ff34dc673538ecc93c59608e.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/d2/9c/d29ceb8ae26cc0f7ea28876d1521d96b46ca9e28f1ec47bf225a145dec8b283e.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/00/8c/008ccc267502441330ee548cd917c5284891ce8d8ab9783222b9269934b27925.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/8b/dc/8bdc4ff678057d0202b8fb23108ea347b3079eb2246ee999548b4da8b39178a4.webp"
        }
      ]
    },
    {
      "id": "cs-08",
      "alt": "Participants and organisers on stage beneath the Robo Carnival 2016 banner",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 108,
      "caption": [
        "ROBO CARNIVAL 2016"
      ],
      "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAsABABoJbACdAYvhkrD/McBgAD+73igcpKjONgbQKIUNnrDXeAA0jAppuFRdAQBbZ/XAXBgmnQMdDiqXHS/mOZasi4CCj0bpwcRsu35Lb60ZGKHgssbFAIgAA==",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/25/63/256383eabd65b6aef43c3ddfa537b03c0c548ad9d85abc0a96cf2bc50d22fc24.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/91/7a/917a8d8f97489c4df8642bcb9dbca6dbd442a59767ea4ea0f1ac001cf233e686.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/d9/77/d977e80600fdedf628288ef26b494a56e31dca9b43abc196858a71a26abc655c.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/15/bb/15bba25b4be4fb7223c0118e9893e9b0c0b146c8d7823b948d912dac62a7e3e8.webp"
        }
      ]
    },
    {
      "id": "cs-09",
      "alt": "Competitor robots arranged on the arena table at Robo Carnival 2016",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 109,
      "caption": [
        "ROBO CARNIVAL 2016"
      ],
      "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAsABABoJbACdH8AGBiIecf0AAD+8Z/I5S+zlmBmzxwh0FPORoismm40azUfmGmS96Xt6z6yMT8YwsRrrp65/eiHxe4WIAA=",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/2b/c9/2bc9c54f637d74b4b96833a06c64a23826f783327d78141b85cd3f6839c3330b.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/8d/67/8d672a0d9f20bb1878c982fe073c8c92f98819c117d0807203845bb8241a4333.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/13/37/133760ea11301f95a503c10ef980e868109b6ea58ba62d620069734fe8160fb5.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/b9/ca/b9ca89f468cd04b1ee3c282bce845f11ba72103204eccc2b4a17400072901167.webp"
        }
      ]
    },
    {
      "id": "cs-10",
      "alt": "Winners holding certificates on the arena floor at Robo Carnival 2017",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 110,
      "caption": [
        "ROBO CARNIVAL 2017"
      ],
      "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAgABABoJZQCdAD1kff5wPAA++S889ozQK657w2NX9VHLn3b2HqlSA/RKVI2mxZ3ndeVPEwq8Kl/u3I0MpAA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/81/57/815746487878431d8c6f722e905435e519a5296e641400730186851432ede939.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/be/17/be1752c247ac9078c11ddf7cff9aca5d6360bacf1f71ca38f1bab24a0ed72235.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/77/91/7791d00f949aba352a1fb612c815c95ef2ce2381d2b88aaf386d6c121c599295.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/dd/26/dd26af735170a70cfad7c71000b21e23d2fb5be329bb92a3fd3d53807e4d5bab.webp"
        }
      ]
    },
    {
      "id": "cs-11",
      "alt": "A line-follower robot tracking an angular black course at Robo Carnival 2017",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 111,
      "caption": [
        "ROBO CARNIVAL 2017"
      ],
      "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAsABABoJaQAAq83M7jLxQAA/tDvc/dBh48rVVJq1BdlB1TEmaIpnJXVDsdLZqPVpCJ+QJAAAA==",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/02/28/022827520b1af30d66b2b2d04a39b61580b67d3aab1ee9fe6cc6bc8d3da15e97.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/40/e1/40e17eb15bf5d81866a915691f4c13b7191408e722b197f474737be794033271.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/7d/99/7d99703311281bb0eadc4cc9e56933d79549c2a0a9ef0f0f933e9020342bf150.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/aa/e1/aae1fb80c478ac51f48ceee770766b4708ece81560fb011e28b50ac57cf7ed03.webp"
        }
      ]
    },
    {
      "id": "cs-12",
      "alt": "A robot lifting stacked blocks during a Robo Carnival 2017 segment",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 112,
      "caption": [
        "ROBO CARNIVAL 2017"
      ],
      "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoQAAsABABoJaQAD5LRau5ayLcgPIAA/sEpzj7HctRU7ucf50d989CZxwr4VCJ/M11rQD+qnMUcis56mX+oHEhdK11bTl0viaD7OsNjVePqgAAA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/bf/e1/bfe1a73af672fe17957824f0cbe532036ec0e0c8ba983c7d30866d2e4397afc5.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/60/74/607432ca26b492b499aab1d8a2f1c90be1024e3f0b85b20259b2c85cb56bf37b.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/ab/b2/abb2e7e0596329117e6b13ecdffcfe4ff293d0ff57c96ca195c947cd33a30888.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/54/a6/54a64d61b3a19cb6c52cdc48b1d160337a6e746275e7b07a7927b2f8d3616bc2.webp"
        }
      ]
    },
    {
      "id": "cs-13",
      "alt": "Spectators seated around the white arena mat at Robo Carnival 2017",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 113,
      "caption": [
        "ROBO CARNIVAL 2017"
      ],
      "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsABABoJZQAAtzxGrHSfZ5gAP7vipSsSToBi5T0bdvKko1W74GDmaEOFu8ZWKPZ/WGLdCXHy/rOeCw5yjZAVyfbQ91qUyhCAAAA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/4a/74/4a741026890d8a88e0ca774453930d5e0b74022caf7c191fe24dda9c58f82350.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/72/ba/72ba2e32fdc9958f55cf369b8b3c6f36f339fbf6466a429a97773f4490bb0240.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/bb/3d/bb3dddc5068a4368d76b81013820b694b8537f2f8cce1474bd5dc3ec8baec222.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/75/cb/75cb82c570a49bdcb7c60f3b66e84d41d3c66ea38d7d769ec66a6d323e8937d2.webp"
        }
      ]
    },
    {
      "id": "cs-14",
      "alt": "A row of student-built robots on a bench at Robo Carnival 2019",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 114,
      "caption": [
        "ROBO CARNIVAL 2019"
      ],
      "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQAAsABABoJZwAD5FRf/wV8zh0mgAA/olhiT4unGIOU5acP9yeuvGP4sWpbJtepghWdEiwy8HbSEX90QOPPOzI1VMwzBqpjngSjUrO/AAAAA==",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/15/2a/152a7452bf95cf389f9dc943658a22f16b4cd82760e6c865d52b6a7e06a3ecd4.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/4a/09/4a098662af576afb84458b1041771e18de8b2144535ed099f02e64b8436a4a0d.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/10/01/10010821208c664cb9443b6cedaf864fdc26e8cc69cc485b661aa735a97c7345.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/3f/53/3f530e67f7ac5144ead038492083f0a84c8a7707cf5cb31f60a2e3306da48bee.webp"
        }
      ]
    },
    {
      "id": "cs-15",
      "alt": "Teams lined up beside the arena track at Robo Carnival 2023",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 115,
      "caption": [
        "ROBO CARNIVAL 2023"
      ],
      "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAwABABoJZwCw7Eei1+xx4AA/iX4pap8/Q01PPViKD5ICF5m2xbED9q8DzDjxU99Gbry8hBbHz6rfGHgAmSHbgAAAA==",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/b2/89/b289ba378853146112141290092e15d3ee97ae328d6205b3f94f023b902b211c.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/38/ab/38abc6070c6f6023f177dccb5f076cdfd789fda068c984be3a8e9c764fdbadb1.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/27/62/2762377b30f5ad938620fa73f832dd5b9f8e31075e5f7041c347280307960d63.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/d9/ae/d9aed9755ce214778fcc31eaa2912ddd74e2e985098f1b4a496e11fabcf1f9f7.webp"
        }
      ]
    },
    {
      "id": "cs-16",
      "alt": "Two robots on the hall floor before spectators at Robo Carnival 2023",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 116,
      "caption": [
        "ROBO CARNIVAL 2023"
      ],
      "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwABABoJZQAD5JwL4UDq6AAAP3b4H96DxcyVayz1aqoMB65fEI9WldozSEKVwMgcXKiMpcDiI1aYxzWmNGb5l7GpTskd9iIzaDUY4AAAA==",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/1f/ba/1fba8b7be27713a78073d6dad4545b1e56a6e2dec547974f46a20e022e7b08fe.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/be/2b/be2b0566a98cad3691a664c256de96580474a94297c8b723aef8a30d7e03d8a0.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/22/8f/228f6cb3a8af63da37bcd2225e88b30dbdc3af7b50317be9908294958866452d.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/75/b8/75b8333d21a9a7cee24bbd914477dfa93123e30a84eba7e6a5de20e579d8fa64.webp"
        }
      ]
    },
    {
      "id": "cs-17",
      "alt": "Organisers and faculty holding the Robo Carnival 2024 pennant beneath a cluster of balloons",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 117,
      "caption": [
        "ROBO CARNIVAL 2024"
      ],
      "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAsABABoJZQC7AEQgYcICq6cAAD+zQNJA+8MggR12pNU5SSKf7lftMEqoNtzRwPLeXs5UfDVyHf2Lg0G3Cy9wmZR/AAA",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/ab/d9/abd931d56840b6adc898705f74ad637d309394ad8452f5777b29bb54c8dd2611.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/8d/9d/8d9db4263a00f8e6fbb82356bc9088734529a99420e792cf079a6155ffaeab1e.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/dd/52/dd52a1051c0f391d08b618f637d37fe3214ab5655b7b76c21569f423ea9e4edf.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/08/13/081390f3129c00f563415f0cafd3e8f6dbebc723a646b54fe42de604bca5b737.webp"
        }
      ]
    },
    {
      "id": "cs-18",
      "alt": "Competitor robots lined up on the ground at Robo Carnival 2024",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 118,
      "caption": [
        "ROBO CARNIVAL 2024"
      ],
      "lqip": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAsABABoJaQAAtq231qzAAD+9W/bGgScoHw+xDan5Cwu7mgWwTGSAAA=",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/a5/8b/a58b110886125e241f25ddeac39fd73f815446c3bd4076e495c3b0b432b6d8f1.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/bb/57/bb579c10b23562435c4fbc5614bb293927566a009298ecacc744cfeed02dc3b3.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/02/ad/02ad6f2b01ae7e39d5d354ef49812de1f1eec1341b0923f63854500019e2b851.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/d2/0d/d20d9b50f879dff789131775aa3af6d6ed95412ae35f0bbe14e2791a6c69788e.webp"
        }
      ]
    },
    {
      "id": "cs-19",
      "alt": "Attendees seated in a lecture room at the Robotic Inception 2024 orientation",
      "width": 320,
      "height": 320,
      "ratio": "1:1",
      "plate": 119,
      "caption": [
        "ROBOTIC INCEPTION 2024"
      ],
      "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwABABoJQBdgMX6rIJKYNUAAP4TlABU6Qv/5Jml7Vpcnsci1gq5EYNmt8JQn6BKOZ/cOylgy7lJeXSftaHDr347mCASc7+tuYlEE4AAAA==",
      "avif": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/59/06/59066482bc6f8373a6d430e41c9ffaf179edfd716e078eb9b25f4e4d280944f0.avif"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/0d/32/0d32fc166859d9b47e76c68c941a2c8415ae0f4b3cb2f8f1699cb60ab5d5feeb.avif"
        }
      ],
      "webp": [
        {
          "w": 200,
          "url": "http://localhost:9000/brs-assets/sha256/8c/08/8c08b69ca4a67285be8907365f93a816196d8c48981d2a60dedf2c39f8cd715e.webp"
        },
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/a6/a6/a6a66d024d120f2070766db917f923e934698a15a2134365c15d0cbec80220a0.webp"
        }
      ]
    }
  ];
