/**
 * GENERATED by scripts/prepare-plates.mjs — do not edit by hand.
 *
 * Derivatives of BRS archive photographs. Alt text was written from looking
 * at each image, never from its filename.
 *
 * Phase B1 replaces this module with live /v1/assets data; the shape is
 * deliberately ImageDTO-like so no component changes.
 */

export type PlateSource = { w: number; url: string };
export type PlateAsset = {
  id: string;
  alt: string;
  width: number;
  height: number;
  ratio: string | null;
  plate: number | null;
  caption: string[];
  lqip: string;
  avif: PlateSource[];
  webp: PlateSource[];
  outlet?: string;
  year?: number;
};

export type FeatureId =
  | "hero-rc19"
  | "compete-robocon05"
  | "build-mechatron13"
  | "teach-bwv8";

/** Exact keys, so noUncheckedIndexedAccess cannot make every lookup
 *  possibly-undefined. A missing plate is a build error, not a runtime one. */
export const FEATURES: { [K in FeatureId]: PlateAsset } = {
  "hero-rc19": {
    "id": "hero-rc19",
    "alt": "A row of student-built robots on a bench at Robo Carnival 2019, their Arduino boards, ultrasonic sensors and jumper wiring exposed",
    "width": 960,
    "height": 1200,
    "ratio": "4:5",
    "plate": 1,
    "caption": [
      "ROBO CARNIVAL 2019 · BUET PREMISES",
      "JANUARY 2019 · 5 SEGMENTS"
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQAAsABABoJZwAD5FRf/wV8zh0mgAA/olhiT4unGIOU5acP9yeuvGP4sWpbJtepghWdEiwy8HbSEX90QOPPOzI1VMwzBqpjngSjUrO/AAAAA==",
    "avif": [
      {
        "w": 480,
        "url": "/plates/hero-rc19-480.avif"
      },
      {
        "w": 720,
        "url": "/plates/hero-rc19-720.avif"
      },
      {
        "w": 960,
        "url": "/plates/hero-rc19-960.avif"
      }
    ],
    "webp": [
      {
        "w": 480,
        "url": "/plates/hero-rc19-480.webp"
      },
      {
        "w": 720,
        "url": "/plates/hero-rc19-720.webp"
      },
      {
        "w": 960,
        "url": "/plates/hero-rc19-960.webp"
      }
    ]
  },
  "compete-robocon05": {
    "id": "compete-robocon05",
    "alt": "Four Team BUET members on stage in Beijing holding the Panasonic Award certificate and trophy beside a Bangladesh banner",
    "width": 720,
    "height": 480,
    "ratio": "3:2",
    "plate": 2,
    "caption": [
      "ABU ASIA-PACIFIC ROBOT CONTEST 2005 · BEIJING",
      "PANASONIC AWARD"
    ],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQAAwABABoJZACdAYubbHg/rPuqAAA/ulZXTBPERdkRuHSTQ7vAmE8xtgJyN4ayeOgxCRRYBQ+kevN76NPC5aCAG6/4ci/9HlNqosUcrVry0VLiIIfj28tPzdtBF1cRcAAAA==",
    "avif": [
      {
        "w": 480,
        "url": "/plates/compete-robocon05-480.avif"
      },
      {
        "w": 720,
        "url": "/plates/compete-robocon05-720.avif"
      }
    ],
    "webp": [
      {
        "w": 480,
        "url": "/plates/compete-robocon05-480.webp"
      },
      {
        "w": 720,
        "url": "/plates/compete-robocon05-720.webp"
      }
    ]
  },
  "build-mechatron13": {
    "id": "build-mechatron13",
    "alt": "MechaTron, the BUET Lunabotics excavation rover, standing on grass with its chain-driven bucket ladder and conveyor visible",
    "width": 480,
    "height": 320,
    "ratio": "3:2",
    "plate": 3,
    "caption": [
      "NASA LUNABOTICS 2013 · TEAM BUET LUNABOTICS",
      "SPECIMEN MECHATRON"
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAQCdASoQAAsABABoJaQAAfX2T4axAAD8j0txJy4WUrtIaZhLpe4wsUTfnpk81QcggT5OHfASAeazpX+SRiusEUaGxD9cWPgAAA==",
    "avif": [
      {
        "w": 480,
        "url": "/plates/build-mechatron13-480.avif"
      }
    ],
    "webp": [
      {
        "w": 480,
        "url": "/plates/build-mechatron13-480.webp"
      }
    ]
  },
  "teach-bwv8": {
    "id": "teach-bwv8",
    "alt": "Participants standing behind a full-floor line-follower track, their robots positioned on the black course, at Basic Workshop v8.0",
    "width": 720,
    "height": 480,
    "ratio": "3:2",
    "plate": 4,
    "caption": [
      "BASIC WORKSHOP v8.0 · BUET",
      "FOUR DAYS ACROSS TWO WEEKS"
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAwABABoJZQCdAENX1PdAAAA/ldWrni1DYYKpldIhjLbfvXU1Ocopadd+Ev2hTRi4L5crH/xDiAA",
    "avif": [
      {
        "w": 480,
        "url": "/plates/teach-bwv8-480.avif"
      },
      {
        "w": 720,
        "url": "/plates/teach-bwv8-720.avif"
      }
    ],
    "webp": [
      {
        "w": 480,
        "url": "/plates/teach-bwv8-480.webp"
      },
      {
        "w": 720,
        "url": "/plates/teach-bwv8-720.webp"
      }
    ]
  }
};

export const PRESS: PlateAsset[] = [
  {
    "id": "press-iarc14",
    "alt": "Prothom Alo newspaper coverage of BUET Exponential at the 2014 international robotics competition",
    "width": 360,
    "height": 593,
    "ratio": null,
    "plate": null,
    "caption": [],
    "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABwBACdASoQABsAPxFysFAsJqSisAgBgCIJQAB8mT7B088uRWxS3EGlKHhNIAD+3xu1/5R+/bQCfW51zshhvzunax9kFSByB8qMAJwYe4B+NcI9CmtlDXPwpshUwM8JzRCJZV/9SnUG5bLTisCBNHmb2MTIAGocPtQG+OdjPYVvi2vU3KagpkKygES4h4kj2ePXiL9vuzXq7m9P/C+5SZTcgt+m5r6big+0oAAA",
    "avif": [
      {
        "w": 240,
        "url": "/plates/press-iarc14-240.avif"
      },
      {
        "w": 360,
        "url": "/plates/press-iarc14-360.avif"
      }
    ],
    "webp": [
      {
        "w": 240,
        "url": "/plates/press-iarc14-240.webp"
      },
      {
        "w": 360,
        "url": "/plates/press-iarc14-360.webp"
      }
    ],
    "outlet": "PROTHOM ALO",
    "year": 2014
  },
  {
    "id": "press-iarc15",
    "alt": "Prothom Alo newspaper coverage of BUET teams at Techkriti 2015, IIT Kanpur",
    "width": 360,
    "height": 303,
    "ratio": null,
    "plate": null,
    "caption": [],
    "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQAgCdASoQAA0ABABoJQBdgMW+5jP7yJSN5AAA/tgfOaFljwgyekarDPSpaVaMxsBfuyj7tXq/KSEmTtxEqFtBOvVEeH52jI4jNEBCz+Xj8wHHCD+xK02xCEMLja2pgb7biBmpSgKgAA==",
    "avif": [
      {
        "w": 240,
        "url": "/plates/press-iarc15-240.avif"
      },
      {
        "w": 360,
        "url": "/plates/press-iarc15-360.avif"
      }
    ],
    "webp": [
      {
        "w": 240,
        "url": "/plates/press-iarc15-240.webp"
      },
      {
        "w": 360,
        "url": "/plates/press-iarc15-360.webp"
      }
    ],
    "outlet": "PROTHOM ALO",
    "year": 2015
  },
  {
    "id": "press-irc15",
    "alt": "Prothom Alo newspaper coverage of BUET Resonance at the 2015 international robotics contest",
    "width": 360,
    "height": 410,
    "ratio": null,
    "plate": null,
    "caption": [],
    "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAwCdASoQABIAPxFwsFAsJiSisAgBgCIJZwAAXfJadR+WqcoNglAA/tYptEotRmD9yN8iqqJ1YuEy2hM0jy/aKQ18UAXLehpFySJbPyix8JLR1g3YZF4xtI+GABN6jvfzqU2/+AA=",
    "avif": [
      {
        "w": 240,
        "url": "/plates/press-irc15-240.avif"
      },
      {
        "w": 360,
        "url": "/plates/press-irc15-360.avif"
      }
    ],
    "webp": [
      {
        "w": 240,
        "url": "/plates/press-irc15-240.webp"
      },
      {
        "w": 360,
        "url": "/plates/press-irc15-360.webp"
      }
    ],
    "outlet": "PROTHOM ALO",
    "year": 2015
  }
] as const;

export const CONTACT_SHEET: PlateAsset[] = [
  {
    "id": "cs-01",
    "alt": "Members seated in a BUET lecture room during the 2024 Annual General Meeting",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 101,
    "caption": [
      "AGM 2024"
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAwABABoJZQC7ADOljQxiKHMAPPJU3g/13LH0Ym3VnMSZjm9dTNsJyXYqIb/oZ+YF1J0xyKonn9l96LT419Ly/l1qvhMF+LS6YgA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-01-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-01-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-01-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-01-320.webp"
      }
    ]
  },
  {
    "id": "cs-02",
    "alt": "Participants at laptops filling a lecture room during Basic Workshop v1.0",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 102,
    "caption": [
      "BASIC WORKSHOP v1.0"
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoQAAwABABoJYwCdAEe90WU624AAPzZZm4biMWH5VSDqR/aJOTGr9jzvd3TYJbJxqcaLrsN1jmZy7yPI796/eNhDMJiffl/dz2GPWQJxnxGhzsXb4O3gAAA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-02-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-02-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-02-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-02-320.webp"
      }
    ]
  },
  {
    "id": "cs-03",
    "alt": "Instructors receiving a framed certificate at the front of a classroom, a line-follower robot on the desk",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 103,
    "caption": [
      "BASIC WORKSHOP v5.0"
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAQCdASoQAAwABABoJQAB8coKf77OkGAA/sV/UQLP9pGuqH7lRI8/o3YrJjUaYRIheoM9b75wkmM9Px+mPw3ozhociBVVEA8ULSn7h/HX8+PCoQfHJYAA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-03-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-03-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-03-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-03-320.webp"
      }
    ]
  },
  {
    "id": "cs-04",
    "alt": "Participants seated before a projector screen during Basic Workshop v6.0",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 104,
    "caption": [
      "BASIC WORKSHOP v6.0"
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoQAAwABABoJQBOgBe0DOcJiAAA+ex1ACum02fQaKsq3hHmIPkCUQX8sD+xqw3DEyCihN3TkoTyY946TQjER6yL4O9maAAA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-04-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-04-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-04-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-04-320.webp"
      }
    ]
  },
  {
    "id": "cs-05",
    "alt": "Participants standing behind a full-floor line-follower track at Basic Workshop v8.0",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 105,
    "caption": [
      "BASIC WORKSHOP v8.0"
    ],
    "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAwABABoJZQCdAENX1PdAAAA/ldWrni1DYYKpldIhjLbfvXU1Ocopadd+Ev2hTRi4L5crH/xDiAA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-05-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-05-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-05-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-05-320.webp"
      }
    ]
  },
  {
    "id": "cs-06",
    "alt": "Line-follower robots lined up along the track at the Intra-BUET Robo Challenge 2024",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 106,
    "caption": [
      "INTRA-BUET 2024"
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAwABABoJQBOgMXXeRwGAAD99e1GL9EfHlx4xWodxrcsVR/nMRy0EmUPp+TDXg68V/GyLPEIaxo2msP3pBT4TDMz+1vQ3fGKsgAA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-06-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-06-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-06-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-06-320.webp"
      }
    ]
  },
  {
    "id": "cs-07",
    "alt": "Participants and faculty gathered on the ECE building steps at the Intra-BUET Robo Challenge 2024",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 107,
    "caption": [
      "INTRA-BUET 2024"
    ],
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAsABABoJZwAAuWvxOFgAAD+sPaog2x+jTyYuMuTdHr8TjNdwksoFuNOf3t4Ljl3GXeDICvDZfb0vXxnc0AA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-07-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-07-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-07-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-07-320.webp"
      }
    ]
  },
  {
    "id": "cs-08",
    "alt": "Participants and organisers on stage beneath the Robo Carnival 2016 banner",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 108,
    "caption": [
      "ROBO CARNIVAL 2016"
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAsABABoJbACdAYvhkrD/McBgAD+73igcpKjONgbQKIUNnrDXeAA0jAppuFRdAQBbZ/XAXBgmnQMdDiqXHS/mOZasi4CCj0bpwcRsu35Lb60ZGKHgssbFAIgAA==",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-08-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-08-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-08-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-08-320.webp"
      }
    ]
  },
  {
    "id": "cs-09",
    "alt": "Competitor robots arranged on the arena table at Robo Carnival 2016",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 109,
    "caption": [
      "ROBO CARNIVAL 2016"
    ],
    "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAsABABoJbACdH8AGBiIecf0AAD+8Z/I5S+zlmBmzxwh0FPORoismm40azUfmGmS96Xt6z6yMT8YwsRrrp65/eiHxe4WIAA=",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-09-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-09-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-09-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-09-320.webp"
      }
    ]
  },
  {
    "id": "cs-10",
    "alt": "Winners holding certificates on the arena floor at Robo Carnival 2017",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 110,
    "caption": [
      "ROBO CARNIVAL 2017"
    ],
    "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAgABABoJZQCdAD1kff5wPAA++S889ozQK657w2NX9VHLn3b2HqlSA/RKVI2mxZ3ndeVPEwq8Kl/u3I0MpAA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-10-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-10-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-10-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-10-320.webp"
      }
    ]
  },
  {
    "id": "cs-11",
    "alt": "A line-follower robot tracking an angular black course at Robo Carnival 2017",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 111,
    "caption": [
      "ROBO CARNIVAL 2017"
    ],
    "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAsABABoJaQAAq83M7jLxQAA/tDvc/dBh48rVVJq1BdlB1TEmaIpnJXVDsdLZqPVpCJ+QJAAAA==",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-11-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-11-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-11-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-11-320.webp"
      }
    ]
  },
  {
    "id": "cs-12",
    "alt": "A robot lifting stacked blocks during a Robo Carnival 2017 segment",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 112,
    "caption": [
      "ROBO CARNIVAL 2017"
    ],
    "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoQAAsABABoJaQAD5LRau5ayLcgPIAA/sEpzj7HctRU7ucf50d989CZxwr4VCJ/M11rQD+qnMUcis56mX+oHEhdK11bTl0viaD7OsNjVePqgAAA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-12-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-12-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-12-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-12-320.webp"
      }
    ]
  },
  {
    "id": "cs-13",
    "alt": "Spectators seated around the white arena mat at Robo Carnival 2017",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 113,
    "caption": [
      "ROBO CARNIVAL 2017"
    ],
    "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAsABABoJZQAAtzxGrHSfZ5gAP7vipSsSToBi5T0bdvKko1W74GDmaEOFu8ZWKPZ/WGLdCXHy/rOeCw5yjZAVyfbQ91qUyhCAAAA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-13-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-13-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-13-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-13-320.webp"
      }
    ]
  },
  {
    "id": "cs-14",
    "alt": "A row of student-built robots on a bench at Robo Carnival 2019",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 114,
    "caption": [
      "ROBO CARNIVAL 2019"
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQAAsABABoJZwAD5FRf/wV8zh0mgAA/olhiT4unGIOU5acP9yeuvGP4sWpbJtepghWdEiwy8HbSEX90QOPPOzI1VMwzBqpjngSjUrO/AAAAA==",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-14-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-14-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-14-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-14-320.webp"
      }
    ]
  },
  {
    "id": "cs-15",
    "alt": "Teams lined up beside the arena track at Robo Carnival 2023",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 115,
    "caption": [
      "ROBO CARNIVAL 2023"
    ],
    "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAwABABoJZwCw7Eei1+xx4AA/iX4pap8/Q01PPViKD5ICF5m2xbED9q8DzDjxU99Gbry8hBbHz6rfGHgAmSHbgAAAA==",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-15-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-15-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-15-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-15-320.webp"
      }
    ]
  },
  {
    "id": "cs-16",
    "alt": "Two robots on the hall floor before spectators at Robo Carnival 2023",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 116,
    "caption": [
      "ROBO CARNIVAL 2023"
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwABABoJZQAD5JwL4UDq6AAAP3b4H96DxcyVayz1aqoMB65fEI9WldozSEKVwMgcXKiMpcDiI1aYxzWmNGb5l7GpTskd9iIzaDUY4AAAA==",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-16-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-16-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-16-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-16-320.webp"
      }
    ]
  },
  {
    "id": "cs-17",
    "alt": "Organisers and faculty holding the Robo Carnival 2024 pennant beneath a cluster of balloons",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 117,
    "caption": [
      "ROBO CARNIVAL 2024"
    ],
    "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAsABABoJZQC7AEQgYcICq6cAAD+zQNJA+8MggR12pNU5SSKf7lftMEqoNtzRwPLeXs5UfDVyHf2Lg0G3Cy9wmZR/AAA",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-17-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-17-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-17-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-17-320.webp"
      }
    ]
  },
  {
    "id": "cs-18",
    "alt": "Competitor robots lined up on the ground at Robo Carnival 2024",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 118,
    "caption": [
      "ROBO CARNIVAL 2024"
    ],
    "lqip": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAQCdASoQAAsABABoJaQAAtq231qzAAD+9W/bGgScoHw+xDan5Cwu7mgWwTGSAAA=",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-18-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-18-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-18-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-18-320.webp"
      }
    ]
  },
  {
    "id": "cs-19",
    "alt": "Attendees seated in a lecture room at the Robotic Inception 2024 orientation",
    "width": 320,
    "height": 320,
    "ratio": "1:1",
    "plate": 119,
    "caption": [
      "ROBOTIC INCEPTION 2024"
    ],
    "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwABABoJQBdgMX6rIJKYNUAAP4TlABU6Qv/5Jml7Vpcnsci1gq5EYNmt8JQn6BKOZ/cOylgy7lJeXSftaHDr347mCASc7+tuYlEE4AAAA==",
    "avif": [
      {
        "w": 200,
        "url": "/plates/cs-19-200.avif"
      },
      {
        "w": 320,
        "url": "/plates/cs-19-320.avif"
      }
    ],
    "webp": [
      {
        "w": 200,
        "url": "/plates/cs-19-200.webp"
      },
      {
        "w": 320,
        "url": "/plates/cs-19-320.webp"
      }
    ]
  }
] as const;
