/**
 * GENERATED by scripts/prepare-sequence.mjs — do not edit by hand.
 *
 * Exploded-view rover assembly, re-encoded for canvas scrubbing.
 * See the script header for why WebP, why full frame count, and for the
 * provenance note on the source render.
 */

/** Frame count. Files are /sequence/f-000.webp .. f-239.webp */
export const SEQUENCE_FRAMES = 240;

/** Intrinsic size of every frame, for canvas letterboxing maths. */
export const SEQUENCE_WIDTH = 1024;
export const SEQUENCE_HEIGHT = 576;

/**
 * The frames' own backdrop, measured from the corners of frame 000 rather
 * than eyeballed. The section behind the canvas uses this exact value so
 * the letterbox edge has no visible seam.
 */
export const SEQUENCE_BACKDROP = "#16181a";

export const sequenceFrameUrl = (i: number) =>
  `/sequence/f-${String(i).padStart(3, "0")}.webp`;
