/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/collections/{key-facts,gallery,assembly}
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

export type ShowcaseSource = { w: number; url: string };
export type ShowcaseAsset = {
  id: string;
  alt: string;
  width: number;
  height: number;
  /** null means "intrinsic size, no design frame" — a scan, not a crop. */
  ratio: string | null;
  lqip: string;
  avif: ShowcaseSource[];
  webp: ShowcaseSource[];
  title?: string;
  year?: number;
  note?: string;
  caption?: string;
};

export const KEYFACTS: ShowcaseAsset[] = [
    {
      "id": "kf-compete",
      "alt": "Organisers and faculty holding the Robo Carnival 2024 pennant beneath a cluster of balloons",
      "width": 720,
      "height": 900,
      "ratio": "4:5",
      "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAsABABoJZQC7AEQgYcICq6cAAD+zQNJA+8MggR12pNU5SSKf7lftMEqoNtzRwPLeXs5UfDVyHf2Lg0G3Cy9wmZR/AAA",
      "avif": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/2e/45/2e45bea8236240a3d8e648a7c4a49ce2b07fef27f79975e3bef930dc5a73d40c.avif"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/cd/94/cd94bdaad728acc990f9325c406bad48224dd34d912e4abfa3e959a7c910a93f.avif"
        }
      ],
      "webp": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/02/be/02bef149a9e01da256440a4ad2c28b6f4574e2e4418504772aa5e159a1528ce2.webp"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/c3/7b/c37b6568882e360d5ea2b4762613b63a50923f1e214fa8d07eb5613b434fecfb.webp"
        }
      ]
    },
    {
      "id": "kf-teach",
      "alt": "Participants standing behind a full-floor line-follower track at Basic Workshop v8.0",
      "width": 720,
      "height": 900,
      "ratio": "4:5",
      "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAwABABoJZQCdAENX1PdAAAA/ldWrni1DYYKpldIhjLbfvXU1Ocopadd+Ev2hTRi4L5crH/xDiAA",
      "avif": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/5d/ad/5dadd2bbec33e7117051758ef17dde52b09082634e9000ce7dd615f1a10af0ff.avif"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/fd/48/fd484a5ed54ede72061f0697e4117d423e65e7d2de0b21ced5654047307570df.avif"
        }
      ],
      "webp": [
        {
          "w": 480,
          "url": "http://localhost:9000/brs-assets/sha256/8f/39/8f391cceddfabe0d33261316db3c61608545cf464a4854f3e087f8362f5afb1b.webp"
        },
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/b8/90/b890fe241b8e1574bbff6e6f2b39f868c3f56c630f7804071c6ed5712b75d23f.webp"
        }
      ]
    }
  ];

export const GALLERY: ShowcaseAsset[] = [
    {
      "id": "gal-rc24",
      "alt": "Organisers and faculty holding the Robo Carnival 2024 pennant beneath a cluster of balloons",
      "width": 1440,
      "height": 960,
      "ratio": "3:2",
      "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAAAwAgCdASoQAAsABABoJZQC7AEQgYcICq6cAAD+zQNJA+8MggR12pNU5SSKf7lftMEqoNtzRwPLeXs5UfDVyHf2Lg0G3Cy9wmZR/AAA",
      "avif": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/8a/e2/8ae2393efc2d89fe980b5a3f7549c9b828ffc4fafc3e8f97fdff20af54ef4ecf.avif"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/d7/79/d77944ad09a4a934cd5f09aba263d8cb76994b4d0d58849eaa92f205181a1609.avif"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/dd/d3/ddd32c1e52db66863489c037e425f77c564655ec214cfa64589021ef52996ad2.avif"
        }
      ],
      "webp": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/d5/ea/d5ea6e003d7c532a75cf17dfa4592cd0dd9c665769adaa8873dd50f871bcc923.webp"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/f1/40/f1409c4bfaf13a2e2c9c309e082ae6a187ae5e6380a0e666c554d93f8dcfbb90.webp"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/9e/20/9e20ee723608e24e979ef7dfcceb7df9d048689f7da49ac1f6d488ca4ecae62d.webp"
        }
      ],
      "title": "Robo Carnival",
      "year": 2024,
      "note": "The society's flagship public event. Five segments, open to teams from across the country."
    },
    {
      "id": "gal-intra24",
      "alt": "Participants and faculty gathered on the ECE building steps at the Intra-BUET Robo Challenge 2024",
      "width": 1440,
      "height": 960,
      "ratio": "3:2",
      "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAAsABABoJZwAAuWvxOFgAAD+sPaog2x+jTyYuMuTdHr8TjNdwksoFuNOf3t4Ljl3GXeDICvDZfb0vXxnc0AA",
      "avif": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/b6/05/b605aa1d77125e9965bb1e7714b14257a3d0b6594f6b7c8fa652f4883c9adf62.avif"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/cd/42/cd42376c44092a4752caacf6876c27d85157081a91379a038f6e5c372f26d5aa.avif"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/d1/ea/d1ea4ccd915f7e1246f1b88596b3464978ae1ce799ab6884093a65206480cf79.avif"
        }
      ],
      "webp": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/26/f0/26f02ea8e179db1b4db29aea48e79a82142fa76f891bf5b70b10d1b8bb3f1eb4.webp"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/53/d2/53d29ed0686842ec68348682b2740e028818eb4f7152d2b20ad5c222f70e4a3b.webp"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/4e/0f/4e0f3783a8bc87cb9343d0018aa428ee57595a0a9d989edb3370804e0db48299.webp"
        }
      ],
      "title": "Intra-BUET Robo Challenge",
      "year": 2024,
      "note": "The internal competition. Teams form inside BUET and build to a fixed brief."
    },
    {
      "id": "gal-rc19",
      "alt": "A row of student-built robots on a bench at Robo Carnival 2019, their Arduino boards, ultrasonic sensors and jumper wiring exposed",
      "width": 1440,
      "height": 960,
      "ratio": "3:2",
      "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAABQAgCdASoQAAsABABoJZwAD5FRf/wV8zh0mgAA/olhiT4unGIOU5acP9yeuvGP4sWpbJtepghWdEiwy8HbSEX90QOPPOzI1VMwzBqpjngSjUrO/AAAAA==",
      "avif": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/b0/5a/b05a23f5b80f327699e88f3baf02bdece74814c1c47c1c37d6b686b41808af66.avif"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/a8/c6/a8c6605274b292cbad110e5d8021d433fca7b56deaf13a6486275edd08965a1f.avif"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/a3/b4/a3b4a18523366908d5cfc3cb69fbcd39fb562f23c6976da099db8a03cb0a6197.avif"
        }
      ],
      "webp": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/24/00/2400e612e200d1cc1aba8c4be88298a04b48c9bc98ff608547dfc24a23f2b3cd.webp"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/ff/e6/ffe6f09590edeecea5128f21efb488f290ca633092a851922789113a5a877cb6.webp"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/26/a1/26a1da4adb7445086a80ac2779313eae75518db197da8cd8b1b3edadf03c809c.webp"
        }
      ],
      "title": "Robo Carnival",
      "year": 2019,
      "note": "Boards, sensors and wiring left exposed. Nothing on this bench arrived in a case."
    },
    {
      "id": "gal-bwv8",
      "alt": "Participants standing behind a full-floor line-follower track at Basic Workshop v8.0",
      "width": 1440,
      "height": 960,
      "ratio": "3:2",
      "lqip": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADwAQCdASoQAAwABABoJZQCdAENX1PdAAAA/ldWrni1DYYKpldIhjLbfvXU1Ocopadd+Ev2hTRi4L5crH/xDiAA",
      "avif": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/87/72/8772b9c0ae67d1a2f2461ea35c9d93ee976830f4f98cc143322a1ac45c0e1e0b.avif"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/31/c8/31c88e20a26b6055970bc1ec5e3ad97040d0a4f88f380a8a095c590807de638f.avif"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/fb/08/fb08cd034200d459092fd9e5ce646b06377f0f140d94170963d2b8a6a7058d80.avif"
        }
      ],
      "webp": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/41/0c/410c8b4d8c808817e93f1642300a2b5c23cccbdb8ee5178f248990cad9c3366e.webp"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/ce/d3/ced31a4ce5c220626be6eba49a68e5851b9bc44ea5ab05928fa8a683503a587a.webp"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/79/a4/79a49c3a81023ff1345b2f9308de2cd47ec0d689de5137eb73ea75865ee0293f.webp"
        }
      ],
      "title": "Basic Workshop v8.0",
      "year": 2024,
      "note": "Four days across two weeks, ending with a robot that completes the course."
    },
    {
      "id": "gal-rc17",
      "alt": "A robot lifting stacked blocks during a Robo Carnival 2017 segment",
      "width": 1440,
      "height": 960,
      "ratio": "3:2",
      "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoQAAsABABoJaQAD5LRau5ayLcgPIAA/sEpzj7HctRU7ucf50d989CZxwr4VCJ/M11rQD+qnMUcis56mX+oHEhdK11bTl0viaD7OsNjVePqgAAA",
      "avif": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/e3/9d/e39da65badc399d0f916966b90638a5a0ab0c6f49b824366490bddde05e76ca4.avif"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/73/6d/736d4b14b9b777a62a05f9c855982d907bdf525f14db7ee2de7a638ccf05e791.avif"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/ad/89/ad8930af63bdd0ca446a2a68687526b0e095d46dd2024cfb5cb2eeefde8408cc.avif"
        }
      ],
      "webp": [
        {
          "w": 720,
          "url": "http://localhost:9000/brs-assets/sha256/da/89/da890860368f1db9b52ad05c2a1d6552a000ab1f598077aa7a3a89f4b0ac5645.webp"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/e6/e7/e6e7416f9f848878024d8af62e6c1744352ec655cc656f64b9d490136f526c42.webp"
        },
        {
          "w": 1440,
          "url": "http://localhost:9000/brs-assets/sha256/30/34/30346cd3aedab3efd5d0d5702f9a5a4179f79dd4e9640370c3b8788ee80f622f.webp"
        }
      ],
      "title": "Robo Carnival",
      "year": 2017,
      "note": "Manipulator segment. Blocks stacked against the clock."
    }
  ];

export const ASSEMBLY: ShowcaseAsset[] = [
    {
      "id": "as-rc16a",
      "alt": "Participants and organisers on stage beneath the Robo Carnival 2016 banner",
      "width": 640,
      "height": 480,
      "ratio": "4:3",
      "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwAgCdASoQAAsABABoJbACdAYvhkrD/McBgAD+73igcpKjONgbQKIUNnrDXeAA0jAppuFRdAQBbZ/XAXBgmnQMdDiqXHS/mOZasi4CCj0bpwcRsu35Lb60ZGKHgssbFAIgAA==",
      "avif": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/77/34/7734a1f6a21c5fd1febbcdec6a2d96473dd448d5b730a2d889bf598fbe77d6e5.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/95/bc/95bc4ad351c17000cab4bc4a935647b6a7f94c59d88ffa5c5972df13b4a481c7.avif"
        }
      ],
      "webp": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/9a/cc/9acc079031ab836419d05a67d798376967b501a7be32e020d9af5d56a6ec551c.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/06/cd/06cdb443d4f44dc7d8f3148c94aa70a77be6c8366b54fd669a8690a28eaf2e8c.webp"
        }
      ],
      "caption": "ROBO CARNIVAL 2016"
    },
    {
      "id": "as-rc16b",
      "alt": "Competitor robots arranged on the arena table at Robo Carnival 2016",
      "width": 640,
      "height": 480,
      "ratio": "4:3",
      "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoQAAsABABoJbACdH8AGBiIecf0AAD+8Z/I5S+zlmBmzxwh0FPORoismm40azUfmGmS96Xt6z6yMT8YwsRrrp65/eiHxe4WIAA=",
      "avif": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/ac/89/ac8969aa4ae472a29ca6382b6e384447efe468af0b11ad6f5ad5ea75ffe9207f.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/fa/93/fa93ca7b9ce4f80d2f568031f7a0b361065e2b6696e1e09e65b671998df55cf8.avif"
        }
      ],
      "webp": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/5e/45/5e452d710fe529a1f24e5d91f6ab05d44c554aabf7c71542a8fa48a641cfdac4.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/55/ec/55ec69426a2143a97f5854b6491924f8600ed43e3147e87d06cc0200fbacc5e0.webp"
        }
      ],
      "caption": "ROBO CARNIVAL 2016"
    },
    {
      "id": "as-rc17a",
      "alt": "Winners holding certificates on the arena floor at Robo Carnival 2017",
      "width": 640,
      "height": 480,
      "ratio": "4:3",
      "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoQAAgABABoJZQCdAD1kff5wPAA++S889ozQK657w2NX9VHLn3b2HqlSA/RKVI2mxZ3ndeVPEwq8Kl/u3I0MpAA",
      "avif": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/d6/ff/d6ffca3f97a1a36826d61dc3e0e303b2f7977320a04cac029300469112cdc861.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/ad/5f/ad5fe272b9c2cb6d2eea09dba8d8c060351878676ff7abf525d07182bc341af9.avif"
        }
      ],
      "webp": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/be/14/be14e3369f0f90fa9c6d456122268dab65d9a97fc58fa3100b3c3bafbae51809.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/06/62/06620eba3e1993a137482554e9db9dd28743a73cfc05e8d240d40929e48b7462.webp"
        }
      ],
      "caption": "ROBO CARNIVAL 2017"
    },
    {
      "id": "as-rc17b",
      "alt": "A line-follower robot tracking an angular black course at Robo Carnival 2017",
      "width": 640,
      "height": 480,
      "ratio": "4:3",
      "lqip": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAADwAQCdASoQAAsABABoJaQAAq83M7jLxQAA/tDvc/dBh48rVVJq1BdlB1TEmaIpnJXVDsdLZqPVpCJ+QJAAAA==",
      "avif": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/8f/9f/8f9fbbafaf37e36adb0878eca5db44c39c1c435562e17d1ee18bd511b76a8738.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/23/bd/23bd00002bddb7054e03b90e70c3ceac50c51a3454ac0a44e4a02fe38dfa9bcc.avif"
        }
      ],
      "webp": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/e6/79/e67916f56816cc51eb4687b2a8c64d218a0800cde28c1dcefac79945692d040a.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/fd/2d/fd2dffd7b2906c0186116eaff70631f67895fd8e6a14c6194ea8f44c182404a4.webp"
        }
      ],
      "caption": "ROBO CARNIVAL 2017"
    },
    {
      "id": "as-rc23a",
      "alt": "Teams lined up beside the arena track at Robo Carnival 2023",
      "width": 640,
      "height": 480,
      "ratio": "4:3",
      "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoQAAwABABoJZwCw7Eei1+xx4AA/iX4pap8/Q01PPViKD5ICF5m2xbED9q8DzDjxU99Gbry8hBbHz6rfGHgAmSHbgAAAA==",
      "avif": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/69/76/6976257cbc3fcc680becc07dcd6cccbd24ec267ae3bbb0b150283157427461c4.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/c2/72/c2725d21f910517f2427490977bb9527707449053843cb665e59b92eb1d3c4b0.avif"
        }
      ],
      "webp": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/08/a8/08a8b10e4a7f5605a7b7e9aac3371b35bf9fdc1cf653d55c45afe9f773459378.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/a2/b0/a2b0d1fa9173088c6d5970fa17da0e7205fb7ab45df4f790bd5113a1f90e6e3e.webp"
        }
      ],
      "caption": "ROBO CARNIVAL 2023"
    },
    {
      "id": "as-rc23b",
      "alt": "Two robots on the hall floor before spectators at Robo Carnival 2023",
      "width": 640,
      "height": 480,
      "ratio": "4:3",
      "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwABABoJZQAD5JwL4UDq6AAAP3b4H96DxcyVayz1aqoMB65fEI9WldozSEKVwMgcXKiMpcDiI1aYxzWmNGb5l7GpTskd9iIzaDUY4AAAA==",
      "avif": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/d7/8f/d78fabace5d6d545b9207802cdd7e6bd2a2f99cebc3d52a1e22aa0333b9685e6.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/cc/4e/cc4e7d325fbd38c309be5901b58454b795fa27f575ed10d2e8bd91e36d5e98ea.avif"
        }
      ],
      "webp": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/0e/e4/0ee4205cffc71b75b6de5259392e9ccbea668e4eaa87a3237df153e3295b7b21.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/54/52/545247d2a94b24ae42a830c2b38679bcbd0e537f675a1b11eba55b15ae84853a.webp"
        }
      ],
      "caption": "ROBO CARNIVAL 2023"
    },
    {
      "id": "as-intra24",
      "alt": "Line-follower robots lined up along the track at the Intra-BUET Robo Challenge 2024",
      "width": 640,
      "height": 480,
      "ratio": "4:3",
      "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAQCdASoQAAwABABoJQBOgMXXeRwGAAD99e1GL9EfHlx4xWodxrcsVR/nMRy0EmUPp+TDXg68V/GyLPEIaxo2msP3pBT4TDMz+1vQ3fGKsgAA",
      "avif": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/c1/21/c12149c8cbed5fba636e1d4855accd41362595c1e134d38e4b5b9dfdb71625f3.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/ae/3e/ae3e768245d148668f11305fb2e89e7ac94c78ee45fd19e50204494557cacb58.avif"
        }
      ],
      "webp": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/5a/f4/5af43deee4354e84d486fe911fc8ba093dd8340c68632dad8436596945700a6c.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/50/fb/50fbf717f769146c9fc007ac5ea705e0f8cdc7b1f889b5855b7a6047f9d6c991.webp"
        }
      ],
      "caption": "INTRA-BUET 2024"
    },
    {
      "id": "as-agm24",
      "alt": "Members seated in a BUET lecture room during the 2024 Annual General Meeting",
      "width": 640,
      "height": 480,
      "ratio": "4:3",
      "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoQAAwABABoJZQC7ADOljQxiKHMAPPJU3g/13LH0Ym3VnMSZjm9dTNsJyXYqIb/oZ+YF1J0xyKonn9l96LT419Ly/l1qvhMF+LS6YgA",
      "avif": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/bd/a6/bda6b4f0d697139c605f24a9da2754719e45e844d75fb494e9932e1b3274c9d9.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/b1/d0/b1d0de0748b7ecfc7a271d2464a7636ff93562d5181abce400e64a03cc7ee1ce.avif"
        }
      ],
      "webp": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/58/f3/58f3bc3027fe03546b5fe15f06cd4fcc9b18560b44288e9120069b07f41f6b20.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/c1/18/c1180e49db08c056aa89fe14258c8aa8dee6078f764570128522239c4c65006d.webp"
        }
      ],
      "caption": "AGM 2024"
    },
    {
      "id": "as-ri24",
      "alt": "Attendees seated in a lecture room at the Robotic Inception 2024 orientation",
      "width": 640,
      "height": 480,
      "ratio": "4:3",
      "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoQAAwABABoJQBdgMX6rIJKYNUAAP4TlABU6Qv/5Jml7Vpcnsci1gq5EYNmt8JQn6BKOZ/cOylgy7lJeXSftaHDr347mCASc7+tuYlEE4AAAA==",
      "avif": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/7b/73/7b735fa751b46de52f2ed06255709750e18dad04f253c4c54a564fe5c7e76863.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/28/40/28408870823327c233a9ca6366a957e53169e1fd87969477d3219b489a45f8e9.avif"
        }
      ],
      "webp": [
        {
          "w": 400,
          "url": "http://localhost:9000/brs-assets/sha256/46/15/4615714b1bcc78524abd8d8ef646f1e2ddd1fa249c0c31c9b67ce140c6f4cbdd.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/06/ae/06ae605b9b796a2afd8cce53264bb55b0154aaa5e8d631f9ff6877a4a026a972.webp"
        }
      ],
      "caption": "ROBOTIC INCEPTION 2024"
    }
  ];
