/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/aaaaa
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "aaaaa",
    "title": "aaaaa",
    "category": "workshop",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "authored",
    "html": "<p>wow..this is rea<span class=\"rt-ink-petrol\">lly cool wow.</span><span class=\"rt-ink-petrol rt-mark-warning\">wowt this is working..</span>...<a href=\"https://www.facebook.com\" target=\"_blank\" rel=\"noopener noreferrer\">this is the link</a></p>",
    "plain": "wow..this is really cool wow.wowt this is working.....this is the link",
    "cover": {
      "alt": "Md. Mosaddek Hossain, Assistant Secretary, Workshop Team of the 11th Executive Committee, BUET Robotics Society",
      "width": 1500,
      "height": 1800,
      "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoUABgAPzmKu1avKSWysBgIAlAnCWMAyNQMNnhYGvc+d4+fqmAA/tlYeTYi5Ybo4+LQ2gpfDdTkJneFV2fDHlrTCVG2C2Ij8k5b2jQ2s5cjYoKzfPN6tuDQJk4doqx/t8AAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/30/0d/300d8d4ad0cf677b5aec655aa9e80d71f38eb473e3883bcdb20d5d560c77cdb1.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/ec/74/ec7456c59591e1c75b2d5bef70394a3556a2a4d8e499fd56b68345215d1aca7c.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/ac/29/ac29e1c8bba5887a8de1ac63d2c226a2f48aed90abde7aebafebb7788bb780f1.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/1a/87/1a874f4436eaee9442fb23b6c78642aee524cd2eefbd032835ea7513f09d5d2c.avif"
        },
        {
          "w": 1500,
          "url": "http://localhost:9000/brs-assets/sha256/05/8b/058bed878722fcbc3393f18927cfb94b48ce424d442ad7aa56e90350a71b68dd.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/52/b1/52b167ea685478dbfdb49e5ac9c96491403a3c62fea275c91f9db6586018ac42.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/d6/32/d632830ec490819e5c6dcf4a7e728ae75ab54459bd6755c143ef8cb8eed7525b.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/4e/f9/4ef93475cbc3d5f173e50bff0fa3889fa8519c2535fefae99abe83f032b8f8b3.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/07/66/0766a87915fc797f5dc2015a2f03be23c61f00a3980852dc5f693f618998b5ed.webp"
        },
        {
          "w": 1500,
          "url": "http://localhost:9000/brs-assets/sha256/8c/68/8c684ecb556987c269656bf3a0a54642f7ea759a497f2b0fa79c4bf8f1866877.webp"
        }
      ]
    },
    "gallery": []
  };
