/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/agm-2017
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "agm-2017",
    "title": "BUET Robotics Society Annual General Meeting 2017",
    "category": "agm",
    "edition": "2017",
    "year": "2017",
    "categoryName": "AGM",
    "copySource": "web-ready",
    "html": "<p>The BUET Robotics Society held its highly anticipated Annual General Meeting (AGM) on October 15, 2017, at the ECE Building, BUET (Room 535). The event brought together club members, executive committee members, and the honorable moderator to discuss the society's future plans and initiatives.</p>\n<p>During the meeting, the newly elected executive committee was announced. Additionally, key topics were discussed, including:</p>\n<p>The problem statement for ROBO CARNIVAL 2017, encouraging active participation from general members. Upcoming programs and initiatives of BRS, providing a roadmap for future activities. The introduction of a mentorship program, where experienced members were assigned to guide juniors working on robotics projects.</p>\n<p>The AGM also served as an opportunity for aspiring members to express their interest in joining the executive committee and contributing to BRS’s vision of advancing robotics and automation at BUET.</p>",
    "plain": "The BUET Robotics Society held its highly anticipated Annual General Meeting (AGM) on October 15, 2017, at the ECE Building, BUET (Room 535). The event brought together club members, executive committee members, and the honorable moderator to discuss the society's future plans and initiatives. During the meeting, the newly elected executive committee was announced. Additionally, key topics were discussed, including: The problem statement for ROBO CARNIVAL 2017, encouraging active participation from general members. Upcoming programs and initiatives of BRS, providing a roadmap for future activities. The introduction of a mentorship program, where experienced members were assigned to guide juniors working on robotics projects. The AGM also served as an opportunity for aspiring members to express their interest in joining the executive committee and contributing to BRS’s vision of advancing robotics and automation at BUET.",
    "cover": {
      "alt": "BUET Robotics Society Annual General Meeting 2017 — BUET Robotics Society archive",
      "width": 2048,
      "height": 1152,
      "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJS7AKaO//AoGnvAWoAAD+7R+YtLqp3fOYOIjFyCqTf9y3nabfa/CVp9wqUo5bJ3zZuWvhc8JAdYCI9yj8BvCA8Evd9A6takQAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/5f/9c/5f9c91f351a705b1d59d66184179d7b5e80090f9cf59b2845b527de865f97173.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/b3/02/b302e20211dabe0f7a92132cdb0bda40b482cab0c3bf25e8f462560ada11c369.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/c3/cf/c3cf58acc1591cf98166b9c1d7c33ec62cc324331fa7a2ec0cc3bf0ef6fd8e86.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/ef/5a/ef5aa51f99893703eaea78b94c7f016a2095ca9c0bb5c0db0a743fb91ff908c5.avif"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/ef/ed/efed4ede22692843edfc4d78d72fc4628ec93d64475eef752cff6140feaca29d.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/d1/03/d103dd97ecc12c794940c3eee3dfb76035733e20fa1e3976e16bdd4235888d1c.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/dd/bd/ddbd5744b022c9a33c33def24b7d17360b65cc8081a4b10b17da8dc93db2ca82.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/5c/5b/5c5bbf8cdaacf6999f22fccb2bd5d1cc7b30f6381287a3fc68f7cdbe861b7d0e.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/f6/d0/f6d09f36499e6bd0ae21aacf3c2b92033994821776eb6e4bd088fadd219fa3bf.webp"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/94/c1/94c1df97b9be066cc70e3922ece5f1faaee2ba82281723b670523b128f4cb3db.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "BUET Robotics Society Annual General Meeting 2017 — BUET Robotics Society archive",
        "width": 1365,
        "height": 2048,
        "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAwBQCdASoUAB4APzmGuVOvKSWisAgB4CcJZQDNwCHR1IjYD2aZiOO7c2EViuu5wLG/YAD+dbRf+iOC4msGzBZW6r4gAgIOxT+7H4mDozgEQ2G8KzEC5cWPbcI13IyMadgFDtUtAiu1qYtVtRnRgfbRZjt5lh0ha9igUnWmJXoyMbtiANin8z8hvP29rm86LsrIhDm0hp51FkP8XBIpPZdYxn8wAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/90/59/905984d77bf1af2cca6e6ef22e1e8c21668b916d7d1e3af87085532830c5b824.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/79/7d/797dd49a820d7e9548d837e73173f9e80a201cebb8a12824fa73a808c2ad759c.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/e6/ff/e6ff00c2598ece38030daed4293a1523fe210e722b2f85f8dd8b594e01238cad.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/9d/b4/9db4b9af1be95056890af5b13267eeabd475743937adef364c4450d2b778e93f.avif"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/1e/a5/1ea5312faec5248c18d88ea07d6633a2c17ac010dec69092c3208d7ef1fb96f7.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/e2/09/e20963aeb93541c57f4f596e9e8c58df35e9f19939b5bc0909f9ae73edca4dbc.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/9a/29/9a29beb710687667b724933de1a97b6f878bd4d6e3d2656924f6545856ab6a41.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/04/6a/046a2f5b376a09729e925d7f75ab7d0e691295ce9a0512a78ad9f367b30acd2a.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e7/e1/e7e1eb976a300eb7efcbce470c53ca8cb6a306337fd9bc72329d13532cb85a35.webp"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/a4/12/a412d281d9452d464ec4f8052c82d39e3f822cf59a7165e4ffa00cfa13faa4ab.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2017 — BUET Robotics Society archive",
        "width": 1365,
        "height": 2048,
        "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBQCdASoUAB4APzmOuVWvKiWjMBgIAeAnCWMAzfwRD0txjr3C0Onh5csHfOAZWe0RiAAA/ZeJ8MTLTH1I5m3PNEXXDe4ScpRGeAfEcil8ILMS5J0q3BH+1xz7b50ydVVhfJg4a6LwZKq0fOM0Y7WpvIJZqNm2kmeUEM8GILJlMlXL+NwtiKfgxfgAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/63/18/6318bb2c639481a02a0efd75aa4062b6738ea65cb1ff0128e7065108f128262d.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a4/17/a4178a54a69a361a493db02fcb14d379defb4e085aec7618a01d3371fe8fa7cd.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/fc/fd/fcfd66105f7eed84913964359ae7415e30a8a7a56308f13c440cbd8938e950dd.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ab/b8/abb8f5476ede2ccbd43b430da4896be59ecc5ad8ed6d5bdf7e798f8310652b78.avif"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/b2/ed/b2edd239a2361873ca0ac8877c62b9ef3503e6cc6c9f2b61bbc35984597b303a.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/6d/e1/6de13f52384022e96c925a522ee6eaa28dfe25ab04ee1548bd0445bfa5ca7c37.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/b2/84/b284b3e92acecafbec952e851499e22ecc0991ffabdec07be88e5b36e2f25a81.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/48/e4/48e427ce263a4f9026b366777d10ea51e73a3117c9aefd5479a3936de14329d3.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/37/53/37532226b599dd122f8c99289cf1763f5c29e4dab8e11cacdebd013ee403b338.webp"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/98/9a/989a898d487fe1e0e34296a45a3ec00a77f72cf1cd36142bb87a835bade2c89d.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2017 — BUET Robotics Society archive",
        "width": 1443,
        "height": 2048,
        "lqip": "data:image/webp;base64,UklGRrgAAABXRUJQVlA4IKwAAABwBQCdASoUABwAPzmOu1YvKiYjsBgIAeAnCUAYm2WAGIYt2Sf4F9ti8rDY3kqwGmbP8+EAAP4/dpVDCLFNIXOUPDmoEeBOVa+0TdFQYZBXiyw043RCfrCkjYBBDbJOPTwcI2li3PUlSwJsJ6kYdK+lpTQUi8KrB9ugk2IVye080Iw13sOkASEKavtxFoGqSrH5LH1rnHZE027abGkJ8StSH5vyHYsVN3GgAAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/06/07/06072966315aabca91d198f3c061d7b94aede6459c36d20a9bfb34492ff8441c.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/69/e6/69e6597dd00e7a8737d57a677f08e275b347a332d4daaf9440fa41539eae9353.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/80/2f/802f639423b573bcd066d9f21d52f485d641997b1f25b61f2e9613568684f80d.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/77/4d/774d4be8b74583d80dd7bcdc4d97a31fce05178f23aa4720e0c6dea7d4166650.avif"
          },
          {
            "w": 1443,
            "url": "http://localhost:9000/brs-assets/sha256/ec/54/ec545959d0bca422e2fbcaa4d895e2c8569310a8b981a8842b22d290bc322531.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/96/37/9637b177d1ec9abb52ca4f12065d10ec506b7f5b6ba0454922e7d91a5de50faf.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/1b/3c/1b3c7c95e5fa71ff9e0676d60820dfd1c13500d82413e5a1b1a6ae2312ab1ac1.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/7e/7e/7e7ec9334e234948409fbff5627417846c233521936f028eabaaeb7f840a93fe.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ad/ea/adeae412cd4dd28b511c1926916624b387a673a8a52295e03a49423615acc571.webp"
          },
          {
            "w": 1443,
            "url": "http://localhost:9000/brs-assets/sha256/68/2a/682a23df3ff90282a5d1ef70530d1b8e11d8c2c89a0ce6a42982419ad7ac8aea.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2017 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoUAA0APzmIuVQvKSWjMAgB4CcJYgAAW4znS12Jc2nwUgAAyx5ihFVB5N1kb2P7eYPBBgObkuaTJx/z3B+Bv+MQLF8LpMmctjeaibUE8/4ihCR8CAAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/26/ac/26ac45434b24a7ccafed35b45014965baca7e80bb13ba1eff5a80de31459a29d.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a9/6b/a96b7ca6ae323449591fda9cc0e0d2155bd76b602e86f34933e2c813ff0d7125.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/9b/6d/9b6d04c46658efe319410358cd38c498778c16cda03dc8cb42c5d7298b3d7722.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e6/81/e681fc993ba0c7fce1667b83ef28be8bf2157aae9b1d2cf4259c560182d7d590.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/85/5e/855e400940edbe468ab1c0e2dfd6d4afb24b5366f92484b1c584ac6fb8eb7342.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/bd/48/bd481f303bcfa7ca6caff3f79ca0f1c004a77659414409c561928c0baa5782f9.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/18/84/1884a039279b4affd212d293d8f06a4821970b0e5bad6fdd485dff52c9078557.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/64/db/64db1c0e84cc197589c145e1b8a1ce20cf85e64f9f50b503ebd34c75c06e018c.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ba/c9/bac904742dc1b07ef537cee0a94549671893c43e0657cb2ae208980784cf6769.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/59/e7/59e7bae48e755abb106902be8587c6e36857929e566af52b70236dc64fafd72d.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2017 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJYwDE2CIAFVy+gNBIY0IgAP1PvpN9mQ87n0nDie4FvJYv8YypSwAgj9I7IXjn2j8EJCovg90MAAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/74/fd/74fda6d11be3818aee902dda156014889793e2ef83ed0d558891e91b1aa09426.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/05/ee/05ee0932466d8f5530317d40fc7ffd4300fdf729c103ac38d10fe6eefb95565f.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/e1/c4/e1c464d4b69c6a8f56414b08d01310fad9d80da39992fc9ae0f182069ac210c7.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/39/a3/39a3df586d807355f8c6e87950de611efc303c09fdd1a8fa736a0697b15ffa5c.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/05/9e/059ec8d53d59b507b2b71ba7a407e42bf8417ce9b6034e0e4ef9c5d56cf953b9.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/a3/a1/a3a102cdc2872f32b701a6211595c6927960b7046f87f3dae6f9def538a2a899.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/f0/7f/f07f67eda12bb1aef1b6c9df2c0151b0360c35288513f57c99b39afeb0c13c67.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/ad/09/ad0919b51f39474e301dcf0348191a4f91dffa3cb99ccaee8d88b9934396e4bc.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/5a/70/5a70c0ceddd4596409606f465a4bc440af29f6d855649d815c78a7f01fd79e0a.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/27/32/273287ab73fb1cd5b423e5e83182a0fa9deae7ef62280cd1e55df6b6febaa139.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2017 — BUET Robotics Society archive",
        "width": 1365,
        "height": 2048,
        "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQBACdASoUAB4APzmIulOvKSWisAgB4CcJZQAAVGFahSXrxV2qGH1vYl9ttxJMAAD+zXw9MhtEb7qEOaj8ZX96fuh3owTGA6NkYgZ5fBmBLviR2Er/u9fK4gEp4yeiehOKoTY5mSd5ZPt02cZ6caI+6HGAQ2FcBdADIlbZFg2Ladve4O37e6NMXAAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/70/9e/709ee178e392084e126689bafbb287ab2a08d1665f1a4f8a4965b1cd09abbc84.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/2f/e4/2fe45f12f439a7d0855f0aabaa33d4b88dccd5aec45cd78d02fb86bcd2610fe5.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/87/30/87307836f8eb3484703b17a81719e62f8bd2c03d09de0b4c6b230a4e783e18b5.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/2e/1c/2e1c1b579770fd733ff224dff1f22b738f55c4319a6bec920de1d1ea466b4072.avif"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/33/b4/33b4c5927b31e5c1eb15c7c8631b8100b6b7655d83987b96f7e0144d5097add5.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/6b/aa/6baa3c60e1ac4f1f21c3abe7e8d3e3ac929959ea3ecc79da36f475b7616cd671.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a2/a0/a2a06aef40258a865b6fc513a6b9c8266a88ba8e56bbdb95bf30b980ad2c2efa.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/d1/98/d19816ee08b14b0077fe58b69820d2d9553948089a3c999d11dc321f1d8a8cba.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/64/65/64651b1db1ebddbb94a3c5ebec08e5c8fd50b36fde0e3534dc3a11827dd633a4.webp"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/01/df/01df99a247c152f136a53414fd3146aa797d20765dd76357ca85c31af5b465ec.webp"
          }
        ]
      }
    ]
  };
