/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/agm-2019
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "agm-2019",
    "title": "BUET Robotics Society Annual General Meeting 2019",
    "category": "agm",
    "edition": "2019",
    "year": "2019",
    "categoryName": "AGM",
    "copySource": "web-ready",
    "html": "<p>The Annual General Meeting (AGM) 2019 of BUET Robotics Society (BRS) was successfully held on July 10, 2019. The event covered essential announcements and guidelines regarding the club’s upcoming initiatives and programs.</p>\n<p>A significant highlight of the meeting was the announcement of the new Executive Committee, marking the beginning of a new phase for the club. The newly appointed committee also introduced their vision and goals, outlining their roadmap for the future development of BRS.</p>\n<p>The AGM served as a platform for robotics enthusiasts to engage with the club’s leadership, gain insights into upcoming projects, and contribute to shaping the future of BRS.</p>",
    "plain": "The Annual General Meeting (AGM) 2019 of BUET Robotics Society (BRS) was successfully held on July 10, 2019. The event covered essential announcements and guidelines regarding the club’s upcoming initiatives and programs. A significant highlight of the meeting was the announcement of the new Executive Committee, marking the beginning of a new phase for the club. The newly appointed committee also introduced their vision and goals, outlining their roadmap for the future development of BRS. The AGM served as a platform for robotics enthusiasts to engage with the club’s leadership, gain insights into upcoming projects, and contribute to shaping the future of BRS.",
    "cover": {
      "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
      "width": 960,
      "height": 529,
      "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJagCdAB8qGMimsp6KAADyn1UFHUXE8LUdUA725QmA8mRwNqXK4Vt2CLV7ZSr02B/BuRVgbCaNVxAeeX40th2lYkOJzW7MhAbih2sEGNCGgAAA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/c8/5a/c85a2b2972bf7950e688b4d1db6d57cc84650dfc62b88b6756a1b34cb05a3515.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/d0/a8/d0a8ca6bb42d97911ff1cae4e60902ba9a8e314cbf061f74d4c8e7622f1e196f.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/04/3c/043c7d6db2a1449a12392ac1efaa60dacce37179e608859c41676f5837df9400.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/e3/9f/e39fce97c65da8b0ebf786a1283cb1d4a8e5587e729c1d2c3203a98661a8c7bd.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/5a/20/5a20eb79b573ecc48e6e498f47f5a4cbfde66ac9382809de9e07161b4b0a0ba0.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/75/b9/75b929870a91c3cb77bbea2cc971a14b29fcee99186a0de8b3c445896ad37d09.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZwAAUoHAkXLanywAAPfehWklfMmWICfVEdH7IAWgjvcsWIR6APgv6Wt7fOYC3r4FsTMr5jBAiBXrkdJrRpFYmGLGbBVd092IYCAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/29/1b/291b34b55f80ea4062cd6d19aa1ffa6d35b8d4b596d4a88fb97fcca461847d72.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/93/4f/934f19a593891e02e1f8431cd3489d5bfd9bea2d8d2bfee179831f16a740a5ed.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/b3/b1/b3b1c97deb83089b09829d2a14c3ddbcc78f5cb05b7c207216664219329a5be1.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/2e/bd/2ebd2e31a5d9a59c8c90a619ef6879fdf6e7a0da6f138f47bfb69ce14e08351c.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/28/03/28039946d1ec8e782a5c784739534f9191e26d4240dc5718551dced2a44f5e1f.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/21/b3/21b3088c797f249fb4b8db1d7fff70a3cad28ffb63437f7aa97f1a6f0c3366c7.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/6f/86/6f8699849875016dc3b7b8ad02f6c7f79cea08f5beeb1119f5801c677d356fee.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/f4/64/f464fcdca36e5e196d036d3f4507c20ec9655e904e5c110f9d60b67a08280bb5.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/bf/7a/bf7aa9c3da8f8ea01689b0b16ff95be78165dca004021bc99d376be61c35ab85.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/2b/bc/2bbc95566ea3dcc0c6af49c7c2d4b379af7516f29d6461ca86cfc9ef26412774.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJYwDE2Bm9N6N78kg1kAAAzZqLZlzk6xUHBOWD5FnL/FoqPTLslEFdQyePoNgjtZK1ztd74u+pIxAOovGFVrJyXH6Tfh8/Mr9eepwkOPwb/DsNTfOAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/37/f1/37f17b9284bf590dec731b2f00012806056ce2bc30e484392861d4793d2540af.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a8/20/a8204f5f83bdacadee3d8a191d8e23c991225f8a2e6a69de549463af1d621b52.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/7c/4b/7c4b42147599a6f6ae49b8b1de2835ca266d3d9466f2af49cba327b178e65db7.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/46/5f/465ff2ce303bc46a58f5e8598aa6eeb86d95f0f3c2aa707fa84dc28e702d8df6.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/4b/e0/4be041c163fba4da09b164586ccb20ed999651999bfeeab1f88a2798def7843e.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/02/a7/02a70dea429e929eefcab89030017ebca7298f859c8c87be605614748d907bdb.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/fa/bb/fabb5197cf7e0764a220c6d3f7e22d35aa75ff9ed84f393631f9525b6acb4c5c.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/be/21/be21982b6f17b552ce13719ded8e5ffbe5d4b3cfb493849365445cfaaef0e9ce.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/58/d7/58d7f82bdb2df634aa578810a03a356dc75af7816ff5085302b95be21905d963.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/03/f2/03f2faec70ceedc1b8fce3c00dd93acbd424ab2868954bd7496f60746b8bb0bf.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZQAAKHh9UGQAAPkjtvugxk/cu+qCmcwfo3ylvKW9Z76KQ83Kv+QaLABS1aSdQ9rQvF23UHaF3xXTHTHQcRRLmgEy10RxYH7n/gO6wu4kUAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/00/bc/00bc055738f8c367e9997d466dc7874215289a91cee77a1767fb1f15d6375047.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/cc/bd/ccbdba4472d9d2029c1a5056c36a1a8f603fa0b626f9273a3ea4553641b57f5b.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/7c/44/7c44ba5035054ddd42642cf065650352d3ea81a69e11613fc76c55da7cc8ff2f.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e6/02/e60246c533b6b78b5794ea980605ae6b548c5a953df9f141e422ab8b30df8c51.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/fa/ea/faea66c3ed1bf0754065d3a04689e9b792ee2a7caa4c35bd3d9c0901aaf7e72e.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/d3/53/d3531c01237674e62543bf8bf14eb1ab3c7c165453dcd8d0a3cf8931449f9c9f.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/68/29/68292668d6e47b0a71c40e758fcabeed81c719460fa7785f2f0311bd6734f6fe.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/10/72/10721aeeae7e7d84e1a1133da7feca6e2b342c56d1b41215fe4628c4b2a3f841.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/3e/64/3e64d599b7b7d4b3f41af9cc082b55468da0da6bb2700ab27cbd9c3170f83355.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/89/24/89249688fc72ecc2cbd8c6e3d768dc23a9fdd1cd714e927d9f1e7e0d863b5c99.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAABQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJQBibMYYG5gli4ADc2blzCi/i1BQQI7TypRYV31vYZwEfzuD1SWE7sA+0N1sYM/5d8WwJUdT1oTYtOZU/3uCzmUp3WexoRpl0yy3ZLXIVlyyAAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/2d/81/2d81e3e70582afe5e007808e7d05eace9ff7e082167e031d98b8712bda432850.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a5/2b/a52b322da827f17f5369bca044714df9e9fba54774f3cf5ba2bea64e4669d25c.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/3b/51/3b51921dc0b571cb5dd71fd573348713d6bda22ee097217f43ef82aea1789880.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/c3/fd/c3fd1d78b3c475c3c1d9d1f2b08117f6471e0ea7c8e9b8bd985505f663d149b4.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/73/44/73442181d48ea8aa4a60c7e6e7456cf2f9107b8bbbc34c65d8b7dcae698d3952.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/e4/92/e492c8deafbad13a2ea015bf2f916309d30843fb57f6328c42508c387cbf70df.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/25/51/2551c9a77f4f9ff6109168dd94d2a74a80a3592b45e3a9bb74a0e1784dc60072.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/18/4d/184da41768d25270914b70b9d929362728154e2a0ad8da07bb40771c86678459.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/8e/3e/8e3e7f7af9edfa082dd6647b66a4412561e6f8d3d9484404b506adbc4c6122af.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/74/b0/74b0914ea239e776ea2ddb39fc38b1b28eafa43b2ce03fa321cba3d284c68cee.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAADwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZQAARd0FfZuxS1BFAWOAAPkaCMO0AmMeOLlH0Ww51t3eX/XfumFdTGvS16A86jclWmmuDQa6bf3aw424k//Aqd2oS/QkkKKsDd/Y7h+RSskApnjwAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/b4/cb/b4cb378f74f4ae53187f766a9f6c1d08ef7dc528e2deca3f0fcfd597c3d26e5e.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/e1/c1/e1c163758bcd9f71e2774a01a8be3cd687d570a3d8979061671fc4cbfaa79056.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/91/6d/916d5fd9b914f83b825f01bf0591e61694358c3f6eef94f4124542633071740a.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/1e/3d/1e3da57c65f03f61a31b389222eb3df182b2cdbae9ac0bcb0c7ad88faa58862d.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/f8/50/f850cbfa4435ebfc812a196b7ed08c173c055ccb18cedb7bbeb21d15fd121a1c.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/25/9c/259c294321d3aefb70bb05b28c3e65dec3874c291901cfc2c5f791429868332b.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/7f/d9/7fd9df92cdd347996bf1a9a73d14f2e8cac8308a410d08352e9f4af3e95eb30f.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/8b/96/8b96a6888b93f8e44b2dd19824f44567c4efca59a598fe344541f29c15f0d54d.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/1d/62/1d62963cfab34962883f2553d91f72b17394c66132297ddb95351af352d0fb33.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/a8/f9/a8f90b64a2025f0794430ccd13ba063739256546274b9d400e03744ea5ecdf40.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoUAA0APzmGuVOvKSWisAgB4CcJagBU4AXB2ycGnPI9b8BQAADxFssm+HhHJ7HM9Lb2/4vUBIbaX1xXK3wZIuw+4OTxmVbycl0JKOQ0CvbvxkvBVRzWgZQlMnDOUBMGrtWKrJ4KoJztAhXoOUfaaAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/f4/2e/f42e3e71b51aa8b838156afc99a223fda4f26435cfad7b3d723afa820b09b32a.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/d5/16/d516cf3fee25064f6a1d805702ead576a45a3db6c6baa61e820de68481c0b568.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/93/8c/938c896988191bb8afe6968016f7439608c7e03b8f3b28a384b491bc6488d264.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/db/25/db25221878708ae35e6f60c4357d46de47b619530dda5f3944b77eeea1f49db4.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/26/ef/26ef2804bf315f6e4b9a67b98cc03be491a011b8b9ee554f1ac8cb48e811620e.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/05/d1/05d1d59aa218ad25b79d29d91e2fa79446b178b0eed136c4525487d5d4eacac5.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/5f/cc/5fcc88dac6d669ba743ca9a25d58091c5e4633e9e91939046f1bbb384c7a9a6b.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/97/27/9727d9f8a598fd1e0cf227078fe3a66052419fe01099126dae2881d45237c2a9.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/be/b4/beb4a3e7d54f2accdf802d4737d7c962725b45ee110144bc5773cd984c6e5c54.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/99/a1/99a19b333fc53568565cd0704109a42ab98153c7c96998e7a68b09ed16b3ddf1.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZQDImCIdrLzxU6BGhv4YAMtBZNcegufjMbBsho+unrBfNiwGhb2C2sNO8gNWGlpZSeO2iG3p45lqgpG9LB5zVPtAZIkJ4AA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/6f/58/6f58755c83f18074c448c00dc37fba4323afdb61370f5b20cb45e92b8ef68f93.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ee/93/ee93fe454e1f139cc65b4c7bd465e00c52445abce807338a8628233bd5cc96c5.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/29/b3/29b3d4fe5e02e2c7e52cf9be8ffd47fb797f06f01d5b12ee6da0c57e601a3b65.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/78/56/7856cf9f5cb5e087ed1ded544a73d47a144805643997ab10c2592543591d4bda.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/57/15/5715ff46d27006051f6e1599bbc49e01c58e80041ec69993dbf5a5e76b71dd59.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/0e/3a/0e3a89fa7f0ce2f48bf558742d93e5e4a7b084edba455e922a7db5fc3a4567f6.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ab/9d/ab9d404b08409b0adb140837c71530c180038700d2709d22f42b0e2d80e46740.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/34/10/3410cccae124757ff544dbd5d5507bad54635763216ce2897e136b9f10203133.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/1c/6c/1c6c927e5dc85966c21c3d815a2d9647e494a5f712e7a5be95f901e42aef6a57.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/62/32/6232d0485276424ced8bed015dbaccbf08f6a645cde49716f28a81237034a60a.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAAAwBACdASoUAA0APzmEuVOvKKWisAgB4CcJagDCgBnfoJIwrWre0qHiI9AA+g46Ag6HtNLvDBOGjRQJYXXO778LX64Zb2UluzYqMnV2sBlMdGuKF1r/jtPAfn2vbjtkPHsCqFa4WULLDtLTULFq21cAAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/4e/49/4e491523d9c99e1b619999ba2ce1863c045b294bd7cb630a56b2c6cc3a4fd133.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/02/45/02452397946bd00e2e75431513da19156eabf7a2051185d4783634b4cfa7c764.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/76/f6/76f657ab66da101502d29241555aad8f387b3a05c1911239abc060801f959209.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/02/bb/02bb7b623c6eb0a93fd2cc2056f25c1078190149a0b4c993234ccf9b5e33ac4c.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/90/37/9037a9fb758c086ab236856018e85c0cd3a35d441edc63453b5c5735c4cde795.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/7f/8d/7f8d25ddb674e8d7f6af639b2688b470ff27898423bdfed344f14281c14482d3.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/80/03/80039d85fa6243929ec19c887a1a937c223fbce546bffba8926522c69796196a.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/0c/44/0c444c2be4971eefd5113c9d14982797e917541835974a880fbe0427f5a0a89c.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/34/7f/347f6ec5e3dbeab0f5934814cb4fc69bb153511ae60fc6c63ed741315419bafc.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/95/16/9516526ed2f287e6babe71b0dde8698b5ee3e13ac808b12083a8e5721aa7e37c.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJQBhQAvMIusvecgHR/bgAzh3P9XKGmTMcQGTNX6nKN6vLTYZx6frkfDSsc+eUql1H0YeRuVW1+KP4Jcenii1WIMAAZX3Adm+a4YT1j1FtwrSGh49UUhyPHR8xjyAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/b5/18/b51876cc6a232e1d942d2bf2ff0a3912f163cd5c1c48ce3933b0cdb91bcae62f.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/59/b3/59b3e08f8224c622b7abf9eb49cca8430ee6c7bb73aeda3fbb27e2d3aee40c5f.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/7a/85/7a85434755949d8583f80d7b11aa0b547f133861f70c8eb4e91e54ff81862d5e.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/27/42/27424ce2112a63452225fe524134dcb5aa5a33ce4fe8959e9c9d3fbb3a9ec161.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/4f/64/4f64641741184d2eb061b81631e7051f3bda5be1ff71e267103ec5dc36d15894.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/5c/70/5c703ff3c19cedbbf66da345fe015c46bb5bb511ba871da4d38b6e3a416ac197.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/17/2d/172d79b6bfe1e40e54a341ec61c30ae06df3f47805de4bbcb24eb4e54f2a555f.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/fc/e1/fce1b01c9c2fcc6a9dc6f64701cea59becf937cf9d6525bff3d7ce7e2323f436.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/7b/a8/7ba8cc99f858182b976524a9632a2e834f90a35c36230ea770fa06dc97ccd45f.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/44/06/4406096f3e02b013ed66eb7b62f9a31b91301fcf20d367173623b2a58b09e25f.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting 2019 — BUET Robotics Society archive",
        "width": 1365,
        "height": 2048,
        "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBQCdASoUAB4APzmGvlavKCYjsBgIAeAnCWcA0Bgy1uf+IOOtc3v5QeCs7G/n5O5fpchwAP6MLKrfAdFdNzej/VLrI86hw41tOvNmYYa6tnuUNhnNPkZ/NGTb0fpAzJhy5SM46ZtrCCB2LTMQddrbMVAvg/1QAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/b8/5a/b85a6561120f1233a76f8ac13425b2ee1c9c434e677f7a98c9699f48078f0398.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/4a/3f/4a3fd68bee46a3bd24dcbcaff9fef3462bd9049233f259cf4f8bc18626ce7ca4.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/70/70/70707acb55eb74b11e93e833442bb413436fb12d6767d95b26ef344e88c0f29f.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/83/54/83549f6b8813552e32aa9d4285cd3f15f93b200938de3670bf28430c63ba302c.avif"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/ac/c0/acc09c6b8629a6e51041910c60b98cc7382614650ae9c8b41a819d324b40c8f1.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/38/8e/388e937894101106c12aa50fe1e556646cccb3a9f633c4483978917edea6785c.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/f0/ac/f0acd057c6ce977c0878db92b2ba36130813cd627aec9ef386a3a1cfecb548f5.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/59/b4/59b401dea01b77b44d4793e014324571f9c12f443439f86e7b96cee3094c7b60.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/50/72/50728c07d646bd6be4891e18489f2bc92b979411bd6c2930a27966c86711205e.webp"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/2f/5e/2f5e1ee82fb62cb1c193e403c1a70b75a9fc3c1645ad5c07df1a2ad22855793d.webp"
          }
        ]
      }
    ]
  };
