/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/agm-2018
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "agm-2018",
    "title": "BUET Robotics Society Annual General Meeting",
    "category": "agm",
    "edition": "2018",
    "year": "2018",
    "categoryName": "AGM",
    "copySource": "web-ready",
    "html": "<p>The Annual General Meeting (AGM) of BUET Robotics Society (BRS) was successfully held, covering important announcements and guidelines for the club’s upcoming initiatives.</p>\n<p>The event marked the farewell of the batch of ‘13, whose dedication and contributions enriched the club over the years. While their departure was a great loss, it also paved the way for future batches to carry forward the legacy of BRS.</p>\n<p>The meeting also welcomed the newest members from the batch of ‘17, offering them the opportunity to officially join the club. To celebrate their initiation, special gifts and refreshments were provided.</p>\n<p>Additionally, the problem statements for the upcoming Robo-Carnival were announced, giving potential participants an early insight into the competition’s challenges. The event also witnessed the introduction of the new executive committee and the launch of the official BRS website, featuring blogs, monthly reports, and robotics-related updates.</p>\n<p>The AGM served as a key event in strengthening the community of robotics enthusiasts at BUET, setting the stage for future innovations and collaborations.</p>",
    "plain": "The Annual General Meeting (AGM) of BUET Robotics Society (BRS) was successfully held, covering important announcements and guidelines for the club’s upcoming initiatives. The event marked the farewell of the batch of ‘13, whose dedication and contributions enriched the club over the years. While their departure was a great loss, it also paved the way for future batches to carry forward the legacy of BRS. The meeting also welcomed the newest members from the batch of ‘17, offering them the opportunity to officially join the club. To celebrate their initiation, special gifts and refreshments were provided. Additionally, the problem statements for the upcoming Robo-Carnival were announced, giving potential participants an early insight into the competition’s challenges. The event also witnessed the introduction of the new executive committee and the launch of the official BRS website, featuring blogs, monthly reports, and robotics-related updates. The AGM served as a key event in strengthening the community of robotics enthusiasts at BUET, setting the stage for future innovations and collaborations.",
    "cover": {
      "alt": "BUET Robotics Society Annual General Meeting — BUET Robotics Society archive",
      "width": 1960,
      "height": 1080,
      "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAABQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJaACw7CzbmaYkAAD+3lPe0qeb2ngrJsnel+BObLTczaEUb/zXPJb9ANNH8TUp/VsOUVUjAAA=",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/6f/05/6f0506d62ceda7052c27d28a8dc5120b7eeb9fadd86a3c587e3ae9e19f8f0d13.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/18/8a/188a1bfa113316cb9d87bf984ab283af88574dc8da7cb1181155187e52e59040.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/36/b0/36b0c55714985df06c9f6844f25ae430b24e8d435fea1b7b5a5f736c21bb78d6.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/62/3d/623db64956525b916e5bc017833057310a63ee4d1655192d81a1f266c788821c.avif"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/5a/c1/5ac162febba8cbe32f65283d78f2c3d321b59b878fac58f0b0287a40ae35377b.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/ab/f8/abf829e99dd7c7afe0b62ae30902ec9ad9b6f0ff83d914cfb4aa8726f7fe4ac3.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/de/39/de3965c900a56920414b64aa53adc1553a0e428ac7882e6f645b88426aca5217.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/88/25/88254b87e40e25e5df02a4087e4b7c182bbc13707661cbca0b73e14364494ff6.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/7c/b1/7cb1d54a8c71f73393c7cbf9a073f2997d1d4e0757e3e5dcc53a8e7c03057912.webp"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/e6/63/e663d99da603071f13feb0e4fb6b2e8465e93996d75a4b251db737b9c0671c42.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "BUET Robotics Society Annual General Meeting — BUET Robotics Society archive",
        "width": 4608,
        "height": 3072,
        "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAABQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZwAAXGufRRowwAD+rrOOE2ebXS0WXo76VU1NS3iMb1y+r2WOaZvNAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/3f/e9/3fe9b845e15f5703c089f2ebacd327feb9e45bb9e7c40d9d6f5d143f1355110c.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c7/09/c7099fa9eb4901cefafed8a125fe11a424245ffd9e845b5ad6271c6467ae5ffd.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/48/d7/48d7faf9ba0cd0ea7ae71adf983995b9415fdf1574fd6ea31339d4569e6a285d.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/b2/f8/b2f8221b1c4c88cf6f4ecb0da112aae12e1544c29c7e8dee0a036f75bac51bcc.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/2a/78/2a7899e39f2edc40962b11dd44b992be21e8733abd62c3406e23ee14803f07fc.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/c1/64/c16428f08bdc62e0748642ac67293389f47f70ef676c7dbc75d6d331d9eb031a.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/cb/69/cb69f22570807d5608d6d223403030a7f4021455321b4801c66a3e6da3427f95.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/35/38/353840ad802db31bebdc8f5ad2a7f0a570424b30590893ca1951834126eee132.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/08/b0/08b0c28dfce0ab031cf78ec5349a8accd3c079e565f0e21330b90d2c73fd8bde.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/d3/11/d311367e3455cd295f9c8609df8c850ba1ee3f5fe1b7e5a31d9daff88ead4956.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting — BUET Robotics Society archive",
        "width": 4608,
        "height": 3072,
        "lqip": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAwCdASoUAA0APzmGvFQvKSYjMAgB4CcJZQAAWzexOIjRUImEAAD9zoGdHpyXQYFQcBwd43FE3pV6hIsrrMIcoAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/53/1b/531b43bf95912f3052f87de66ff5121fa266cdff4d9e7e1398ee6c30cd7db578.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/63/eb/63eb166efc6cbdee2c22dd85638f204030275eba11ccb9b72998b6563343201e.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/af/8e/af8e2526938e8b8925507b231f089ff9631b59718c52bdc0df0785b34e787b98.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/00/41/0041e66ecba5bc52b9d22c05d7d359d4186c42eef696c20fdc72bab47a630d14.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/e5/ba/e5bad100882eb9769af4e31736a193d085b198faec7d28ea26d6fb2a1bca8d1a.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/ab/7f/ab7f98d855443f8200011fbfdb7f1d219f1315d14c4a7aab2b50e9dfe19f67d6.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/42/a3/42a3b360b25102e5e5f41470d9ab268c99d81bd7281762cff834425e98edbfaf.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/97/f3/97f31b1444d965188b28b4848419af6818f80dd86e62b3aa1c4538edf9d9bd83.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/74/1b/741ba3da518535073aa5e269bc88b6dd8cdfc2ac0894b27994afec3d593ecc12.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/d8/b2/d8b22bf397aaf3723fb6f1e50743916ae58f3a7a4cdaa1f60973e086cb32f560.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting — BUET Robotics Society archive",
        "width": 4608,
        "height": 3072,
        "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZQAAXuf/oYfFnVEpOfAA+Rwd1jK0Ptdu1tapay4soQX2Uy/PO0EUud7LEcAAqlC08v8iQ4s7OOPttmkkpirXeIAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/e5/9e/e59e88d1d9f69ff384cb106d03df39758ded81cc8395c288168ede2fc904933e.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a6/da/a6da93a8cbddf1061000dc6537e639f3a2d1db35297701eeb5bb3a20b845a815.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/2b/e1/2be1cdc333abb0615419fe49e75a357f1e190b6e2a4cf9d96d50dc14cf47660f.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/af/16/af168e9f960dde1f2307071e4cd40a48fcb3995af98d2d122e4e12cb2bae43a5.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/cc/5c/cc5c74055de47ea2cc7c6d525fb1b84f50a8a292869a2a9bdfb60a7c25dc9128.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/1a/02/1a0211661d5f289c258705368783e90e9dfd9ab52b21983212fd91683a51da76.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c7/44/c744bc17873710f4aa613f204a551c5cfdddc084e520fbf7cd0743d469dd912d.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/ae/a8/aea8f0f2f8d7573b3673d245ddc3d76e56b7b83c0ec207bc0ae4b5182ca02e62.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ab/f9/abf93dd390ac60564ef1c09a88fd35146e5d0283321880ffd08828e95aa3b423.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/8f/d3/8fd323e295f8b351d6928fac6ec315e8de54da17f931b03bca5726861cf09892.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting — BUET Robotics Society archive",
        "width": 4608,
        "height": 3072,
        "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQBACdASoUAA0APzmGulOvKKWisAgB4CcJZQAAXrh0wUjrQtS++kMvAAD5HNpjDY+C64qF0MWF3DMhSvnvKLYT5c/6IajpZzcVSPWdQAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/70/a9/70a9dc54a87e8d5743d30420e2e425636a271ed9d97b9378ab9c115ce14b6758.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ec/71/ec71ff6bd083b730a14e314e917487f4c464c6e0177e7f7eb93f6547874fb88a.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/51/f8/51f8a5a1e6190831b2c346646d17c35e5f1ce3657c9159e7f27316c6db1ca3db.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/7e/4d/7e4df6377d0347697fa2e3d2f8e59609ccc9d9ce0912b4e18757f84309b53641.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/a0/0f/a00ff36fc83d28629173e70dda027c5674904bb4f1e9638af247c81d2a385e49.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/74/89/74891b3ce7536dc6e87f5d2d032956d5f9f7ae9e9e6cc1b6de6ed9d69f23e691.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/f7/43/f743cd13946513b008a99e1869e51cf5893065b618134df24078a7f699497402.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/67/0a/670a1cf3551a31ab3dc8275189020dae2bf3d686b616354ef954c43200a342c8.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/3a/23/3a23b16c1f9eb9b84f685779769e8014dc1a951db4237087ec6e92e1c6829d62.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/d5/29/d52989246602a13fd8023112829a0cf7f94736b383891790ecbc98974f53d248.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting — BUET Robotics Society archive",
        "width": 4608,
        "height": 3072,
        "lqip": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZwAAUWV5v43zJHhrsAAA/IwnDlFEaKZ1txazF3KqleP3a48nOdVxOG7syRq0nGzr63EVRNWX+NebuqIoAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/67/e6/67e6bba2b861b4a7b148ebc0c447a760e1ccf91e2d958467ddf0f0cdb4b67d59.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/5f/ef/5fef400994ba85a90548b0a5426db319699a9c2badd5ffb59d8937636b445c17.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/d6/e2/d6e292a7efa56a80818f775638d7c03bd969a37eeb286a0b3a63888b4b41ccbd.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/33/bb/33bb6d4418ea2c9b91f0b13b3f8351656d1044243d5bb1c46c1c4e48b42b6b16.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/97/f6/97f6027cc90e1022a95c0b6056358ef3612ff270f7be8032ee3511fddc3548f4.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/5d/a7/5da771d3e8bfbf509de2a0a64d50234b1a90eb52f45ca5a4bc2ed189b6aa5989.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/d8/97/d897f8fcef747c49e30fd3afc5c89bec4e37047de19f9c3a72de8a0f7f898d8b.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/4f/32/4f3212dc5a0e03bf34c3a2a0e64994667f70a1ddea654d7b9b4a44b485175343.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/bb/1c/bb1c0aa246f1e240a372ce4295cde2c11de8597d41fd9ada8ca1eba702d5e33e.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/35/66/3566ac105659fc1f1518c5a7b5b6a9ce243a2addc7eb80768f9187b7de1268ae.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting — BUET Robotics Society archive",
        "width": 4608,
        "height": 3072,
        "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJaQAAOTcLL1f+1VgA/qgqAfra1rleR44LmgTRNpOgiTysL2qWOU+r6UH4UfNnvL10oGjzEvAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/16/f6/16f6b29a71cc41d09430ae922d1f3046eb839d5b96341fdb7f8d69754c2bd6ad.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/94/46/9446e23ae328ddc5d808092a6f632dc7a8a16fe07c220440a57f817fe3f8ff45.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/18/38/183866c872e6d4f91531dfc10672800ec20d6005141ce38c809922f220b16e29.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ff/d8/ffd8846c802ba2bcc059a8181d5078446b8d1e4b7b4928138ccaeed169d4569f.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/dd/ac/ddac99e880c39fad9b0ea849cea8f89b49e5e661137099b739402d48a93c1fb8.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/d7/ab/d7ab8f49f16a2a10333c9a98d13bb997b29b8a9d1cbfcd370aece0aa2e4fec27.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/07/83/0783729f005718f22327162ade6cd3115d377d32fa5f18ce2440ff9c31f8b5e3.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/b5/3e/b53eecde54d2403383bf0b248b0476e7dcc19a7ba562017bd6b9122c6104223d.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/00/a7/00a7ac912a9af61331aeb02b84778d3ad228bd33c46af9a99a60972f73c910e9.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/84/4b/844b5a5c1afa22e8acea55cf874fd7ef28a20c32dd2f3624911544b17e2cff94.webp"
          }
        ]
      },
      {
        "alt": "BUET Robotics Society Annual General Meeting — BUET Robotics Society archive",
        "width": 4608,
        "height": 3072,
        "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJYgATwAF1Wbj3Y+AnIoAA3gRBJuLojgrFwanzzF77rdEerOz3lVFsESkqfiOPGOimrVm6UYaO8QPdHKQnJyTaym3ThneUVD1yKfxr3Wrmfhw774TFJcemLVpDkBnBMAAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/d1/f5/d1f51dc0b3285f6a5abcc6db7a95b0db0aa4e9ab070f48789a75f2b73503bef2.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/78/52/785284223e6a3514f6a3f34fd78287f8d3a8fdc2538fe5eba415bace482036e2.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/72/d3/72d3e144e32eed3684dcdbd07bea3b7a188d32c8c7edc2b6d437199994ed7b5c.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/4f/b4/4fb47d0e15034e834de66f1692754323c7ea0a6c1fc2bd1d9e73930e471a5ea2.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/12/4a/124a9c1537292ee8f6376c827d46bd3c33ecec6fd4d2ef2d197f934e578bd19d.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/54/de/54de86f30e6dd9564b7a3f4422263f2e00d692002952e5364695cc6af3174719.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/69/65/69656c9dfc9e208b9eedac07e255281a3ffdbf240d41be9cc6d4ed5a98314147.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/16/49/1649df8f49f6df24eb569377b2b2e2905f4ea3df2e4fde75b0d4a46ee1f6039d.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/94/53/9453c2e79c633cf9bbb67e7428ecc7a6e941f1dfef6de1eb05d72d392788f1aa.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/37/b0/37b0d70a4cb3f715734631c4a118db3731caed6d1ec6361669010a0c9d05c8b5.webp"
          }
        ]
      }
    ]
  };
