/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/agm-2022
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "agm-2022",
    "title": "BUET Robotics Society Annual General Meeting",
    "category": "agm",
    "edition": "2022",
    "year": "2022",
    "categoryName": "AGM",
    "copySource": "web-ready",
    "html": "<p>The Annual General Meeting (AGM) of BUET Robotics Society (BRS) was successfully held, bringing together members to discuss important updates and future plans for the club.</p>\n<p>A key highlight of the event was the announcement of the latest Executive Committee, marking a new phase in the society’s leadership. The meeting also served as a farewell to the batch of ’16, whose contributions and dedication played a significant role in shaping the club’s success. While their departure was a great loss, it also created an opportunity for future batches to carry forward the legacy of BRS.</p>\n<p>Additionally, the event welcomed the newest members from batch ’19 and batch ’20, encouraging them to embark on their journey with the club. To celebrate their induction, special gifts and refreshments were provided, making the occasion even more memorable.</p>",
    "plain": "The Annual General Meeting (AGM) of BUET Robotics Society (BRS) was successfully held, bringing together members to discuss important updates and future plans for the club. A key highlight of the event was the announcement of the latest Executive Committee, marking a new phase in the society’s leadership. The meeting also served as a farewell to the batch of ’16, whose contributions and dedication played a significant role in shaping the club’s success. While their departure was a great loss, it also created an opportunity for future batches to carry forward the legacy of BRS. Additionally, the event welcomed the newest members from batch ’19 and batch ’20, encouraging them to embark on their journey with the club. To celebrate their induction, special gifts and refreshments were provided, making the occasion even more memorable.",
    "cover": {
      "alt": "BUET Robotics Society Annual General Meeting — BUET Robotics Society archive",
      "width": 960,
      "height": 480,
      "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACQAwCdASoUAAoAPzmGulQvKSWjMAgB4CcJZwDImB4TInrpsTIAAPt0uqolWHp0dm1VWZd3cxe3tIsHOJDcDo93Tj1AI9IgVA24AA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/6a/12/6a1209fc7a876f338f55a13023eef2164659a479d75249a55827d655c1e51a85.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/71/94/719484c9acf8df21b7dccbd3aa7479de4207b40e886fc41c5399ee7dcbfe57b4.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/e6/f9/e6f9b5e4c65ef2f2d2f4a3aca8ed668d730b9f496339748ba3944918fbd07891.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/6c/cc/6cccc7d8b3f21f61d9cebd1d9123466b5a88f675771520b9653f14b8344b2144.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/c0/6d/c06d070252a83b48f88709772fc9f939bff2ab0b3a16e4396856ae2b771e15c5.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/3e/57/3e5787353d9da7052f31883c8ad83737c81d8620f8e0d2dd9a6993e936a5f5b4.webp"
        }
      ]
    },
    "gallery": []
  };
