/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/agm-2024
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "agm-2024",
    "title": "Successful Completion of the Annual General Meeting & Executive Committee Farewell",
    "category": "agm",
    "edition": "2024",
    "year": "2026",
    "date": "2026-08-14",
    "endDate": "2026-08-28",
    "venue": "buet audi",
    "platform": "offline",
    "categoryName": "AGM",
    "copySource": "web-ready",
    "html": "<p>The Annual General Meeting (AGM) and the farewell program for the 8th Executive Committee of BUET Robotics Society (BRS) were successfully held. The event marked the end of one remarkable journey and the beginning of another.</p>",
    "plain": "The Annual General Meeting (AGM) and the farewell program for the 8th Executive Committee of BUET Robotics Society (BRS) were successfully held. The event marked the end of one remarkable journey and the beginning of another.",
    "cover": {
      "alt": "Successful Completion of the Annual General Meeting & Executive Committee Farewell — BUET Robotics Society archive",
      "width": 2048,
      "height": 1536,
      "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoUAA8APzmEuVOvKKWisAgB4CcJQBOgA3OViq5AvT9CYADhxJSCgB5DpC3U9fk9kgWBlcYrsX+lQZs39q2tXtM5lI+uz6SacOCAe4GKiSasRPVgefKn2nC11yKbRLrfgLCBpjrXwQAAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/d2/c5/d2c58e9b7c62b7889d9c5fe5157ba0feb161e72f2bb5501831ed05da9ec3f8b9.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/09/4f/094fc730ed5475c51d15ebfd5a2b5d4c1f539a92dfee58e09ab1b3d1ed27a401.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/2b/99/2b99c919a44e250962bbd7c80c8f6bdfbf7a3e58b5738fc5fd060f45d00d03a2.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/96/6f/966f04f61e3bc73b7563569b1715159895a5c4a61ae2c9dc0d58257bb6ed01ab.avif"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/2f/ad/2fade5c61f2b66c9550668b2713f4cecf329c0195dd626a454e3912b075ee9af.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/aa/bb/aabb8542c612c37d0f8638c624b86e1b92a5302ae5bad6ff2cad2ba01d220dd3.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/f9/5f/f95f26976c7bf003669a0d99ee460d880b6df80a5bd824cbc8e21a21a1c37f24.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/cd/a7/cda7319413d6dd39d1025ce38285f2c8749d11db3c075df0f08f71bb173e28bf.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/88/15/88157d91961026dfe93673ea86545945fb2dfaa9c5a0ff8ad68590e1d758c48f.webp"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/30/59/3059622a8f5fbcee167b4f57642cb6112054a275485f4422996358299200c29b.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "Successful Completion of the Annual General Meeting & Executive Committee Farewell — BUET Robotics Society archive",
        "width": 2048,
        "height": 1536,
        "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoUAA8APzmGulQvKSWjMAgB4CcJZQBTAASIppq6kEKQkQAAywDtzMAZXlsAcEWLoNW22iwq2rggNU98IrRq1eoRbsqfWVDxwdw5A2HYxG+TvQgAp9Pu1KAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/25/55/2555ef133fb0b867c781c3126ce3183eee77c62d9bab291abebc4c7562dde61b.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/0b/db/0bdb37bdfb260e1229164566859cea0e8c663c691bea042bceadaec6deb7598d.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/81/83/8183a6c56bf991dcdb6c94df303c3f4df3282496321cf561cca8dc99871779d3.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/f9/23/f923099d756d8e82f2495b61150d9ad2f5f1a8c787e5040aaec3ec3e4d6f53a7.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/e2/19/e219bd77f9acc390141fd9b8a84f28627aff1385c5f9d16f6b8dc684c52f0fc8.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/3c/98/3c98402d07bfd0e34570bb7c917322b7614bc78cb437ad199c03c327b6267109.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/e8/b7/e8b77c9efe5545186880b9ba5ff9d88957b8d1ab660760470497c212e794d160.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/9c/b0/9cb0bda5d9a8710ea9dce9ec7e8c552a8af7c886ffc2cdad3f1fee9666771f95.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/b3/21/b321475106db5dee52d828d01082f3114f8bc8c282b5e4d6d56b7f7ade1e8fbd.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/be/bd/bebd32835877d1d78e55beadb7a8faa01b0f2bb2f14701303e9c80b2b35ea84b.webp"
          }
        ]
      },
      {
        "alt": "Successful Completion of the Annual General Meeting & Executive Committee Farewell — BUET Robotics Society archive",
        "width": 2048,
        "height": 1536,
        "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAQBACdASoUAA8APzmGuVOvKSWisAgB4CcJQBOiP/wHdTXuPKIg/OVQAAD4zVjaYqiZjggHVkvUsXsFE2rn5LujRSl+bbZP555U7/Bl4A7kQYuQsufQnVNjuy5NG0piUuwed1r3kzgAjEv+ltXAdbFjH3dzy/oEDC+qDFfZAXgAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/25/b5/25b57d07263d3b7249ce2c649d6d9aa73d97232c4394285e83e0554efb056e72.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/41/08/410891d1def04f60866e1a3c94564d71818ebfc2bf01faa6cd01cc7549fc710e.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/4b/4e/4b4ee0454bd44b57c6c7442f88fd93ec6f81c469751fc2c854cb55d30ea1d2d7.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/aa/10/aa10da3181d189f562c0653572f4620f5b9dd9df94cebd11f204a6c20fa6eb2f.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/2e/2d/2e2d2e6b5feebff5fa9fd8788fbedabca32ce00a97f3c7b77640741fb2adb314.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/76/da/76daa07c01473375d0ebef880865c86c3753e102e6500d69f2fb737c2bf1ae9c.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/f9/7f/f97fccce9ce23a678e0fa123ce2257aec14f597a5fdcc80f50f253f580ca0605.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/1e/3f/1e3fca8e84977c4a3c3433081c733ca591d9ceaef18f00ecf0644d0922973c64.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/57/c2/57c2da7dfba81ab596688d1bfd01e63a8f99eedc6c03a25cbd85411a2fb05c13.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/1b/6f/1b6fbc19dfe6937f2946f457e924b480ccc5ed720e9310cff89e6d8f66cb39ca.webp"
          }
        ]
      },
      {
        "alt": "Successful Completion of the Annual General Meeting & Executive Committee Farewell — BUET Robotics Society archive",
        "width": 2048,
        "height": 1536,
        "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwAwCdASoUAA8APzmEuVOvKKWisAgB4CcJQBOgA2aHWURmjYIagADdsp72f9Woj7ISOBFFFikIeRgUPcQ4B035Pa5vEFH/TUdWOuHEc09aDhbqs48E+SRApy4PQhFQ7tsu+jzuZ3P0e2HPOuYAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/97/ab/97abf845b4b8a18573e0f05f1ccde87bd7534143f4a20767e7ae44d19a86e864.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/cb/c7/cbc7329d5acade479fa8826b9d74788394a816ed88eb10ed9a739bf9a45b9bb9.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/f8/f1/f8f1f27098f5969ead3774878c467d853280657189cde7cd99e950462a802d0a.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/d8/1a/d81ac0cf3ef48e3377c0704486c2223de2db47e0afc2e52a764836831b8d3dc0.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/66/68/6668d9259a9a68269128c68c1de9f8eb269b6db35c119f7590764ac38f6303a7.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/c5/10/c51099a7aadf6d747a0e3f29ca3341501e4dc9e0d7a4ef99b2e97093d0a1d4d2.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/80/e2/80e26b7106a194e909956691c3c79dcca4afc836f7b5cdb9764acbce29badc7a.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/3f/1c/3f1c24013688e74b872d550e02520c3ab64a29e22ed9a7f817fcd0808175bf17.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/46/f0/46f094679ae8d2cfeb116afe353288bd8d91988204251eacd4e89db461bb9b79.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/ab/c9/abc9faa9f68010871eb7bec147b688a362adbf7f389f63ba760bbb94e20cad2e.webp"
          }
        ]
      },
      {
        "alt": "Successful Completion of the Annual General Meeting & Executive Committee Farewell — BUET Robotics Society archive",
        "width": 2048,
        "height": 1536,
        "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoUAA8APzmEuVOvKKWisAgB4CcJZQC7AB8/Z3kBrUAMpzC+QADBis5183d4qFKSqUz4U4avES9kt3zAgCcSJh6yrB4ZhahuEDDwi1GbZnLgLbqVLsDDgh471NLH5CZKRxSw7WlURhoPkSF6tVHUAAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/42/49/42495bb0a3b14e818901d040c64e7a9c651438065910f3c5081cab7e808aed05.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/0a/13/0a133997d4bd9827e4ead2dd963d6b6fba8bd25f885468df6626953740dfa60f.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/86/41/8641c68c6ffcbeb7a583a25f8a93fca8f570e8c0522c47da79164a280271743d.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/58/0b/580bc645628136dc10dc4d69f5a0060a60788e102cc78470932398be86dbbc7b.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/9c/07/9c074fc5ff6b91a10b3aebdf65553a923f2b097e68930bec69ef16b59ca5188c.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/ef/f7/eff742bc98286b4110ed544dba417cce65690aa535470f5b5be6d3eea58addcb.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/f1/ae/f1ae4c480d5fab70d7f88e67898c94af416b916a92da1f2f310d52d07308130f.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/a2/3e/a23ed46b593f9bc6e207776c5c0b24faf6c6ad24e7296d604423db7f47a4762d.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/22/22/222201f6d951265d358324827779650729d1ac8a95ad115b85e96a36abcdf95b.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/27/dc/27dcc500dc1482daaf6acbf03ee156b955d8a1a0feea38343f761057ca48071d.webp"
          }
        ]
      },
      {
        "alt": "Successful Completion of the Annual General Meeting & Executive Committee Farewell — BUET Robotics Society archive",
        "width": 600,
        "height": 450,
        "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQAwCdASoUAA8APzmEuVOvKKWisAgB4CcJYwDKAB1PVD0mAAD4wWFsq9C9T581ybw7T1QEBs4YLrLB0aDXGGQv0pyRl+JD2A+LtVlZh9hJtRh/YC8nGlL5C5hqav4Lvr8Hmw1iY9RLLMpUmPEZPwoaAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/23/30/23301720fa88bad288625395f7d38efc8173ee2b513917390fa499ff975666d8.avif"
          },
          {
            "w": 600,
            "url": "http://localhost:9000/brs-assets/sha256/b6/7e/b67ead1e2c8d08c4583ffd64052853e9cf0931f329537cf2af14adce6eba752e.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/39/7f/397f76465180f642adbe01042a64f56ab439cb86fe74892e176c0e66c86fd544.webp"
          },
          {
            "w": 600,
            "url": "http://localhost:9000/brs-assets/sha256/e6/fd/e6fd1aecb6e934df49b0bca38eb330810aa3a1bd5967f6e7312e18e468ba0509.webp"
          }
        ]
      },
      {
        "alt": "Successful Completion of the Annual General Meeting & Executive Committee Farewell — BUET Robotics Society archive",
        "width": 2048,
        "height": 1536,
        "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwAwCdASoUAA8APzmEuVOvKKWisAgB4CcJZQDG9Bu0xEYjyVZMAAD9z2FqPt4ILqQWHnGoEqLcFzpcrLCAN3R4rhHQWzrV/W9td99/07grz0wLHRWtFgP8TE14VWT9ZTicPn1Gl6U1NSokAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/54/b4/54b400eaf2f0b677f9418095f08be8099ff3a0ea5a2d1022f2c9095fcaef284f.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ab/ad/abaddf80294790986e94646e23f6d85bcd5370a81573cfba001b672c5ea50fea.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/5c/2a/5c2a6be3150acf6fd1f12489b21024e936f713bd36ec1ed0fc98b767abd1cf98.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/b2/45/b245ed462daf67f30590c3d0af4b6c108cd58bd880166750b9003cb64223145a.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/e5/03/e503a4b264f72ce404038fc717ac25b94307177bcc84cdc74c97344e7f47e1d2.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/78/64/7864093054f87d93e8b70cab8adf5516e7175f7425f6ed9dc7072911c91042dd.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/3c/64/3c640b3ca7ca88ec566ff368d1d56379e4e70e032e1470c426be87e9f06a9c0a.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/3a/a1/3aa1d35b384bcb7446df1a26a3d1bd7cb62fee9e35f10b2309c0a80a82ba32ab.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ff/b7/ffb76e43868d82a5ad7cfbb405a83be810626512fb26df3eb774938284a562c9.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/75/ef/75ef6dffab8d498a42013ad9f7dcd159decbb33c2e46e60995a879295a5b70e4.webp"
          }
        ]
      },
      {
        "alt": "Successful Completion of the Annual General Meeting & Executive Committee Farewell — BUET Robotics Society archive",
        "width": 2048,
        "height": 1536,
        "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADwAwCdASoUAA8APzmEuVOvKKWisAgB4CcJQBOgBC2BojxY+Nb0OYLIAPjUKesJuOxgcZCGi5q67nAy1pi1paJpI9fDKhcFaU0HxYnEpfvr+S9y6rvUlfssHUVRd6W+/x9BUXtT9S3BRPJhmrWHPPQCZnvQAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/32/62/32623936a149cc806b35f2639ec27bd2b8e76175b0f809f51ed9dac43d959d27.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a4/d3/a4d39a717c9be5a3285ebdd35832d096b739d4728ff4cae73c626f15ccedb504.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/d8/07/d807899cc5c36855c0dd6d79c38893f7f313737cf4235e6a9628f986ee92ef34.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/f8/5c/f85c757314cf2607c8830ac09cafa7154b27e2992fa686f9aa240ae5b92c599f.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/41/3d/413d887efdf215df015c878b0c77a77fe4413873868daf5f07bfd208d86e05ed.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/4a/a4/4aa481e341bbcaebcd5b9ad013c1ebc728035f2e05bd6214e458807cc930a5f2.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/10/31/10315c92eac4a5814a5a20357c7effccfcbe88bb0ab51f3799f401c5192c92ad.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/a4/14/a414aa356c376887f164cce4b4c08d23e5bb6132abd4758196789a425bf8db9e.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/38/a2/38a298954cf049814dc591eb4ab8c708119e219a5d570b8bdaa71eeacd71b179.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/15/9f/159fd4ecc6d7c1e3205556e1578aec73a60d3977de4fccd1fec968cdff073305.webp"
          }
        ]
      }
    ]
  };
