/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/asdf
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "asdf",
    "title": "asdf",
    "category": "co-organised",
    "year": null,
    "categoryName": "Co-organised",
    "copySource": "authored",
    "html": "<p><span style=\"color:#000000\">this is the real name of the banglades....wwow ..this is the real name o</span></p><p><span style=\"color:#000000\">of bangladesh univer</span><span class=\"rt-size-36\" style=\"color:#000000\">asdf</span></p><p><span class=\"rt-size-36\" style=\"color:#000000\">asdfasdf</span></p><p><span class=\"rt-size-36\" style=\"color:#000000\">asdfasdfwow..this is working fucking as hell</span></p><div class=\"rt-embed\" data-embed-src=\"https://www.youtube-nocookie.com/embed/pPr3hms8lHo?rel=0\"><a class=\"rt-embed-play\" href=\"https://www.youtube.com/watch?v=pPr3hms8lHo\" target=\"_blank\" rel=\"noopener noreferrer\" aria-label=\"Play the video: YouTube video\"><img class=\"rt-embed-poster\" src=\"https://i.ytimg.com/vi/pPr3hms8lHo/hqdefault.jpg\" alt=\"\" width=\"480\" height=\"360\" loading=\"lazy\" decoding=\"async\" referrerpolicy=\"no-referrer\"><span class=\"rt-embed-icon\" aria-hidden=\"true\"></span><span class=\"rt-embed-label\">YouTube video</span></a></div><p><span style=\"color:#000000\">owasdfasdfasdfasdfasdfasdfasdfasdfasdfasdffasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasasdfasdfasdfasdfasdfasdfasdfasdfwow man this is so cool</span></p><p><br /></p><p><br /></p><p><span style=\"color:#000000\">this is before saving</span></p><p><br /></p>",
    "plain": "this is the real name of the banglades....wwow ..this is the real name o of bangladesh univerasdf asdfasdf asdfasdfwow..this is working fucking as hell owasdfasdfasdfasdfasdfasdfasdfasdfasdfasdffasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasasdfasdfasdfasdfasdfasdfasdfasdfwow man this is so cool this is before saving",
    "cover": {
      "alt": "Md. Redowanul Hoque, Vice President (Technical) of the 11th Executive Committee, BUET Robotics Society",
      "width": 1500,
      "height": 1800,
      "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACQBACdASoUABgAPzmOv1evKaazqAqqcCcJZQDE2AyZG2VGg+GFniterN5DeeAA/tlYeTYi5Ybo4+LQ1s6XXxb8t7WFbYCd7oWu43bHmbSKSbEUyyoEUOIRrTT3GL59uGxMwgQIXdSLJVhIgJw+O81VwfOMAAAA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/1b/85/1b85591ef7171634e5730a23edfffc055953897ab47ae8b428b1b13ac283ba79.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/34/a6/34a6a13216ee6ec49ec5de4920e9b9ceb092e26436050271c45d7b59c804b867.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/6d/38/6d38123cbb673dd231c7c59baafed1c8bb06184e2253f07a7ca2df6cbf71cad6.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/45/c2/45c240b76b8d97441c5b97ee54fd95bdacbdb4aee61be19bd0f9798c800d6c9b.avif"
        },
        {
          "w": 1500,
          "url": "http://localhost:9000/brs-assets/sha256/af/97/af97c57d8bbd4aab86136cfab74b62aba46da8d40cfbafc17dd4c4a48edea7a6.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/4b/73/4b73920e075b6751d5aafbb66fdff5e5e76fadba6aad353eecd36d0b4e23fbd1.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/6b/fa/6bfae97e166a6200ca71b91c365000d9ae0ba2ef555b14e6663bf7da6c3eb66a.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/e0/fa/e0fa6f514d1fc332f0dfdf84804141ed4258db5e983271d7ab73d68d022e40b5.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/69/c1/69c10db7dd020595480313a6672ff19b2dc5f82e4a233c5a2450cfc3a9c3949d.webp"
        },
        {
          "w": 1500,
          "url": "http://localhost:9000/brs-assets/sha256/62/f7/62f77a4aaddb04a0e6ce28e1314eb73d7389b376ac72fdee88995c93a97dfd9e.webp"
        }
      ]
    },
    "gallery": []
  };
