/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/intra-buet-intra-22
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "intra-buet-intra-22",
    "title": "intra buet — intra_22",
    "category": "intra-buet",
    "edition": "intra_22",
    "year": null,
    "categoryName": "Intra-BUET",
    "copySource": "derived",
    "html": "<p>BUET Robotics Society presents to you the first-ever Intra-BUET Robot Challenge. Intending to provide a platform for basic competitive robotics for upcoming robotics enthusiasts of BUET, we are glad to bring you an event of great challenge finally. So, fasten your seatbelts and be ready to participate in this special event o BUET. 𝗧𝗵𝗲𝗿𝗲 𝘄𝗶𝗹𝗹 𝗯𝗲 𝘁𝘄𝗼 𝘀𝗲𝗴𝗺𝗲𝗻𝘁𝘀: 𝟭) 𝗦𝗼𝗰𝗰𝗲𝗿 𝗕𝗼𝘁 ( 𝗧𝘄𝗼 𝗥𝗙-𝗰𝗼𝗻𝘁𝗿𝗼𝗹𝗹𝗲𝗱 𝗯𝗼𝘁𝘀 𝘄𝗶𝗹𝗹 𝗽𝗹𝗮𝘆 𝘂𝘀𝗶𝗻𝗴 𝗮 𝗯𝗮𝗹𝗹) 𝟮) 𝗦𝗽𝗲𝗲𝗱 𝗥𝗮𝗰𝗶𝗻𝗴 (𝗔 𝗥𝗙 𝗰𝗼𝗻𝘁𝗿𝗼𝗹𝗹𝗲𝗱 𝗿𝗼𝗯𝗼𝘁 𝗿𝗮𝗰𝗶𝗻𝗴 𝗲𝘃𝗲𝗻𝘁 ) A maximum of 4 members in a team is allowed. Soccer-Bot Rulebook- https://drive.google.com/.../14bph2VbC-oiI.../view... Speed Racing Rulebook: https://drive.google.com/.../1xP52U2zb7jsQAFtBPOII4g.../view 𝗧𝗵𝗲𝗿𝗲 𝘄𝗶𝗹𝗹 𝗯𝗲 𝗮𝘁𝘁𝗿𝗮𝗰𝘁𝗶𝘃𝗲 𝗽𝗿𝗶𝘇𝗲𝘀 𝗳𝗼𝗿 𝗰𝗵𝗮𝗺𝗽𝗶𝗼𝗻𝘀 𝗮𝗻𝗱 𝗿𝘂𝗻𝗻𝗲𝗿𝘀-𝘂𝗽 𝘁𝗲𝗮𝗺𝘀 𝗳𝗼𝗿 𝗲𝗮𝗰𝗵 𝘀𝗲𝗴𝗺𝗲𝗻𝘁, 𝘄𝗵𝗶𝗰𝗵 𝘄𝗶𝗹𝗹 𝗯𝗲 𝗮𝗻𝗻𝗼𝘂𝗻𝗰𝗲𝗱 𝗹𝗮𝘁𝗲𝗿 𝗘𝘃𝗲𝗻𝘁 𝗟𝗼𝗰𝗮𝘁𝗶𝗼𝗻: 𝗕𝗨𝗘𝗧 𝗰𝗮𝗺𝗽𝘂𝘀</p>\n<p>Intra-BUET Robot Challenge</p>\n<p>BUET Robotics Society successfully hosted the first-ever Intra-BUET Robot Challenge, providing a platform for budding robotics enthusiasts to showcase their skills in competitive robotics. The event featured two thrilling segments:</p>\n<p>Soccer Bot – A competition where two RF-controlled robots competed using a ball. Speed Racing – A high-speed challenge featuring RF-controlled racing robots.</p>\n<p>Teams of up to four members participated, putting their engineering and problem-solving skills to the test. Exciting prizes were awarded to the champions and runners-up in each segment, recognizing their outstanding performance.</p>\n<p>The event, held on the BUET campus, saw enthusiastic participation and fierce competition. It was a remarkable experience for all involved, fostering innovation and collaboration among BUET’s robotics community.</p>",
    "plain": "BUET Robotics Society presents to you the first-ever Intra-BUET Robot Challenge. Intending to provide a platform for basic competitive robotics for upcoming robotics enthusiasts of BUET, we are glad to bring you an event of great challenge finally. So, fasten your seatbelts and be ready to participate in this special event o BUET. 𝗧𝗵𝗲𝗿𝗲 𝘄𝗶𝗹𝗹 𝗯𝗲 𝘁𝘄𝗼 𝘀𝗲𝗴𝗺𝗲𝗻𝘁𝘀: 𝟭) 𝗦𝗼𝗰𝗰𝗲𝗿 𝗕𝗼𝘁 ( 𝗧𝘄𝗼 𝗥𝗙-𝗰𝗼𝗻𝘁𝗿𝗼𝗹𝗹𝗲𝗱 𝗯𝗼𝘁𝘀 𝘄𝗶𝗹𝗹 𝗽𝗹𝗮𝘆 𝘂𝘀𝗶𝗻𝗴 𝗮 𝗯𝗮𝗹𝗹) 𝟮) 𝗦𝗽𝗲𝗲𝗱 𝗥𝗮𝗰𝗶𝗻𝗴 (𝗔 𝗥𝗙 𝗰𝗼𝗻𝘁𝗿𝗼𝗹𝗹𝗲𝗱 𝗿𝗼𝗯𝗼𝘁 𝗿𝗮𝗰𝗶𝗻𝗴 𝗲𝘃𝗲𝗻𝘁 ) A maximum of 4 members in a team is allowed. Soccer-Bot Rulebook- https://drive.google.com/.../14bph2VbC-oiI.../view... Speed Racing Rulebook: https://drive.google.com/.../1xP52U2zb7jsQAFtBPOII4g.../view 𝗧𝗵𝗲𝗿𝗲 𝘄𝗶𝗹𝗹 𝗯𝗲 𝗮𝘁𝘁𝗿𝗮𝗰𝘁𝗶𝘃𝗲 𝗽𝗿𝗶𝘇𝗲𝘀 𝗳𝗼𝗿 𝗰𝗵𝗮𝗺𝗽𝗶𝗼𝗻𝘀 𝗮𝗻𝗱 𝗿𝘂𝗻𝗻𝗲𝗿𝘀-𝘂𝗽 𝘁𝗲𝗮𝗺𝘀 𝗳𝗼𝗿 𝗲𝗮𝗰𝗵 𝘀𝗲𝗴𝗺𝗲𝗻𝘁, 𝘄𝗵𝗶𝗰𝗵 𝘄𝗶𝗹𝗹 𝗯𝗲 𝗮𝗻𝗻𝗼𝘂𝗻𝗰𝗲𝗱 𝗹𝗮𝘁𝗲𝗿 𝗘𝘃𝗲𝗻𝘁 𝗟𝗼𝗰𝗮𝘁𝗶𝗼𝗻: 𝗕𝗨𝗘𝗧 𝗰𝗮𝗺𝗽𝘂𝘀 Intra-BUET Robot Challenge BUET Robotics Society successfully hosted the first-ever Intra-BUET Robot Challenge, providing a platform for budding robotics enthusiasts to showcase their skills in competitive robotics. The event featured two thrilling segments: Soccer Bot – A competition where two RF-controlled robots competed using a ball. Speed Racing – A high-speed challenge featuring RF-controlled racing robots. Teams of up to four members participated, putting their engineering and problem-solving skills to the test. Exciting prizes were awarded to the champions and runners-up in each segment, recognizing their outstanding performance. The event, held on the BUET campus, saw enthusiastic participation and fierce competition. It was a remarkable experience for all involved, fostering innovation and collaboration among BUET’s robotics community.",
    "cover": {
      "alt": "intra buet — intra_22 — BUET Robotics Society archive",
      "width": 960,
      "height": 480,
      "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAABwAwCdASoUAAoAPzmEuVOvKKWisAgB4CcJZScAAAw+f+T9zUAA/uIK0jj3vdgPBFOHrft6atkGBrW647taaO9ZT1lwBikGn7Vz/szwMTLwAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/8f/e5/8fe5ff8ff52ae59525c083b1482330d4d150758135523497bc28757ca8f648a8.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/66/c9/66c9fe50c34c448d9e780fe1d744f47d38997525649dfc77c8ae5a23a770c976.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/b4/0d/b40d44d208e073cb50ec698d00e5baa82b903e91a9a8f95f8bd75706b3a18ef4.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/3e/1e/3e1e60c97271d57ba43da25e88a7a3e5f6b377e591e106d4c5866cd59082c064.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/0f/7f/0f7fcc2b38662e936d1abf0c47f7bae03a8ba36afbf013755fe426706da06667.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/f2/c3/f2c3a171b57ba8dcefd61bba3790c33980401a7e2ce24d56d36f247d228f3e9a.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "intra buet — intra_22 — BUET Robotics Society archive",
        "width": 5184,
        "height": 3456,
        "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQBACdASoUAA0APzmEuVOvKKWisAgB4CcJYwCdEf/gQGnmAWv5IQbWvdXwAP7MUUE75RMH4Hgk6nsC2Irl/26p2mVDACOc6HXFQqHfHyRFT5AB7yeLeXAHlVY8rOgjFmA3cBvQFPfAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/89/68/89684f207d0cb5e38ac594c36976cca71749bca1dcd97ae36f8189b8fa675dfc.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/22/77/2277cb763b688bf8af5ab17c8adc584bf1c76b0285fe18dc2b002b04789c3923.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/a3/f5/a3f5049bd3cfd04a274a7684e19ef2f7246075802f980c14c9a364102beb1a5c.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/3e/12/3e129ca7606fd0169b91b972aa21219952b19df41dfecd04d1fe02a02b69b9af.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/0a/f9/0af99bcd5aff3ff2abe64d93a672d380cd9d56d439a730831adc4b8cf4b903c1.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/88/3f/883fac02849383688c643d1d2055d83a9a4ce432c17fdccbd3c44ee732222888.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/d4/f5/d4f5ebde192cddd1934ac841d6d1e437342bbfb47aa2c5cb1b3e61c42a7d867d.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/e4/ab/e4ab9a835c9e83c4a37d132bb347ed0b7f199dcf704f2fb09774800e6687cfb9.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/be/e6/bee6bd0576ff48c57e3b54254c0da57abccc8cd0fb075ef12569663c0b84609e.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/a6/be/a6bec9b12eadff1e571147727d57502b320f3dc8ae4d564fa93de9748d6df2ba.webp"
          }
        ]
      },
      {
        "alt": "intra buet — intra_22 — BUET Robotics Society archive",
        "width": 5184,
        "height": 3456,
        "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBACdASoUAA0APzmEuVOvKKWisAgB4CcJZACdMoGv/gG5n29L1ycs8gAA9pv24oWzyh75cvIiZYPKKMBEsb6aFDh9C1bpQrr+6fzLu3os/BN62S9NDcaUfZWslG0J71AsRaQqM3jOiKgsMgqD+6gA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/b9/e1/b9e118b55c13f375f6b788f73f15c7472d008a07f332fc2d93b0d211262a9606.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/9c/05/9c05d0109d6b9aeba776700032d151161509252aa9dcc3ea152e1bf20f3b66a3.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/36/5b/365bd7fa8fefa17cf5c2532a8b81bf5509ba8cb1cd14382521e2df6dadd29184.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/f0/0f/f00fcfacab8883ed8651e9d44f2f24896ed95bff16daac83c62636d0948b48a1.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/28/ff/28fffc61009da4dca8d6bfb3898d431712005697a01be0fe7f16e98febdd2a48.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/59/15/5915b0e4d62d362656a4fbfa34a8c5cb90994c2c47d63694eeca557b240d1473.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/56/fd/56fdda27174dabd26b2d3c18b1aa11da9725eb4175c8a042860790034b6ceb7c.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/1a/3e/1a3eaaf1502a4884bf41e68d8b266c72c3852f9fd7317882ef2ed9320bd34b95.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/93/39/9339a302d453f8756527657ece345c9f0820d98c866e4fb33af50e9a4529e8c0.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/c9/a6/c9a6683f1e998ed22431c5a45a1b183fa80c00850420de7755a7e228a9f54007.webp"
          }
        ]
      },
      {
        "alt": "intra buet — intra_22 — BUET Robotics Society archive",
        "width": 5184,
        "height": 3456,
        "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJQBOkJABFVf7frdYk9sYAAPzQSrm7Y97c5d1MNJC2My6mPIP6tAw7/IJ793P1BjnHQ85tzsWDun3LsG7+d58Nsmn751Pz7TJAO/19HGSs1hlBciZj3VVl8ZWPRELR5wAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/a9/5a/a95a377f33527835aefec9b08fe3fe46213010ac1e6f156dadcf149fc7096f2b.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/f5/bf/f5bfbc1d531415cb188e5bb29e28ffc1ac08cefffdc6370106474593c72a9a1f.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/ac/a5/aca59f3c89f258fd0f817d3a56c00016b83e6266800f6480b18fa71e9473ecd9.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e4/ad/e4ad4476cc911219bad1498b002a735a733be1583fc1749b61a2b0c8e546f568.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/06/7a/067a0b181fb23c18a5b2c89096e5d61d44eef873760acbe4de7bf825c5843bd5.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/7d/c0/7dc0046ddf341d4bc90ab53dde7b451a766425f0deb31910154f949f0fc0cb82.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/19/5a/195a7c1212e1173f89409222bba806d4071bf4f1d0aef2a68c136ece392a9e59.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/5c/fb/5cfbc4f009a7d1519a223378c66743fc464dc860895b8294208c0c0d0d2ed465.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/d3/48/d34819af9c1c583a3bd729a4715f4cf26379a9fe0e08cc894d8644e96f25f168.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/68/b9/68b9402bb128197ad15b291b7cf507be4512084bcb13063d732ecb0c73ee5c7a.webp"
          }
        ]
      },
      {
        "alt": "intra buet — intra_22 — BUET Robotics Society archive",
        "width": 5184,
        "height": 3456,
        "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwBACdASoUAA0APzmGuVOvKSWisAgB4CcJZgC7AB4jGoILh4J1AEugYAAA9zf7WyL6NjKsSj6s0BccIWsPe7XSTtAtB4FUQXETdTZ9RPS4dDeDW9/K9Jsn31wv6k7Qy7YLhsb5PU2VGgAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/e4/74/e474ac76103e9aa7041edb5f4008c329a84db2d90b2e271d0aaa8d80a45ed896.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/8b/7d/8b7d36f8061caf1a4c822863d36db1ea3203be267308de710f9643a3537cf0ef.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/67/c2/67c26ff94d327f7a8c4e5fa0611e1c050f78dfb3f99318242ad363209184c6ae.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/a3/f3/a3f3965aa50fd4196163e7b3e849497d795bbc94a8ca4ac79e9eba9fdfb06eb7.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/79/b1/79b1313230bf8417df2f5c9291277706054c3704805cc9883216eca2d1b73ca2.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/cc/42/cc42533e248d1eec600fedd83c66aa4c16ed3a4c0862f32c65e5f2a540d077a0.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ac/11/ac11c244e83953a71879f4f860c4e2954a01d4b39e1252cef2a009314d17a6bf.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/ca/6b/ca6bf0d7eafac73dc224cf76524894af98b488d1fdc1c5e54f89f1aeda26cda8.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/09/ef/09ef7ad33128987d0b20e6f8447596f3a1a2fc298c97e09838b8fe1b97e7494b.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/e1/ad/e1ad9e0db355a5eee19d26f497fba0300b23172cd3313ea343b3bc0520a02f08.webp"
          }
        ]
      },
      {
        "alt": "intra buet — intra_22 — BUET Robotics Society archive",
        "width": 5184,
        "height": 3456,
        "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZACdABmSC4J35ga9D/QA9qobYOsoBsZgDB9wBWOD3xFGCDw6AafGpubRjYqsO1R2+m2mL/bgrZ0DYrI9ZSU0JX3dFE98MMyX1Fi3awAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/c7/d1/c7d128f71b081bf58275bf2687ff11262a0d9c2ab84e5d4bc8f3a27dc21fe5e6.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/4f/8c/4f8cfd78a827146abf02e4cb76abd0c91d648eea9d0d4154aaf3bb21fb8bf297.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/d8/fa/d8fae377fe18133be622d785c8f9d416e388dc331511a45f2517b8178c62014a.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/4d/ee/4dee62bbda12145f06fa958be64bd296c8c60d1fdcbba35729ed9965896a2b5b.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/71/de/71de794ef2da6a262becc99558d248b8de0bdfb56ff18a147c8e4690d6424364.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/fc/97/fc97edb0eba66e301c7bdeac4eb44d2e1c3f55c25817a9060479f3700a1cbab1.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/fd/99/fd99ef75bd5810db8cbe984baa2c5fec58c94fc175233c3db0230ecdda76072b.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/7a/be/7abee35f5393f514417e8dcb85728f340ab8fb40f26c0cdc11be90c6b539631c.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/5d/0e/5d0eff5628341f5317ea9a7c926a49191f17ae0121f473b527bf33d7e0fbd382.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/e2/bd/e2bd14482ccdcdb8046537d95fb8f4e0a03a8a26a17200e45547cdabe2da80fe.webp"
          }
        ]
      }
    ]
  };
