/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/member-recruitment-2018
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "member-recruitment-2018",
    "title": "member recruitment — 2018",
    "category": "recruitment",
    "series": "Member Recruitment",
    "edition": "2018",
    "year": "2018",
    "categoryName": "Member recruitment",
    "copySource": "derived",
    "html": "<p>BUET Robotics Society(BRS) will set up its booth in the club fair on May 14th,2018. BRS is a platform for robotics enthusiasts in BUET. It organizes and coordinates workshop on robotics, and promotes new challenges for the students.</p>\n<p>Membership fee: BDT 200/-</p>",
    "plain": "BUET Robotics Society(BRS) will set up its booth in the club fair on May 14th,2018. BRS is a platform for robotics enthusiasts in BUET. It organizes and coordinates workshop on robotics, and promotes new challenges for the students. Membership fee: BDT 200/-",
    "cover": {
      "alt": "member recruitment — 2018 — BUET Robotics Society archive",
      "width": 2048,
      "height": 1502,
      "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAADwAwCdASoUAA8APzmEuVOvKKWisAgB4CcJYgCdAB+MhxvkgWOlReTgAPjZON1hN527gKylX0Ht8nb2iDJdnP5qvixk+DIK3Q7BbcNxc8xkaJq2YidvM/DnmILTlu4O+OazJvIFp5iTqRZx1nuq+MV1yXmQQdUTVBOdEI9UwCgMANQAAAA=",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/95/42/9542f3e453e2705fab824f665d3e6829cdcfb14d958362eacc976c6185314328.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/bd/c5/bdc56014706cb5228baf0cb840cdad0447e4efcd3befcb02c5915ed1c1007793.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/05/6c/056cbefebcff99bf0be72b3eb61981b7438afd7aca58eb4942d8efce61ea0338.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/ca/38/ca3816fd86eab54b63aa1beda345ca29d0b8247004a8041e40281b0309d7785f.avif"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/fc/31/fc317202f9bc049d839c7f403fe3fb902acb1bc5858232e31a827bd0eff04bb1.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/41/7a/417a78b7de4081c9e290c08c2a0d06522267b62532ceb3da776f0babdf5b848f.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/cd/48/cd48d994bb1941b18b3dfe12069fe1ec9a61b8941e95990fd074c76a45b43dac.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/c9/1a/c91a06171f06514f0a0240f5b3b40311585c9b0dfa56344b918716b415168b4c.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/b8/8c/b88c263306b202f0dac1c11d7056155191b0448fd4da4a25dc4c0e79393e4e71.webp"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/c4/7a/c47aaefb5514f74bbf3373df91b447fe36f762588de2f46e91af934511b4fba2.webp"
        }
      ]
    },
    "gallery": []
  };
