/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/orientation-programs-robogenesis
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "orientation-programs-robogenesis",
    "title": "orientation programs — RoboGenesis",
    "category": "orientation",
    "edition": "RoboGenesis",
    "year": null,
    "categoryName": "Orientation",
    "copySource": "derived",
    "html": "<p>Imagine walking into a room buzzing with creativity—robots in motion, brilliant ideas on display, and energetic minds all around you. 𝐑𝐎𝐁𝐎𝐆𝐄𝐍𝐄𝐒𝐈𝐒 is more than just an event; it’s a gateway into a community where technology meets imagination, where freshers become future innovators. Whether you're already passionate about robotics or just curious to explore, this is the perfect place to spark that excitement and start your journey. As you embark on this exciting new chapter, get ready to take your very first step into the fascinating world of robotics. The BUET Robotics Society is proud to present 𝗥𝗢𝗕𝗢𝗚𝗘𝗡𝗘𝗦𝗜𝗦 – 𝗕𝗥𝗦'𝟮𝟰 𝗙𝗿𝗲𝘀𝗵𝗲𝗿𝘀' 𝗥𝗲𝗰𝗲𝗽𝘁𝗶𝗼𝗻, a vibrant celebration of creativity, innovation, and discovery designed especially for you! This year’s reception is designed to introduce you to the spirit of our society through three main segments: 𝐑𝐨𝐛𝐨𝐕𝐢𝐬𝐢𝐨𝐧 𝟏.𝟎 – Share your ideas and showcase your creativity through your poster. Make your mark in front of peers and mentors and win exciting prizes. 𝐑𝐨𝐛𝐨𝐭𝐢𝐜𝐬 𝟏𝟎𝟏 – New to robotics? No worries! Learn the essentials in a fun, beginner-friendly hands-on session. 𝐑𝐨𝐛𝐨𝐐𝐮𝐞𝐬𝐭 𝟐.𝟎– Put your knowledge to the test, compete with your peers, and win exciting prizes! 📅 Date: 𝗠𝗮𝘆 𝟮𝟲, 𝟮𝟬𝟮𝟱 🕒 Time: 𝟱:𝟬𝟬 𝗣𝗠 📍 Venue: 𝗔𝘂𝗱𝗶𝘁𝗼𝗿𝗶𝘂𝗺 𝗦𝗲𝗺𝗶𝗻𝗮𝗿 𝗥𝗼𝗼𝗺 (1st floor) Be a part of this thrilling celebration of innovation and curiosity. Meet new people, discover your interests, and step confidently into the world of robotics. We warmly invite all freshers to join ROBOGENESIS and kickstart an unforgettable journey. Let’s build the future—together! 🤖✨</p>",
    "plain": "Imagine walking into a room buzzing with creativity—robots in motion, brilliant ideas on display, and energetic minds all around you. 𝐑𝐎𝐁𝐎𝐆𝐄𝐍𝐄𝐒𝐈𝐒 is more than just an event; it’s a gateway into a community where technology meets imagination, where freshers become future innovators. Whether you're already passionate about robotics or just curious to explore, this is the perfect place to spark that excitement and start your journey. As you embark on this exciting new chapter, get ready to take your very first step into the fascinating world of robotics. The BUET Robotics Society is proud to present 𝗥𝗢𝗕𝗢𝗚𝗘𝗡𝗘𝗦𝗜𝗦 – 𝗕𝗥𝗦'𝟮𝟰 𝗙𝗿𝗲𝘀𝗵𝗲𝗿𝘀' 𝗥𝗲𝗰𝗲𝗽𝘁𝗶𝗼𝗻, a vibrant celebration of creativity, innovation, and discovery designed especially for you! This year’s reception is designed to introduce you to the spirit of our society through three main segments: 𝐑𝐨𝐛𝐨𝐕𝐢𝐬𝐢𝐨𝐧 𝟏.𝟎 – Share your ideas and showcase your creativity through your poster. Make your mark in front of peers and mentors and win exciting prizes. 𝐑𝐨𝐛𝐨𝐭𝐢𝐜𝐬 𝟏𝟎𝟏 – New to robotics? No worries! Learn the essentials in a fun, beginner-friendly hands-on session. 𝐑𝐨𝐛𝐨𝐐𝐮𝐞𝐬𝐭 𝟐.𝟎– Put your knowledge to the test, compete with your peers, and win exciting prizes! 📅 Date: 𝗠𝗮𝘆 𝟮𝟲, 𝟮𝟬𝟮𝟱 🕒 Time: 𝟱:𝟬𝟬 𝗣𝗠 📍 Venue: 𝗔𝘂𝗱𝗶𝘁𝗼𝗿𝗶𝘂𝗺 𝗦𝗲𝗺𝗶𝗻𝗮𝗿 𝗥𝗼𝗼𝗺 (1st floor) Be a part of this thrilling celebration of innovation and curiosity. Meet new people, discover your interests, and step confidently into the world of robotics. We warmly invite all freshers to join ROBOGENESIS and kickstart an unforgettable journey. Let’s build the future—together! 🤖✨",
    "cover": {
      "alt": "orientation programs — RoboGenesis — BUET Robotics Society archive",
      "width": 1000,
      "height": 1000,
      "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUABQAPzmUwVmvKic/qAgD8CcJQBgbgZCeMycr0sgDpOqInYAA/tOWSnHZfBhI4TFxoLhNgK2fVjw4YIE0CWrjgKtKtDEWE2JYrLPTXQsWiIAXkQAAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/6f/ea/6fea20fd3c63dbc50bcc936ab8a2de58e51d761618e1b2d46bd8a771d0ddc358.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/6d/f2/6df2063ea29a4fa8fe44cd654ecad1ffc27d5e3bf15ebadd98541f12c564a09c.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/e3/fe/e3fec684e2afab8ef96c7d34baf51b6c7d8f185b86b342c412bdc4175bfd6586.avif"
        },
        {
          "w": 1000,
          "url": "http://localhost:9000/brs-assets/sha256/83/83/83832b7608d3772b5196270a73c1bbe8544573278b390070de32ac4b95a4bc9d.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/11/6b/116bf84f00529e92fff07ac46e5ec09037689900b426f8f4e5ae09722410b4a8.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/0c/97/0c97549893496e5f85e31ab56e8222ad20639b026c77b6ba65dbcb7c33e1a58d.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/48/1d/481dd5d56d6cf7943b64aefd0fe568f996df8dd6150a00ca2f0db3033480afe6.webp"
        },
        {
          "w": 1000,
          "url": "http://localhost:9000/brs-assets/sha256/96/c3/96c3cbb13357fb3f18b2d9e9f413d5241fc746c3885967a37bafe3c405c95161.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "orientation programs — RoboGenesis — BUET Robotics Society archive",
        "width": 526,
        "height": 526,
        "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAwBACdASoUABQAPzmQvVgvKaY+KAqrwCcJQBhQAZCdUr5xJPh36yrCNqAA/tOWSnHZe/KL5bh+mL0akMUZDZNnp1jE3D0xauoLiXV/vR/MSloAUGggdTdkb0jCjiTSiTUMAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/8d/fb/8dfbf8f68ab63c2ebe6b1eee2f452ffa660af164dc608acad994cce18ca8c498.avif"
          },
          {
            "w": 526,
            "url": "http://localhost:9000/brs-assets/sha256/23/8b/238b6541b593ec969ec0d940019ea09dcc8baa6d7129d922d54d8955bb25a874.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/05/d9/05d948a7953ef101f5d5292dd925ab47aa5a2657ab6cd0cc9bcd9e689cc592c9.webp"
          },
          {
            "w": 526,
            "url": "http://localhost:9000/brs-assets/sha256/3c/e5/3ce5a6e9d14066749445b7b09037aa6467bd3cb04b5a18388485689c1ce3d43a.webp"
          }
        ]
      },
      {
        "alt": "orientation programs — RoboGenesis — BUET Robotics Society archive",
        "width": 1024,
        "height": 1536,
        "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACwBACdASoUAB4APzmGvFavKCYjsBgIAeAnCWkAyngQ5F1YlC6MNQt1AOI/BLYQAP6T1hIa4azU6ElaFtvDHQV5NYixTEorzQgXT8KzE6mlnmHwy15aQrXVdxHcMJ9mTuXrmyIw3PN5TvWF24PV7hOJmLKHHEwtdg5p/eW03be/09TDVW6ltgAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/85/93/8593f707af020a52a9d2c57f7c398465c302ca4599dbc935bb78e469b68dd332.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c2/6a/c26a32a4747addc305a5c5a3425a5ffdcb8a92df31352fff7f48b8a03b9d0190.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/15/0e/150e41fa02a53a5389b4b173714f8a3ccf11fc5baa2b8074a3b554674a106231.avif"
          },
          {
            "w": 1024,
            "url": "http://localhost:9000/brs-assets/sha256/b7/cc/b7cca6500b18bebc61d2d02fde85bdfe99899a2821e91d4f43cb68f81f2d07c9.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/ae/d7/aed7b8306fe3f0fd174c1a67f5d43240db21c01083ac515261bd6e180740d0e6.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c0/71/c07115fdf916f5134f12a9a7299394db652061b2854dc45e2935a689b2e62d89.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/dd/7d/dd7d97cda2108215bd91bc1d447cb702c1b30508c39e03a9f952923aaf932d6b.webp"
          },
          {
            "w": 1024,
            "url": "http://localhost:9000/brs-assets/sha256/fb/67/fb67e559598de367ce6dae2a496a381192788e22008a6523ea1fc8d3622af4c1.webp"
          }
        ]
      },
      {
        "alt": "orientation programs — RoboGenesis — BUET Robotics Society archive",
        "width": 526,
        "height": 526,
        "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwAwCdASoUABQAPzmUwFmvKia/qAgD8CcJQBibAZDtRZmfKXAA/tOWSnHZe/KL60WGavnP9AqIIsRX/orlTPfkUyCP3o7iEXbhdf/6FpIEbS+SGTh9epmZCZ+wpMPGFIAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/eb/9c/eb9c53e4fb698597610932fcafaa17de2bccb59e7d05b49ffc2f648fd53d712f.avif"
          },
          {
            "w": 526,
            "url": "http://localhost:9000/brs-assets/sha256/a1/c8/a1c8897ae2bc3ad17b5a0bd0fad2326f8978fc9d9eef11dd55d8e9cee85e3fca.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/bd/0a/bd0a4d6f4f0a7bc20dedb2b18b7a9e0ee53c2924acefb0f0bfad04e40f684464.webp"
          },
          {
            "w": 526,
            "url": "http://localhost:9000/brs-assets/sha256/ba/db/badb19c1cf60600d8cab551904865ed74c6d9fdea5e12fba869f73cc73069943.webp"
          }
        ]
      },
      {
        "alt": "orientation programs — RoboGenesis — BUET Robotics Society archive",
        "width": 960,
        "height": 510,
        "lqip": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACwAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJZgC06BnkV1eK5g9GQAD+w/IyHiLEM6WUf3N6YNm1+fcoF+N1jLd2K72pJmy/aWTsAAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/88/f0/88f0601a480cb4ccbf1bd81a0b7653de150d8c38e19ad25e202f47fd044ebcae.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/37/3a/373accf148d060e7d92159f87051aa17d84e4da92cc0232fc37badf70d2ebb09.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/99/87/9987cb518619a131d9d48e27f1023ca81f5b5d1c86d4ee120f2d30d6acdbed01.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/65/85/6585644a43f5b885dfa587ab5341389d27d2b66dcc86a1a9763e896ea6e72cf0.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/6d/95/6d95737611c8d89764cd554a664fab6b916b8400270022bb99b7316469d9e092.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/3e/20/3e20c31364d53d3610da5f5a5db43d84ecf54dfcf35f5c838e7a38d6837153b0.webp"
          }
        ]
      }
    ]
  };
