/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/orientation-programs-2023
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "orientation-programs-2023",
    "title": "orientation programs — 2023",
    "category": "orientation",
    "edition": "2023",
    "year": "2023",
    "categoryName": "Orientation",
    "copySource": "derived",
    "html": "<p>'𝐁𝐔𝐄𝐓 𝐑𝐨𝐛𝐨𝐭𝐢𝐜𝐬 𝐒𝐨𝐜𝐢𝐞𝐭𝐲' 𝐢𝐬 𝐨𝐫𝐠𝐚𝐧𝐢𝐳𝐢𝐧𝐠 𝐚 𝐫𝐞𝐜𝐞𝐩𝐭𝐢𝐨𝐧 𝐩𝐫𝐨𝐠𝐫𝐚𝐦 𝐟𝐨𝐫 𝐨𝐮𝐫 𝐧𝐞𝐰𝐞𝐬𝐭 𝐦𝐞𝐦𝐛𝐞𝐫𝐬 𝐨𝐟 𝟐𝟏 𝐛𝐚𝐭𝐜𝐡, 𝐭𝐡𝐢𝐬 𝐖𝐞𝐝𝐧𝐞𝐬𝐝𝐚𝐲. All of our new members are cordially welcome to attend the meeting. We will talk about the BRS's motto, workshops, the upcoming Robo Carnival, and many more. Let us explore the degrees of freedom, with BRS.</p>\n<p>Venue: ECE Building, BUET Room No: 535(EEE side) Date: 07 -12-2022 Wednesday Time: 5pms</p>",
    "plain": "'𝐁𝐔𝐄𝐓 𝐑𝐨𝐛𝐨𝐭𝐢𝐜𝐬 𝐒𝐨𝐜𝐢𝐞𝐭𝐲' 𝐢𝐬 𝐨𝐫𝐠𝐚𝐧𝐢𝐳𝐢𝐧𝐠 𝐚 𝐫𝐞𝐜𝐞𝐩𝐭𝐢𝐨𝐧 𝐩𝐫𝐨𝐠𝐫𝐚𝐦 𝐟𝐨𝐫 𝐨𝐮𝐫 𝐧𝐞𝐰𝐞𝐬𝐭 𝐦𝐞𝐦𝐛𝐞𝐫𝐬 𝐨𝐟 𝟐𝟏 𝐛𝐚𝐭𝐜𝐡, 𝐭𝐡𝐢𝐬 𝐖𝐞𝐝𝐧𝐞𝐬𝐝𝐚𝐲. All of our new members are cordially welcome to attend the meeting. We will talk about the BRS's motto, workshops, the upcoming Robo Carnival, and many more. Let us explore the degrees of freedom, with BRS. Venue: ECE Building, BUET Room No: 535(EEE side) Date: 07 -12-2022 Wednesday Time: 5pms",
    "cover": {
      "alt": "orientation programs — 2023 — BUET Robotics Society archive",
      "width": 960,
      "height": 540,
      "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABQAwCdASoUAAsAPzmGulOvKKWisAgB4CcJYwAAT+JZwEkyAAD9SVf4ReEgo+eifyhqhYP56DG3zLW0H/5g0CuL6d3iR0eHrrYAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/87/7d/877d9971caafb490a6e902de51c0dc2b53208e37cf491691f9344388816f5e31.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/49/cc/49cc40c1bced9ff31a53b12083f658dce4f472a38cc220a98a74259ec0080175.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/86/23/86234d3fbba6cbb3133d965a77e47154a4d2a399da349ee9ee54a829e791a8d0.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/d2/23/d2233a87ff6b8b88f2c6a18ad50e42e1b964f77ae3fcbf4a58776099259226e1.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/20/f8/20f8ec77b6793e121e69ae371cea1c4e151816faa16f906dc47149b42078b7a5.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/e8/c9/e8c9a9b45d16d38e63eab1f94dc5762f27cb75dd6e358851dcc3059dcfb2818c.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "orientation programs — 2023 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1538,
        "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAABQAwCdASoUAA8APzmEuVOvKKWisAgB4CcJZwAAMoFVtHlsUAD+It7x0fKlFZdTH2zysuPevgY9zO9AoxT7Zd2q1iRlyl/+Hp+6Q1fbm2Jf3Bi+bGnpCFl4AAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/ee/8f/ee8f9d5fc782be708413035a961780fe1e3995eae0c63c12566c97e36106b6a0.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a5/c9/a5c948db53bba32ef0522e43383b6b6f238c75899904b979ced627d164352337.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/33/e0/33e0ec6b9fe018230d88b0cf15ed1cfc832daad25f11b50f3b44bf0fb0882dcf.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/a8/cd/a8cd068ecf774d48cfdf25b3228d87adddd716c1e20d3f840fff3a36a654af21.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/66/20/6620259ccbdfba95172675da5bfd553ee71d06545d60973491b50a56c94d2291.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/6f/44/6f44cb449daf56544ec5a0bd3b406b2b36fcbd7d9aff358b84f9bb8722cdc2bd.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/b5/85/b585183759e6f07d26fada34a4c4d40ea29c7cf4bee51c22f6f811a851f42b6b.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/c5/de/c5de9595bacdee91f087291835ec7f0e4a794b2b0493f9b5617e4f3712d3d158.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/d9/d1/d9d16fdd0f926b23cc5acb37ba326f1238ce16867eadd6b5947b3992e308d774.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/6d/bc/6dbc3497f7777eb0c630b6c9169e3f69d57174ba17b91cc1f92e20ee88bd54da.webp"
          }
        ]
      },
      {
        "alt": "orientation programs — 2023 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1538,
        "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoUAA8APzmGuVOvKSWisAgB4CcJZwAAQc3MGjk2fEKkw4AA/p7EKwVKZuQJuCjeYbWYbkCeoAi4T+LccGBgTagVA4qlCIYdXBSYbOt6NXj/Tb2l6zw00KAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/c3/01/c301de4d884e04a26ee27ac7d8dcda849c2ee06564ee11afb3b4d6e33bd41ea7.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ab/c8/abc85e53302384ad04664dfa18b2b5f5ba3cdbc2f1ff2abbd01c9945bb6fc5a2.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/b3/63/b363d7c9e37484eb5aa2c1483b647e9f3f3f0aeee821c980b7e7ca50ee8ca524.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/92/15/92157b33fe931cd31a963e1b8f8857d1adb27231422363ca08028f98344c0638.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/e4/7f/e47f97a83a63123f3bdd6e1dd18813e27c8270cf3d0186ec36c568a0fd46aa59.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/cb/af/cbaf2764fce1a04ff8cb459e461e6f9b87534e02c1714d448f767b7acd95ab9c.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/bc/5d/bc5d0c00b1fbda81e3db32920edc15a0a57f771f8d1c04841c0b6348250a46bd.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/80/d9/80d94557c3f244576c9c7eb46935ed9824e1a1e78b6781539229c592d4de8b2c.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e4/46/e4463aaf24b5051f47b9d19936c6211423abde8c8405cafd85d9553ea341d763.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/84/88/848817ccea4408c9c6dc0fa467be83ff22141214e82fa697c8aa22744c258c7f.webp"
          }
        ]
      },
      {
        "alt": "orientation programs — 2023 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1538,
        "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAA8APzmGuVOvKSWisAgB4CcJZwAAWm/NOicQiJhF6AAA/h+OiGLZERn6cDdyYKMKdy02aAUuUZ/KGOxQjpMOzu5/ZGXsamZ8GncTab3zwIAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/09/d2/09d2fe1741fd2ec194507e386255b4995fe0b3dfccd1225331b38d7ba0b2886a.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c5/6e/c56e4b6ebe6eec3370b1dfa59d0ab9526ec097cab6808e021ac43f355130cef2.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/68/33/6833634eaea86a03efeb2c1c94892404721c6ee66273a9f1c36cd1d91ff92e5e.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/f1/7e/f17e30400de8cdd0020ee8a327ef90bd9dcf594f782119fe0f6cf2830c2cd8cc.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/28/68/2868245883c3e19a63fdb83865f217c09d381acca21dce0f9412144df97d2e62.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/82/78/8278d80f547e3d5a0ae3a14e48573e311f2dac41cc732168014e54302c70b2f3.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/67/a5/67a5e666f43429cee51668c3bcc43a3da037183a75a5d3a87d82bf37410b0136.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/7c/0b/7c0b0fe2e541998a759b1c82c3c0ac0be6158d12236ad0c92c6bd5864589a6b8.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/94/43/94431f952f037694c1f1e7390a042afc73de07ad72b46b32eae6fa7194e05051.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/9c/39/9c39799754f448bc315973bb4e1dd77729baf692bcea9fa267b6e23a99e80927.webp"
          }
        ]
      },
      {
        "alt": "orientation programs — 2023 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1538,
        "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwBACdASoUAA8APzmEuVOvKKWisAgB4CcJZQAAUqtNSEWosMmbv5stGAAA/rr8Q1oYLkOjOI5pTOVDcxcILrtOSjCYNt9rSlvj8G7gWCYe8WOqMiaF5bKsx2QAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/41/fb/41fb0af8c7adae1636acec3bcea26e1f4b114aad964495db10d6e54c06f76cd3.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/b2/f2/b2f2b212ffe5fc9dd4788e18e4db880051806e1c9c01cad19b350e89a94f57a7.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/77/6a/776a30158621de67453a187951d922edfd79c90a0ab4c191e9905ef4e10fc7de.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/47/f2/47f2ae973ea04abc181bc6f92d952658e98819101138b3e87083c4a50107675b.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/55/6e/556ea6f6750d1fed93723b30483863117373f7783c22504bc27f62a89e0613d1.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/74/4e/744e597c8bbbf8b5a884a1e60fef9c8abb32d76a530b6fd523d0bf16485feca1.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c0/ab/c0ab0751f1c6fa8801fd4b4433169f54c66b9d14e55a53211e5c361aca1be6ee.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/de/44/de4473ea1d528186b7c8cc28832208045de45725a2ff726dbb4784ff4fc9fcdd.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/54/c9/54c9c41bd4a45a2092abb8fce1bee763b7e22f568ba3aed680918a6a2bbe9aa1.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/3a/c2/3ac2a1f0d9b63c8554478555dd2f5cfc668c20f69bd65c353f121d6e3e86de0a.webp"
          }
        ]
      },
      {
        "alt": "orientation programs — 2023 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1538,
        "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAA8APzmEuVOvKKWisAgB4CcJZwAAMKJkJF4CDV9oAADbvlxumomdDT94ijWuC2rSdFvKtYj0zppqkr8OELrRrpjywUSryHFcwLfXdIUMXJKMDbRPgzB7AAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/9e/53/9e53b6908efd75861efd83daaabca0334ac5c3d23d99a656e0f120ef5f72c921.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a8/21/a82131348aa545e91a51319ce38b83434f05266d0b4e5cdd8539a744805a57da.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/ad/fc/adfc1913884f8bd4b1666c940a6e96897d3ecdfe0b3f7d20e5f4354ef76db1be.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/12/85/128527139dbaa4ee1ca3debee9696d566b380fa5400f73ee0e533b62e730a7c4.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/26/78/26788fade4ce1549a2754aed3f1d769966e9136d1245a4c6b85a3ecd2611e04a.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/11/2a/112a57c196b2c473f2d2b4d852589d21d05ccec4a744025766764a288b5dcd59.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c6/c7/c6c743869fb7fbf0190fe08d17c12b20e6f5e2f3e30e61bf0223fdb5b20b5c1c.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/db/ff/dbffd9ca97ea094abc3783291bcf91b18a7793ab7c7638036f3d476f6ec32ddf.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/cc/6a/cc6a8a121092af748f3f564692c51618fd57b5672a14a28e77966f1691dc5a99.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/fd/71/fd7153b91d2a7f312ef9f9e24cba439fb08f407ec2ac3b3d76b6a9ee03bad10a.webp"
          }
        ]
      }
    ]
  };
