/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/orientation-programs-2022
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "orientation-programs-2022",
    "title": "orientation programs — 2022",
    "category": "orientation",
    "edition": "2022",
    "year": "2022",
    "categoryName": "Orientation",
    "copySource": "derived",
    "html": "<p>'BUET Robotics Society' is organizing a reception program for our newest members this Wednesday. All of our new members are cordially welcome to attend the meeting. We will talk about the BRS motto and many more. Lets explore the degrees of freedom, with BRS. Venue: ECE Building, BUET Room No: 535(EEE side) Date: 22.06.2022 Wednesday Time: 5pm</p>",
    "plain": "'BUET Robotics Society' is organizing a reception program for our newest members this Wednesday. All of our new members are cordially welcome to attend the meeting. We will talk about the BRS motto and many more. Lets explore the degrees of freedom, with BRS. Venue: ECE Building, BUET Room No: 535(EEE side) Date: 22.06.2022 Wednesday Time: 5pm",
    "cover": {
      "alt": "orientation programs — 2022 — BUET Robotics Society archive",
      "width": 1080,
      "height": 539,
      "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAAAwAwCdASoUAAoAPzmGuVOvKSWisAgB4CcJZ2DrADbP2FAAAP7YPXX8ycgW3n8ylSoRNvTl/u39do9CwhxPq8P75v0DxYmDW7AAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/ce/28/ce28ae86eb2f2a933479ad333d2f475acaa8fffd555a4486a0b6c4cf1a8fa942.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/a6/6b/a66bd133396934a9e3ca8db958602f95f93896e25c61a007e955d032ba6fb045.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/a2/27/a227f2c1567a7ef940ead6b8d8ef6eaa3139286b59e0640326a31965f4883754.avif"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/37/12/3712e7bea32f33fde38c2c48710e775480b439dc918da98d10261ffa778ea51b.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/d0/ac/d0ac604c3f806a56208914ab3e5f327f6493824f36e618c44fb42fa00e06983e.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/3e/56/3e566f67faf76088c05ed1ea26934304a3de90af29bae879e99cdaa72ffd8d50.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/32/67/32674d0a6645d425a62b40e9ba8f5713776ea89814d09955372acf558f8ee74b.webp"
        },
        {
          "w": 1080,
          "url": "http://localhost:9000/brs-assets/sha256/d6/2d/d62d38b70f64e48fe74ef94c2adbaf5a71c1c7ddec9d8694441e1fffa557377c.webp"
        }
      ]
    },
    "gallery": []
  };
