/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/seminars-global-problems-local-solutions-2016
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "seminars-global-problems-local-solutions-2016",
    "title": "Seminars — global Problems, local Solutions 2016",
    "category": "seminar",
    "edition": "global Problems, local Solutions 2016",
    "year": null,
    "categoryName": "Seminar",
    "copySource": "derived",
    "html": "<p>The day is half way through! In the second half there will be an exciting seminar presented by Gorky Sakhawat Sobhan, Director &amp; COO, Monico Technologies Limited, on the topic : Global Problems, Local Solutions! So drop by the Seminar Room (1st Floor) of the Central Auditorium ~ Reporting time is 3:45 PM. No registration required! All visitors welcome!</p>",
    "plain": "The day is half way through! In the second half there will be an exciting seminar presented by Gorky Sakhawat Sobhan, Director & COO, Monico Technologies Limited, on the topic : Global Problems, Local Solutions! So drop by the Seminar Room (1st Floor) of the Central Auditorium ~ Reporting time is 3:45 PM. No registration required! All visitors welcome!",
    "cover": {
      "alt": "Seminars — global Problems, local Solutions 2016 — BUET Robotics Society archive",
      "width": 921,
      "height": 1036,
      "lqip": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwBACdASoUABYAPzmUwFmvKaajqAgB4CcJZQDMWy67eUE6q5OvmCyRvErb8biOlgAA/rxFUM9KDSboBawckB1PyQTS3XKLdawR0e0sNTvgo/KE7jEWNoXLBRWCyAQbzCLwKEwgsdVHFGYdF9rPnc2sgP3xTmbScy0GPYw8TocE2Bq/O4SbSUCnP8/M4/+AAAA=",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/7b/9e/7b9e0f28dfb408565537e4e9e344fb35bed9ec1a503f5ce26c661ab81d3c125a.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/6c/d6/6cd6f268840ec388cecd34761ea26ef752d3e29d4466bf146162776de5e3c77c.avif"
        },
        {
          "w": 921,
          "url": "http://localhost:9000/brs-assets/sha256/b1/55/b15593203df79b075b3ca4b852ac6ce334812823392ae31945d26855e13fe1b7.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/d8/fa/d8fa836d817239212c1ceb06d73dfad3f85ae1b53ef920dfb35004b321f9c11c.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/e0/97/e0973e0e67a7130fdf116e5d5fa07a0936399f7a8f50336c7fdb35c2c2195f1a.webp"
        },
        {
          "w": 921,
          "url": "http://localhost:9000/brs-assets/sha256/ba/42/ba4217e9d69a071fd7d41e86907e26e0cb2762ed6f58e51319ba5df70a49641f.webp"
        }
      ]
    },
    "gallery": []
  };
