/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/seminars-ros-and-deep-learning-2018
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "seminars-ros-and-deep-learning-2018",
    "title": "Seminars — ros and deep learning 2018",
    "category": "seminar",
    "edition": "ros and deep learning 2018",
    "year": null,
    "categoryName": "Seminar",
    "copySource": "derived",
    "html": "<p>BUET Robotics Society (BRS) is going to arrange a talk on ' ROS and Deep Learning'. In the present era of robotics' development, ROS helps provide a framework for robotics software development, while Deep Learning is closely related to information processing and communication pattern. Speaker: Mr. Abdul Muhaimin Rahman, ROS and Deep Learning Engineer, ME '10, BUET. Date and Venue:</p>\n<ul><li>Date: 13th May, Sunday</li><li>Time: 5:00 pm</li><li>Venue: Room No 236, 2nd floor, ECE Building, BUET.</li></ul>",
    "plain": "BUET Robotics Society (BRS) is going to arrange a talk on ' ROS and Deep Learning'. In the present era of robotics' development, ROS helps provide a framework for robotics software development, while Deep Learning is closely related to information processing and communication pattern. Speaker: Mr. Abdul Muhaimin Rahman, ROS and Deep Learning Engineer, ME '10, BUET. Date and Venue: • Date: 13th May, Sunday • Time: 5:00 pm • Venue: Room No 236, 2nd floor, ECE Building, BUET.",
    "cover": {
      "alt": "Seminars — ros and deep learning 2018 — BUET Robotics Society archive",
      "width": 2048,
      "height": 1365,
      "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoUAA0APzmGuVQvKSWjMAgB4CcJZwAAXoO2NdEYsILlsowAAP6vJGFpwfIRMf1DBuG7K3Nc9r5bZwoMFpBk9wQICrVAIRCZVW29sM3qNTZwIEAA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/c9/e1/c9e1ba09ba159af931b6ca2c91e8889aa949ce03ab53c73280ed2b68bfe2a968.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/93/87/9387ad3a246d722e5a425815bf7c27a02bf169a93752de9f76b2b6b640b9f43d.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/85/4f/854f39e4397bc35de284d901685d1e3d2d8f9a7b1bafbc3968fac6c1852b7c14.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/ab/81/ab814a126b54f00c5f2acbb4da86940a5ae1d88c25557b2d52d24a81fa859675.avif"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/15/db/15db859ffb6e72e2ec48b90ddc48d393fcc9f344c6fcd25641cbd6d5694a0bed.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/28/3e/283ed0a3035d09c41d8e31e980defec4740f0e41638f029109e33948e1227071.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/e8/fc/e8fc8fb20f57801719a0902468df1487199b2c90a10aedf91ece354c4db0891d.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/00/5e/005e74b6a690ca24cf42a30df1aedbdd6078cec2412f1395d2d8ab2cf2bc87dc.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/5b/80/5b801d61866ce340f1d1379984131991401468b29ee7dcc4c14d0400bb0d3d04.webp"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/d5/3e/d53ec479042067c9eab72e92246e0ace6d9da4f77b85584e55af6dba2d0e6d47.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "Seminars — ros and deep learning 2018 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJYwC+SBwvFMCC1gx2AAD+wVNIbanyYLSYig/66RNJ560uIFKrfcoZ8vpEx34emvW46bc9ulyGEFmk0nRflAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/0f/5c/0f5c6b905d100f649e68f1c80f3ac9e6027935d7e1f67b7407d27c028aef3cc6.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a8/a9/a8a9d4b0dbdc4ec819b0bee05e61340e9e23f16f20b9e0fafcea0dbcb6ce2802.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/34/39/34394ae6a4dcf522eb31cf9de10651037f67e6032d1720aa7f9fe1be07101938.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/53/f5/53f5276ccc88da8130d62009b62f05437e6f42a995c3ee297e7c6d81047454ed.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/fd/b5/fdb53c698a902f0fbf61f1559d1729d472b60e457eb137c51b09e1d3efa43400.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/e4/ff/e4ff04b777f99172b52cc91be987b960bad968fbe4dcdf6d6f893a962707e1f2.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/06/89/0689bccdc96fa61155afaf001f1a821f5f6781695c6799c3fc49a70bcf101947.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/d5/8e/d58e9a948e0d9175fc9237dd7e2fb1cb1b0c60c21135e7005044be0d9d3ada6b.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/76/96/769635a546bc5c0338a29bd08ca1f77c4b0a6c74e82c64fa3d2b9f474922f654.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/5e/d2/5ed202ace5a451041fee4f6ec6ce427ec0822b3433623c8db467f48d9542f7f6.webp"
          }
        ]
      },
      {
        "alt": "Seminars — ros and deep learning 2018 — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZwAAW9P9hSKMWDqPq5gAAP5bfFuooUHI4UvzP7AWWGy0Fw4uE0CEJP48NjFZmHLMU2WRL/u9FheoqX1elxD3QAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/0c/bf/0cbfb32484c95b68ba651ba825621b13c9b836f85b057aa1a4f105cc8fa09fb3.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/39/33/39337ae227792941f424dccd1998d481c7ab5b924d9ee355a57567f050aa7ac9.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/4e/98/4e98eaa1824fcf7e6b1a619d2e3b4a97049d2058837266cd3ff21374c14be680.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/04/c8/04c84bca977b8e775bdccce5dc02f01f575b3990c52643d1da59de575c689859.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/87/a9/87a92c872a9793a03c86ff4ee47857925e8c9475218d7f50397a986723f3cb01.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/16/52/1652e0edb342f08a982a053b2eeb4555623763e0c4db8d6b91a87c59baa4da1f.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/df/54/df5454224667b70d3ab9760258a269aa0b818eadf5b7d58c23e624d0e00f6328.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/ec/b8/ecb8a53ecaefd6b5c5f1c26c5d1fb1190134812ecc764a9af147bf6f14472c8c.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/0a/00/0a00bef5ddd4616c0399723b80b2e3a6c6bbc6b43a83e9b82e12d2a966028e20.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/52/9f/529f4598f80196e145f411f1bb6b2322c1f20f10fbd27c296a6d9ffd1513bace.webp"
          }
        ]
      },
      {
        "alt": "Seminars — ros and deep learning 2018 — BUET Robotics Society archive",
        "width": 960,
        "height": 540,
        "lqip": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZgCdMoR3ACkmOLBzYCAA/rxRimHFOL4gWxmWAiGrtbI3JMPOSyN/QEsrs86QCaoAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/26/d5/26d552dd02c38318299e671fb2ea9055e8e159fab80187dd4de66593d3fb25e8.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/f3/7a/f37af244ef1c38be6f2b54f75d8f29686220652add755e05fc1496dd600e0851.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/60/39/603959c32f83b6e9499e7a2a6334a00dda2159fbbe83e426ef3809cbc5f032fd.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/8a/63/8a635617141aaddbe7aef0009efba69bfd894ffb5191a38e1727c9d64eaa62fd.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/76/2f/762f0dea0d36576a291ff9fe591f0b229ca37d94f2384f6277c35dfc3f3141ec.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/f1/a4/f1a436aa144f96a87820f1a4c3ef9e3ece272c2f91435b4f41073ff5e86a6bb9.webp"
          }
        ]
      }
    ]
  };
