/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/seminars-seminar-on-iot-big-data-and-m2m-2016
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "seminars-seminar-on-iot-big-data-and-m2m-2016",
    "title": "Seminars — Seminar on IoT, Big Data and M2M 2016",
    "category": "seminar",
    "edition": "Seminar on IoT, Big Data and M2M 2016",
    "year": null,
    "categoryName": "Seminar",
    "copySource": "derived",
    "html": "<p>As a part of RoboCarnival 2016, we will be hosting a Seminar at the Central Auditorium, BUET on the 29th of November, after the opening ceremony at 6:30 PM. The Topic: Internet of Things (IoT), Big Data and M2M The Speaker: Dr. Reduan Hasan Khan is a Technopreneur, specializing in Mobile Wireless Networks, Enterprise Software Development and Internet of Things (IoT) Solutions. A BUET alumni from the Department of EEE, Dr.Reduan went on to do his Ph.D from the University of Newcastle, Australia, specializing in Smart Grid and M2M Communication, will presenting a seminar on Internet of Things, Big Data and M2M. He is currently a Deputy General Manager at Grameenphone as well as the Head of the CS Core department. He is also the Founder and Managing director of Aus-Bangla Communications Ltd. , an IT-services company, specializing in IT Outsourcing, Cloud-based Software-as-a-Service (SaaS) solutions and IoT/M2M Solutions.</p>",
    "plain": "As a part of RoboCarnival 2016, we will be hosting a Seminar at the Central Auditorium, BUET on the 29th of November, after the opening ceremony at 6:30 PM. The Topic: Internet of Things (IoT), Big Data and M2M The Speaker: Dr. Reduan Hasan Khan is a Technopreneur, specializing in Mobile Wireless Networks, Enterprise Software Development and Internet of Things (IoT) Solutions. A BUET alumni from the Department of EEE, Dr.Reduan went on to do his Ph.D from the University of Newcastle, Australia, specializing in Smart Grid and M2M Communication, will presenting a seminar on Internet of Things, Big Data and M2M. He is currently a Deputy General Manager at Grameenphone as well as the Head of the CS Core department. He is also the Founder and Managing director of Aus-Bangla Communications Ltd. , an IT-services company, specializing in IT Outsourcing, Cloud-based Software-as-a-Service (SaaS) solutions and IoT/M2M Solutions.",
    "cover": {
      "alt": "Seminars — Seminar on IoT, Big Data and M2M 2016 — BUET Robotics Society archive",
      "width": 526,
      "height": 597,
      "lqip": "data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAAAQBQCdASoUABcAPzmSvFgvKiWjqAqp4CcJQBj+v/wD0PbCZakcqUErj0QX6Ou5Sg8oAP68SeNpJROrzP/Z51W7ovltMXK3iAoATgoon4hM1iJwhXMqMH0ZCJOB9P6fYZ4siQYPF+zNbuwhkRQQFTQHK2K5QI3Aax5T15FYOwgxu27VMrpQ/95AEEARKAEFNiwn+i/R+VP/qYoN7AAAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/76/6c/766c2964710bb5f01dc6cae7f9404e1787d512a2d5c8df28ce4dedd73fcb9700.avif"
        },
        {
          "w": 526,
          "url": "http://localhost:9000/brs-assets/sha256/da/60/da6084aae628f5a25a0dd37c65b2abb5c6e22e28592e46ad703122636a320f34.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/b6/47/b647738eaee83e3d1287e34808e6f2c84fe0aa3fe19a1e7f23071c65ec7d432a.webp"
        },
        {
          "w": 526,
          "url": "http://localhost:9000/brs-assets/sha256/85/fe/85fe934575a148b48644d5dab8c1309d5be4b12c88c27beb264b9652f07e0b6e.webp"
        }
      ]
    },
    "gallery": []
  };
