/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-basic-image-processing-with-open-cv
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-basic-image-processing-with-open-cv",
    "title": "Workshop: Basic Image Processing with OpenCV",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "basic image processing with open cv",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society organized an engaging workshop on Basic Image Processing with OpenCV, where participants explored fundamental techniques in digital image manipulation. The session provided insights into how image processing bridges the gap between human vision and digital imaging devices.</p>\n<p>Workshop Highlights: 🔹 Introduction to Python &amp; OpenCV 🔹 Image Transformation (Rotation, Scaling, Zooming, Skewing) 🔹 Image Manipulation (Thresholding, Denoising) 🔹 Color &amp; Shape Detection 🔹 Optical Character Recognition (OCR) 🔹 Object Tracking &amp; Detection using CNN</p>\n<p>Instructor: Shahruk Hossain (EEE ’13) Head of Design, BUET Robotics Society</p>\n<p>Event Details: 📅 Date: 6th May, Sunday ⏰ Time: 5:00 PM 📍 Venue: Room No. 535, ECE</p>\n<p>The workshop was exclusively for BUET students, and seats were limited. Participants gained hands-on experience and valuable insights into the world of image processing.</p>",
    "plain": "BUET Robotics Society organized an engaging workshop on Basic Image Processing with OpenCV, where participants explored fundamental techniques in digital image manipulation. The session provided insights into how image processing bridges the gap between human vision and digital imaging devices. Workshop Highlights: 🔹 Introduction to Python & OpenCV 🔹 Image Transformation (Rotation, Scaling, Zooming, Skewing) 🔹 Image Manipulation (Thresholding, Denoising) 🔹 Color & Shape Detection 🔹 Optical Character Recognition (OCR) 🔹 Object Tracking & Detection using CNN Instructor: Shahruk Hossain (EEE ’13) Head of Design, BUET Robotics Society Event Details: 📅 Date: 6th May, Sunday ⏰ Time: 5:00 PM 📍 Venue: Room No. 535, ECE The workshop was exclusively for BUET students, and seats were limited. Participants gained hands-on experience and valuable insights into the world of image processing.",
    "cover": {
      "alt": "Workshop: Basic Image Processing with OpenCV — BUET Robotics Society archive",
      "width": 960,
      "height": 540,
      "lqip": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAACQAwCdASoUAAsAPzmGulQvKSWjMAgB4CcJZwAAUoNrwJ6NzrhgAPxw35d+mYOJ4lgLsX6u5Y+p8T8dOD0DgJcZOTk1BnAA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/90/5f/905f426432472a7c405577690f99fb3c808475be66e29c4b3992a8875b16a375.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/89/64/896476b2b1f1c2a64d7bf55086ffb3e5db2febbdf8ed9692e6ab6755d36b4d76.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/ea/53/ea53c928e961059e2e7ea4329337cbd46e6ee247b6bc4fe79875e93faba14c00.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/e2/65/e265274c11755b2bab77a6ec09964d00a65b3a43ef523bd24fe5cd482e6df41f.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/69/76/6976c13fe1366449d0d152c96c6c738d59e58d6defc48751014a4b090e345d6b.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/44/a7/44a76b6434927329b5acbec3388531910b8b717692fa34ad114667e6558d4dd9.webp"
        }
      ]
    },
    "gallery": []
  };
