/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-v3-0
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-v3-0",
    "title": "Basic Workshop V3.0 by BUET Robotics Society",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "v3.0",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society organized their signature event for freshers, 'Basic Workshop V3.0', a 3-day workshop consisting of 6 sessions aimed at giving a kickstart to robotics enthusiasts.</p>\n<p>Workshop Overview: The sessions covered:</p>\n<p>Introduction to Arduino Sensor and motor integration Algorithms and structures for building robots Line follower robot design Expert suggestions on robotics Mentor allocation</p>\n<p>Eligibility: The workshop was open to new students from the 17th batch and students from the 16th batch.</p>\n<p>This workshop was exclusive to BUET students, offering them an opportunity to dive into the exciting world of robotics.</p>",
    "plain": "BUET Robotics Society organized their signature event for freshers, 'Basic Workshop V3.0', a 3-day workshop consisting of 6 sessions aimed at giving a kickstart to robotics enthusiasts. Workshop Overview: The sessions covered: Introduction to Arduino Sensor and motor integration Algorithms and structures for building robots Line follower robot design Expert suggestions on robotics Mentor allocation Eligibility: The workshop was open to new students from the 17th batch and students from the 16th batch. This workshop was exclusive to BUET students, offering them an opportunity to dive into the exciting world of robotics.",
    "cover": {
      "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
      "width": 960,
      "height": 540,
      "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJZACdMoACbfQhYrSbUOAA/rnnPhD29kv67Y53yly83X401bHOkgEn0qNl3naqfbLyx8DmI7MnN6AA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/cd/6d/cd6d61c04d55f0407a78aa942cd1e006fb40001af8145890290728e5992566af.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/15/7f/157fa48e8e684f0fc6cf7825d6c260a4c5c140e5c76a53dda80232e5d49cd675.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/59/8d/598dd0141139d57c193f456f7ee5e85187878cfbafb5992497e9ec9bb8951100.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/7a/de/7ade18d718ddc4c72eb12786e5393db7fdc1c3706e85b066db022ae4bc75109c.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/c4/a4/c4a49477309ff789d9c1c95cf1e29213fef16e573e96dab77239d26a78100bd6.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/10/92/10920f8394052123499ea54cef847eeec2813e5f6fead64df70c85c7e28cfc97.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJYwDCgBZ43s+pNdTQqZAA+m+hxptKUNOM0ICDTyv5wh43GZQWLKcQ5M3MjxzTnTfZy6v7Ps9IhqfJ3KcIyiRYcAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/e2/0f/e20fc7b9e8961c35540cb4e9a282c3671474c4e81350a5b41c8bf3f7c13bef4c.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/02/2b/022bf846394bf64ac2f0606bcdef9a3bcde2d3ec36cd489c562d8e5b72434e3e.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/c1/ea/c1ea80ab4700f07d986170ada6f6e0e3ae475cfcdf5f0596a2bf2d4f9b4f60b8.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/6f/c2/6fc2f26df23cf9f78b63c2617757404d6c8c7591aa3d691fa01ae5dfb9d3e09c.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/19/65/1965ff152a4e03f8a9a043129058723ec61083a5cb5fb2c139acf4be49db6235.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/6d/2e/6d2e63c6c0b95e998c831a5ea0dddb3959835f2e09f4dcd836064932cef49809.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/b2/90/b290a95ca9d91a7cf86ca1b1703a7426f7ddc4a508380d1a8b6bf9d000da68cd.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/7d/3a/7d3a0c9af5c30f8c6b1548c33f7e5b92cb3926609e180a8e70ab088729ac3fa2.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/f6/b4/f6b43758f06aaa9d08086998e68d2fc316bc199cabbb1a18f29f400e688e0114.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/5c/1f/5c1f0a756bf3920ad914cf553a00a73574376bd978793a3e695b3c0517ee0346.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJQBjegw0qGrdCDuAAAP36O8ql0Ihxzduy5wDemKdGP8uVGb3Dplpqn7zL43h4UOk/PQTssJ8RzXjgtxDiQgAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/6a/58/6a58e3c2a7610e71124e152dde3d59dab071c915f6f1b1bbfd05be3f7b2dc38c.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/7d/59/7d59bdaba262fdb57f3f14db759dd3d28fbbb0f931215b06214c30b4d06b59e5.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/1e/4e/1e4e89534d8b8404b6e060d767c8ccf588cfebbca41d5d5986ff6d170ff6a7a7.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/07/2c/072c232bf131173111cc8b5113af268390dd3fadda65259e00517ce240dea828.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/05/df/05df5496f493f26676594451ac4c28161524f8af570d45e90e7257484ff47e73.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/ba/94/ba94898906d3808eea761606f88c5dfd827089423a53b43f6a7ff05fcb1602c3.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/4e/57/4e574c02866d57331a5e6a7c76549752b1f6576b71d2c82e6ede4220e75fcd82.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/c3/d6/c3d6c708ac05bc9c74ea69fe914a26ea9356132bb1055168ae8f76d4910d3e15.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/14/34/1434974b8d071d9196eabada54074a1cee2c002d2a4bdf969fe13989e0d46b77.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/ac/a7/aca722df398c630bd5d9e2ed1327dfd34ef19467d05c12f9044d8fa1f9b1be01.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZQAAXjNvN4x/K62JxaYAAPfTrfHSF+gsNR0UCgRe5LeTNcO3xq/EN4tkpSeiSuNNRq+o+h3nYw91Hv6FRMf/Q3gTLAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/09/cd/09cdf422b2970862e85e5de1a7c8db34d53fdbe81f2fbc2b05543b0872c51057.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c4/b1/c4b1e797541292b47f77d7a4b2d10a793184f0d040bb0d0061cd8eaa2afc94a6.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/dd/d8/ddd850a3379ceffbde307c940be4e6160316960e41954f0aae16acefecbe2eae.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/6c/13/6c13cb9ebb53dc350ec5314982585b9f2cf7f6e4437e75adbbb920d04510474e.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/f2/0c/f20c72e1c203f59e4902650c41b9db7ccdafcf463c4b3a86922c06c5c3af95a8.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/58/2f/582f3759b1e84e1d7c17bc192ca3fd566e769c59ab4e43a67cc645e7cfd4a50a.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c8/f1/c8f101fdef5ddd088a3fdbc9e2005aaf2d6e8d29e9cd5e04389334ea8f3e7f8d.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/c1/7f/c17f21fccaa1c1f5f6b12288b5780a99aae5dfa0e3a0e257398247a8afca6f4b.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/d6/3d/d63d5a92e1a8d25483d0584920f90852bfff587f3ed40498931ab6ae1d1f648d.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/b3/6f/b36fb7fe5a2e728a596fb17a2fddf2aeaed92f06b6fb57b31fec045946e272dd.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoUAA0APzmGulOvKKWisAgB4CcJZwAAUYKDIDHU5PB0YoAA/sNtFftA/y0Bij28Vq+94V9fsCdyv6YGUL+3w1hyanaEdTdMvAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/88/a3/88a38ef94059371666266b3afec388ef4e00ddfc609ae09dfae2b10143b4e8bf.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/2c/a3/2ca348a0a355cecf91d66f063691fadbdc97856890ed4f2cc9e01bda30248a6c.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/15/a1/15a10118fb56d5837d93c6c1606f9057d8f554294a58fb7ac3d0dca2bbc7a763.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/89/f0/89f0a5419bf93f867102c360563741afb3cff6660335f459b4ed7a5a6b24cfb3.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/b1/0d/b10d7b96e113cd01e404820fb8378aac0762ef292a76ff2dff60e94d0c3adbf7.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/f9/ae/f9aedf663b279655f0aa68ea444d02bfabdb01b63a4b41cf2f2c601104abdaa1.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/7d/45/7d45de432e84e5dcfb19ae8ec328f66eb8b0098dd8884e13d5797a3158d6f7d1.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/64/d8/64d86c2999108c822f9464c7e52930ea0d393982fe7fd116f9ca6f0dcb443fb0.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/87/ac/87acbefb9a98668c22c0c7903e22e38a159db72323830711e2eb2e536f015787.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/de/a7/dea723d14aa8df653f4f50f7503ea5e54015aef78ca7ffbd53aa412dbdf6eebd.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAABwAwCdASoUAA0APzmGulQvKSWjMAgB4CcJZwAAMvNNvbxOcwAA/tPk0j0dTcAntVTRrerW41e26DHmy4CHs6COsZlLnodljxoIp3K/FxMGfofNH8RDhJMiRdI4iAHqUCAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/5e/e4/5ee4f0096c0bf2b5df9df87392d0017ed3e1e6270f934dbbdfa885b9849917de.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/6f/73/6f7307c1b9e4b22c63698bc81f181be3fe6c09c59adf5aa42acdc7a5501d4089.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/f0/4a/f04a0223458d31aa5e403281a7795bbf854ad82e45ed375b65b5aa0dfe8d6053.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/c1/98/c1980bfc4be61445af6d6b1f431b86b6f525f7397b00f20f18bc656e8bf47969.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/64/30/64305f761edde209a15b12132943443d06d5677f405e50e38adffea3a6c492b8.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/07/6a/076ab78b533b903b48be6fceb3004c79d3dce4e2d9b79db9431b7e05e7c6e39c.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ce/66/ce66434bc284213ea8085e63df3b4fb3149c8cce3059ca0d0ff147cfb23a9364.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/27/dd/27dd58d895a515b367ecce270a3e92cd63ada21ebea19cd6a2b530e16a713118.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/9b/85/9b852933806d8c768ef7a8bb668664aa2411864d3f225888ae7a9ef4b21c7172.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/23/06/23066c0c1b9a350f6dcdbc78ca6f4037c0490562e945aff08eb97432d6e45633.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZQAAQxa9YLEX9jnJ/ADMeol0rEoFQQ4UN/gGHUmjiPK6oHBMnjPiZK+DguTt9avZg8esPPl4AA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/42/2f/422f7aa125b330ef122e2bb4198215dc8abcbb9f2f3405c406cdf1e909489cbd.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/b2/8a/b28a7fbf29dd0ae73887ed50cb214674fd4183499581e14c24d4b17a697d8b4d.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/82/24/82249c1b672582ec72d68286c69cea665275d0b9c35a4989071126dcd601fbd8.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/98/39/9839c1e4cb021278a2360e09d2f7eb061253ff5973b60bf596984249fbfde9c4.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/0d/71/0d7180596ccb4f4ab48817444d57f796dd112a7e0514f66b173ac7a476a95995.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/48/5e/485e26a2966713ef12d0ed2776f203d73ee8347fcc17889bb2a1b76ea74774c5.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/00/a8/00a8d66d5cec0b2788b9c42fae26403dadf0a6bc6a94f78c3afb7f9dc41a0476.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/2b/a2/2ba2598c2c720f14b03c69ef1399a127c73936fff159af8e7aec078311e01902.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e5/d1/e5d1f8e837d4d62dbc4b092da326adeaa803287f3b6f9fcb173fcfae10000f88.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/b6/d6/b6d6e51cd46e1dee9e7d92ee09bfedb0959e9c494afb8e43c8cc6714cda6d96f.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAADQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZQAAUUaZNjPbEKR8O5gA97ChgP45zi2M3JxgNkxZe1evk3/GnAyehONPnDoDM7KJAYDcYqpx6tsRmlfd3EzY9x4xbmAujXTTtvgwef4jmMuSwo7P27ZUVEAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/74/56/7456a347d792a826f03747f640d101e96a8892e70670d8dd26404ff7bb7e7a85.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/4a/38/4a3894231adefe5dd6ca9da3dcf00aa8d8723614c135f6a49488aa51fa570769.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/6b/9b/6b9be38b4003bae222529edb513d90459943064a4d994982b41ce9664c96c7db.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/fc/47/fc47c58152e6f4f09a6cff228a6f121910b825485fec85a2043661d2acbc038e.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/35/c5/35c5c1a0fba5c021e2bd2df2f0648a164008b112ebe97979ec6ee780640bf9ef.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/51/63/51631ca0484791fb8efd8992bb5627043180cae2d07506dbbb5f6043ff7bd142.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/12/dd/12dd7fd6720a6d1e4793f312d6b4aa42033f584f407ab45f9cd96006a429141d.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/a4/e3/a4e3f2a3463ea04f532b68088b3bbb1c299ff3ff6bab56b6d4752797e4c4b1e8.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/05/40/0540ae0a46ebf74baf79711541c226b3dacb7657f335de1dd87f5828c3ebe67d.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/7a/0f/7a0f908d93e37b7c61fb7bc8a6d0c37c8b78216c21c5a8a3c4d60f36e147b343.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJaQAAS9rPCOlVtmdAAP6NEc1RhqGuRL/pgdvvvpPT626/WOd4yehTq+j4k+dSmLsPdQmwXhQAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/39/50/39505892e6211140fc8f80be6e463efe3d69e61257452909579f8e32d5e5532b.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/51/08/5108229c5c67167bb2c76375cb9c87e741d815de7e95eb573f3bfbabbfd0052e.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/f8/2f/f82f4b0dd6faf84d2445f55bdf14943d671f36008beb7d3bb36347fe3068a517.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/bf/7e/bf7e24ef3bdcbb5363887b88cb5eac2db036a406d33b64f6e91ae970095c9c2c.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/b6/74/b6748dc535ec7a4face3f903154b887e2abdb289913ba0631a3d758892cf2ca6.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/a1/7c/a17c8c14fa42e51e1496f1dea1c45ffd49149e66ff37290db82edcb599784c65.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/18/ca/18ca4a2a11ebe24d437a99b63382fad877459ede339c1e678c51c72a48c3abd7.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/4d/58/4d58efe40f889896aed6792a45a97081679d7e458ad93e39804813098b7fd114.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/f3/fc/f3fcfc95b0b0856a17ef4af2f3101e786780f5531d615452e720575ff1b082b9.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/f1/ce/f1ce498712447214a8df56e58c52ffc868c925f56ded1184777bae800088479e.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZQAANx9QWXdMA+DAAMls5kWFrCBjAjZ1HU5evVfbaXsq69NrxtesXw7TenO7nHsb2pjbRW6cgmBBwusMDw2I8soGtbSgd/RylBG5+gAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/72/75/7275363681102e99dc96e90ecd198bfed11cf833301d01555463957deba7ce91.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/99/ef/99efe36c3265a4158970268e4a0cdcc8abdeaf52d64f0d17ff55ae410ca50bc0.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/38/d0/38d0a06bb640d3ff22c82105bbf5d0259edb92fed9d94d1c6dc873f6f7c67ab4.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/51/d5/51d598db597d01a456879b6d84f039eaf70a5f447b8683651a622fc147529810.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/99/86/9986d6db43ae0d31e23b2c78f25204e8fa81d0cc4748b96219c74a23f968fe0e.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/ad/74/ad74ea3d6729d5581832df173685819b27ef02ada4aba3d1219cc1ee55608462.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/35/9e/359e2863836d31a0c6c0ef0f46ebabad95fb89dcc5a0ead0b6158fd16daa1d46.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/da/db/dadbf664c7c291c94081b513d15dfe71f7a1e258a741c0126518ebf7cff1ac40.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/64/8c/648c6344e2c558d87c21d7bce3f910f811d81a9cb25c63006eaa6666974ca0bf.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/60/16/601601396e574624e359feee1ee000ec9f0baf36f41bb2cb16ca98faeca200bc.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZQAAYb5w1P4AwjPDBAAA/eGygWfhS1RMOlrSpHhm99n6P7e/eim0sbS9X7njxwJ+9TNn/xFcvJ8nnfUlyD/YYhS0mK7gn33ZCgAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/e8/0e/e80e3005b3368d8a0735aa4d8e0124120191491e1a4c5cd63c10e3a4f3483f4e.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c2/b9/c2b99521112646dfa343a2a19422a00762e5423961997aeb332a46a1c484be56.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/d9/71/d9719d6d0ad4533b2927de201418bcf7d2599a1156a75b721e25f4905d17ed3d.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/59/cd/59cd95ce76020aa130ff5db3bb450922b17e04e20479530396881b695e3e6d05.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/74/4e/744e7223106c3dcb828d6e2c668cdf914fd225bc87129a44638d314ed0ddec4f.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/ef/27/ef2718d73051bf0acd8d077c22bed39794e114a643bc01fb6833b5f0bca4850e.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/28/8a/288a7ad033956fd2db5abcc991a6f783942eb087be5c9db3bec897b1e4d545ba.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/55/bf/55bf62452c6b4659de36373b7defb0b6ac1bb8bb80ff9cf1175f706a655ba386.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/5f/25/5f2528a1249fc498274468a6be59e87e685d118f8dcb342f8e0da67943b779a3.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/13/4b/134b1c63490c0065d0a42ca29ec445a87cb2dd966995fa3572887602ecee2672.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoUAA0APzmGu1OvKSYisAgB4CcJQAALewcxu7B6r1BUSEAA/ouYXKZeVvDt+gEmlGBkol8u0cUbbWmls44+l3ovaTRlBoMiX8UT9VPeDs2IbVyOcdhRYAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/99/2e/992e2da3e7d1f3c1018ae071e7d30f3758dabcf9b85e4754d0912d1c84edbbd9.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/92/7c/927c723c58c021e88f918ae040e5b697f9fefde5b6ce8078970ff31691719670.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/59/e5/59e52f52ad4c51aefc7457983796b7f3665314e60fdd0a828e25191ed32998e5.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/17/6e/176e53b0fe64f47319c1d76e6cc4faba6d61341908c9bea12e1a84ed57737337.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/ea/30/ea30f8cf60731dcbbf24905e6f45af128d4be84c6dd606643febaeab5afe8189.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/7a/6e/7a6e480b864331f96ee8f34ea08a21137eda763fffd15333debf15a7b6b33e76.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/4d/42/4d4276a1f2f6884a580b3b8d249f37617801566cf80c553630009650ef9162aa.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/5d/d4/5dd40e61faf8afefa8f1b504d3a1946f97d0068b498093a90670ace9b00e821b.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e0/66/e066fb0317461c3189ce431959fe7626a83335b41b6b8fd3f507ca85a83fa43b.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/a9/b3/a9b3914af99edaf4f0e947c22f519298f0293d6e43d5a9e73743bf8d7a194d9b.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAADQAwCdASoUAA0APzmGulOvKSWisAgB4CcJZwDMHBuka9F8e2I0MAAA/uNLUeDIuqBPFmhJaYvdADxgux8fYeobVYunmHv7VOvMRJRIX+TiwAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/0a/1f/0a1fd6f9b0c334a5d6501a8ae3b6e643c67a1b8fa9cf01af45b9ba044ef4fe2a.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/31/e8/31e8f5b51574f4955ab05b2867c35d01ac1b78a9d937de159be89c13889dcc4f.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/98/d0/98d05326b724463065deff347b4ee700b385e6549a0f014065ced14a90bc74fb.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e7/f9/e7f9067c2fefd0a1000018a4903494c6adfab7b1071dfb8005d4799173b2c365.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/74/c9/74c98678b9f3fbd243663784f3a45a54e2fe5499ab76e839ef5b65e0de0b13fb.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/a1/b6/a1b6aed9dac3dd02835047e04891b170791417a0d64b8d59e34a05676ca37807.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/84/2b/842b252cff51d058d017fd562112b766f408c8163340635bf85dcb2cd8a2ceed.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/71/70/71708a012058b1ef673e256c89e4379a500fae4caf72f9bb7180457ac090c3c9.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/82/36/823642c61bd822567a7307dea2433f4b46ed6e84a96043e196b42107eb188671.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/60/0a/600af21e20e01ac4db7dbf551616e9ddb96a6cea22f82edec4810924eb1cfd69.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAACQAwCdASoUAA0APzmGulOvKKWisAgB4CcJQAAG+F/YtiP9qJQAANRZP7rWxhEwzC1T3Ee4Oz5ytTlXQqeJ7NwZt1jLTF3nsj9bszdcVCsdej5MqqLdVCP/3UQE99sKP5tbR5+aPvLjJO8uIeRhMoOisQAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/22/6c/226c88fc2b046da66b2bd4f4a484991d03528231f8810d0856bcbd66b1906e49.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/98/e7/98e79339f83beba55047ee460bc0d13b23e58c821ff3884831c3a4465d2097d5.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/36/3f/363f5f68aefcbd9aea049bf61518fbd7fb8d2572fe86b09b87db47a3138b4d97.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/0d/8e/0d8e320dbf7928892d6b10fbd6e29adae0eedee499c3e8e818428880b5cbbb91.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/66/48/66482848f57ab9b4fae76fbe842f312cdecc9c14378a7275599a9eff50927f5b.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/69/35/69359de79dd9d204037030ea28d5e1e2c30d4ca7d5dcec840567d2398733edda.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/5c/17/5c17b1b125871d82d31d6584c117c9795bc168862594043aa7ab4777daf155d4.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/c2/64/c2645a3b79e1ee30f8e96a3c7a90f9ca17b5980fd53dde741fad3c515e127e5a.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ee/cb/eecb6abc0f71a1a662ed70ddcbea12a2bb048102724878b1e4a680f5e7f12fb4.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/04/cc/04cc555765cfeaf9b871a40039a799a244a5fe5b8a870fa779eb03930e3b0cf9.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2016,
        "height": 1512,
        "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAACwAwCdASoUAA8APzmEuVOvKKWisAgB4CcJaQAAVH34k2xlJJEsoAD+2mxnvYzoTjJOsPtK8fxO+9w011fPmRI1KpF5LR2N93kxO4F6D5GddE2DY1hWAAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/f4/01/f4019750916224c8fd483ff82318f0179f019d36449d58835d2839b3edbf71ac.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a4/d1/a4d174f4e5fd26275424ff49550467d3a243bedab34723bc7449b6a61c0f4756.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/67/a2/67a2f511683a8a83656c237a0f5d0e8354f4feb0816238ef9cf200a4bf7ab3e4.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/f3/62/f3629eff129f54a16b1fa2c7fe6f5cdbcc421d209757b588803fcf80a033ea9a.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/e4/36/e436c49098d9106a9f3eb41be510035bca2ea0a38fa5763ae34243700620ddc7.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/05/05/0505350fd49429ad22c1840af9b15f7511093fe537c8cd3ad486dde641957fa4.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/6a/4e/6a4e11ff39a6b329ab2689edc56d5e42462eba1a00c0853b7e992ef0c7079581.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/72/a3/72a32babd2852cd3b5e43870411a909056c443c029ee2ae0eea9b06aa1468b27.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/72/6e/726e796c14fc16efb8440d35f1e3de7a53dfbb684f47cc0954a7ae1b88db5967.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/f0/44/f04437b85673de11eea161d76736f7af8bd58797fcbfe0a78898dc93a080fa71.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJYwAAXuiO/gsa7C4AAP6yE042MNPdkuEf279Ft+mCfL2lIP0iUn4dzdkMkvHYT6XgO98xerSfVvAWkTLPH3dYK/76uF0OA9W/UE6AAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/63/01/6301506f119759c19fa0c7cdb1203827be23fefe4c10be215e9e856569025b48.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/06/28/0628c4c670b636bda19a90d25021b1046ce2341952bfe2681b24a0df265228e8.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/87/a8/87a856dd9b9d4c4c3a20cd98baaa46e3c1edd71df6ceba9536b9386380aec1ea.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/96/32/963242c4e6b4217546b13b1e23aedba29e3ae7d125acf3a56cbf5c48e2c77ac6.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/24/c5/24c54bf2f4374c89be4946c905467e077231283dbe41829b52c9391d7e22b034.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/8e/71/8e71b0a93c50bf22e8a5f191bcbf1942ea9fc525a96432c8c0a886c9333b1973.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/6c/6f/6c6fe2c780db8380b4200291021a0432440c2a1b8721a3b4a03b041875e552b0.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/c8/36/c8367cecd8fb6cb456f9671aea03257bee5e188a4c3dcbf81c763246b20aa8ff.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/cf/f8/cff809c6500f4d3bc5b77b9571e9d2a3fca9b02edc7b230bcd58169156e4baa4.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/19/20/1920fbcda9d9683a74f0111faa6ca8d05701164922d6f201123b49af62b8fc7c.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBACdASoUAA0APzmEuVOvKKWisAgB4CcJZQDKACHetF5T0SLv6guAwAD+xd5uxv7guGVOc8mCA851XeYYyQH5awRj7lngc1zHZY2mI9SZNOlmJqrNHVPh0uAwg8cMbb4mcMJGe+Gn2/skUgA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/95/ed/95edf0f624dee036951a70f00a3a2f29ea63c928b1965ed09cfbfeedc8ac379d.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/84/7d/847dcf5075f28c23b6c2874d3c6e8fe722df7cc36a13b384fa7e0b0c2101ecd5.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/0b/6c/0b6ca053e6e3f9dc38a07acd3e8334ee3d717040604b704be31b2e5ec4a3bdd7.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/05/54/0554d4c1f7f53f22e50793351193d172127f303dba33f2a0df46b958e1ad4727.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/bd/ad/bdad2299e56cf36033f65cfb57ae1f5b5b40561b05704ee37766f97df01164ed.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/67/40/6740bf9d9770b8f7bea4bbee4199b616be065d3f1b108595f4d0f6d6864b26bc.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/17/a7/17a7138c1929e9fc6c95df81ce09e729d6d1a08f11eb98720be3694a8461abf4.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/a6/5b/a65b171b717e19edd03856b50054272fba97e40013da658d7638200078bdcd3b.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/3e/a3/3ea3ebbd0a22652c9e018ec85e929949172e66fd1ab7ab15c80ae737946cf2d0.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/b3/38/b3380bebf92dd05941e7e68c7d04a98bb2094b251dc7f5f94db9c76a561b13ea.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2016,
        "height": 1512,
        "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACQAwCdASoUAA8APzmEuVOvKKWisAgB4CcJZQAAPpFGJm1sPNocANTBOLSjCu6cgYgBc6XXf9KUQJ1NLjPwWgRRWPFLVWnmp0WDWH4yjhqzxOdGuADcGkKHQYhUosqMgA1/sD4regAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/64/59/6459a86565e510589e44dda2d3e2c4cfab08613d23893262e3efb188f44d1445.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/16/40/1640f6514dd2710ab369213c0ea397c8e8db9bcb38d04c48091d655f4f0d18e3.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/f3/b0/f3b08ba76f31cfe5554ddcb7371af4ae51ab2339eb99c9f50eb70171294bd39b.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/8e/2c/8e2c95d802b57d3560348591d78cda9e41427b576622939e197623689c02928f.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/91/09/9109a056f49891df2f9aa5140afe0a5dd576f24a1101e2c4bc5f22a64412912d.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/bf/8f/bf8f1fcaab416651b2a8708c08476ac2a8ef326c749ca2dc7dfc6f3d60030c1b.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/9f/27/9f2776536d8357982db261f7701ffac299715fb56fd5892c3653cf60ac0dfd29.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/e9/2a/e92ac370e452f04ff58530b974788cec319c5ccd3b6e283586399d1d64d39f30.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/4a/5e/4a5e488bb5bcf2827df0c190ea368f227474eef25493dd750436426350b38878.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/0f/de/0fde9bed81ce786bde6d7f85b89515e358cb9382ed50aa6fe237f670da6890af.webp"
          }
        ]
      },
      {
        "alt": "Basic Workshop V3.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 1365,
        "height": 2048,
        "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwBACdASoUAB4APzmOwVcvKaejqAqp4CcJZwDH5DA5ge/BoYKBDnbBkW9Z7NPvgAAA/pCSCM6gRAEVSo+NhGsfaB8bjTMqsoNyzkuw0KzWq3EMusqajaqpAR+jQX86QqY52sMHH2JUjHRP4IDK7pF+k6DzHhSYmnzEZpVCONk6ERAS68oM7EEUBKgV4ihHtOIPVXm4Ggkkip184enRCKFnf8AAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/80/19/8019c1764a440519eb57ae43cd8a727ccab75b44f2cd3979fb6f456e2d0278ff.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/5a/de/5adecb3f377508794c4af09c683c60f7fc1ccc21b1a076728554e548ad0ac8c0.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/24/33/24337d36106d3d1efcb8629d195fbef2045109affd6587e0b66b2897e9189e9d.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/7b/ff/7bffba6b9a5b7585bca3827714f023b5d9cb24fda5485c67dc7ac14ea01fb2d5.avif"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/fe/0e/fe0e0e0332956c9611a0708f772b2676fccbdb9f4589d3dceab7202415b0b8d9.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/f6/6f/f66f95870e140db2e581f9471f7fe08ad704e3df164932d690399582f7c7862a.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/93/e3/93e3ca2462b79998d02ef34788e2061ee8f0843befabc4a435e6e05076517c72.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/e0/7a/e07abd1abce9918fa68871e1c6886c5bd36ae16703b752aee065ade3beac3894.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/f0/94/f094743e52418047b0c9d9b2e47f29edfa2f044d25c0eec65e7b3b9366c71f85.webp"
          },
          {
            "w": 1365,
            "url": "http://localhost:9000/brs-assets/sha256/c0/81/c08194fdb99e7f1c954b4255e7fe1f1914e98c081c414c64d6b79d0327121d15.webp"
          }
        ]
      }
    ]
  };
