/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-image-and-audio-processing-in-matlab
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-image-and-audio-processing-in-matlab",
    "title": "Workshop on Image and Audio Processing in MATLAB",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "image and audio processing in matlab",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society (BRS) hosted an online workshop on Image and Audio Processing in MATLAB, aimed at introducing young enthusiasts to these essential computational techniques. The workshop covered fundamental concepts and practical applications in robotics and automation.</p>\n<p>Workshop Highlights: 🔹 Fundamentals of Image Processing: Analysis, Enhancement, and Manipulation 🔹 Basics of Audio Signal Processing: Noise Removal and Signal Balancing 🔹 Practical Applications in Robotics &amp; Automation 🔹 Hands-on Problem-Solving Challenge</p>\n<p>Instructors: Shafin Bin Hamid (EEE, Final Year) – IEEE SP CUP 2020 &amp; VIP Cup 2020 Finalist</p>\n<p>Mir Sayeed Mohammad (EEE, Final Year) – IEEE VIP Cup Winner &amp; BRS Robo Carnival IAC Champion</p>\n<p>Alfaj Uddin Ahmed (BME, Final Year) – MATLAB Specialist in Biomedical Engineering</p>\n<p>Event Details: 📅 Date: April 23, 2021 ⏰ Time: 2:30 PM - 5:30 PM 💻 Platform: Zoom</p>\n<p>The session provided a comprehensive introduction to MATLAB-based image and audio processing, followed by an interactive challenge where participants applied their learning to solve real-world problems.</p>",
    "plain": "BUET Robotics Society (BRS) hosted an online workshop on Image and Audio Processing in MATLAB, aimed at introducing young enthusiasts to these essential computational techniques. The workshop covered fundamental concepts and practical applications in robotics and automation. Workshop Highlights: 🔹 Fundamentals of Image Processing: Analysis, Enhancement, and Manipulation 🔹 Basics of Audio Signal Processing: Noise Removal and Signal Balancing 🔹 Practical Applications in Robotics & Automation 🔹 Hands-on Problem-Solving Challenge Instructors: Shafin Bin Hamid (EEE, Final Year) – IEEE SP CUP 2020 & VIP Cup 2020 Finalist Mir Sayeed Mohammad (EEE, Final Year) – IEEE VIP Cup Winner & BRS Robo Carnival IAC Champion Alfaj Uddin Ahmed (BME, Final Year) – MATLAB Specialist in Biomedical Engineering Event Details: 📅 Date: April 23, 2021 ⏰ Time: 2:30 PM - 5:30 PM 💻 Platform: Zoom The session provided a comprehensive introduction to MATLAB-based image and audio processing, followed by an interactive challenge where participants applied their learning to solve real-world problems.",
    "cover": {
      "alt": "Workshop on Image and Audio Processing in MATLAB — BUET Robotics Society archive",
      "width": 1241,
      "height": 644,
      "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoUAAoAPzmEuVOvKKWisAgB4CcJbACdAB4H3AWyMEz/xsAA/nw19QMMP9GjbiMVWa8BfgEV1isGW2xUYGzMrdxYFWyFhMydInYxQShR4TmACTkAL6gTN/QA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/95/9c/959cd4db851ac937ae7088f2103d26d03b215387b16b1bce6c21abd06ce11173.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/84/26/842680d0b147a337e3ea648077b1874031a6cd2bffcdcd466b22ac7c72545db8.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/37/35/37354ba6a943878ab0e29a597d79aa3592b0258116d6d4060289fa9f0e00b80f.avif"
        },
        {
          "w": 1241,
          "url": "http://localhost:9000/brs-assets/sha256/af/5f/af5fd4538cd8fdd51ae4a83aec2bb3eac78b95108762086c3ca9e46317dbfad9.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/e3/3b/e33b2802f7fab5a2440d89d574269ed6b2db72e59e101861ea9c7411eb065f63.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/ab/8b/ab8b0e9a61e0e2ddbdfc28621a110e85193a5fb6926e4bbfbd344e4b71cd23ef.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/1c/46/1c46aee58522a6c293b0d3563a0758075faeca24e048d943557110c039151773.webp"
        },
        {
          "w": 1241,
          "url": "http://localhost:9000/brs-assets/sha256/42/7b/427bbbd248b8a5ddd6b15c5c5d278b81370a61c8f4ba86bc4279f20f535b4026.webp"
        }
      ]
    },
    "gallery": []
  };
