/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-machine-learning-mastery
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-machine-learning-mastery",
    "title": "Machine Learning Mastery: From Basics to Advanced Techniques",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "machine learning mastery",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society (BRS) hosted a seven-week-long Machine Learning workshop, designed to equip BUET students with practical knowledge in Machine Learning (ML), Neural Networks, and AI applications.</p>\n<p>Workshop Structure: 📌 Recorded Sessions: Available every Wednesday or Thursday on Microsoft Teams. 📌 Live Q&amp;A Sessions: Midweek discussions to address participants’ questions.</p>\n<p>Topics Covered: ✅ ML Basics &amp; Python: Arrays, Lists, DataFrames, and Scikit-Learn fundamentals. ✅ Regression: Trend prediction and pattern analysis. ✅ Image Classification: PyTorch, Neural Networks, and Computer Vision techniques. ✅ Segmentation: Advanced Unet and Autoencoder-based image segmentation. ✅ Speech &amp; Audio Processing: Text-to-Speech (TTS) applications. ✅ LAMA &amp; Stable Diffusion: Cutting-edge ML approaches.</p>\n<p>Event Details: 📅 Date: November 16 – December 28, 2023 (7 weeks) 💻 Platform: Microsoft Teams</p>\n<p>This exclusive BUET student workshop provided a hands-on approach to mastering ML applications, enabling participants to build practical solutions for real-world problems.</p>",
    "plain": "BUET Robotics Society (BRS) hosted a seven-week-long Machine Learning workshop, designed to equip BUET students with practical knowledge in Machine Learning (ML), Neural Networks, and AI applications. Workshop Structure: 📌 Recorded Sessions: Available every Wednesday or Thursday on Microsoft Teams. 📌 Live Q&A Sessions: Midweek discussions to address participants’ questions. Topics Covered: ✅ ML Basics & Python: Arrays, Lists, DataFrames, and Scikit-Learn fundamentals. ✅ Regression: Trend prediction and pattern analysis. ✅ Image Classification: PyTorch, Neural Networks, and Computer Vision techniques. ✅ Segmentation: Advanced Unet and Autoencoder-based image segmentation. ✅ Speech & Audio Processing: Text-to-Speech (TTS) applications. ✅ LAMA & Stable Diffusion: Cutting-edge ML approaches. Event Details: 📅 Date: November 16 – December 28, 2023 (7 weeks) 💻 Platform: Microsoft Teams This exclusive BUET student workshop provided a hands-on approach to mastering ML applications, enabling participants to build practical solutions for real-world problems.",
    "cover": {
      "alt": "Machine Learning Mastery: From Basics to Advanced Techniques — BUET Robotics Society archive",
      "width": 453,
      "height": 600,
      "lqip": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoUABsAPzmQuFWvKqU7MBgIA2AnCWIAtOgPSDqtQlS4Q6VmbsGAAP7jQeZ+z7KhXUZhkUiy0792FDjZ7TsIi18QKiKqMtkDaY08m528V61yAEqXOh/BgvgeiMJSY6oXdgQuGLXdBjzAfcFTM13iuDES5QMCxbIa2SCTvkOBaGKpJmmEWsgLFAAA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/3f/fd/3ffd0fe32ab91dc0e0b07f77e0e8168d59a9928ed3d4e0ccbdbd68ecb2ea09a4.avif"
        },
        {
          "w": 453,
          "url": "http://localhost:9000/brs-assets/sha256/0e/b0/0eb0f191bab1a5c7b7964761ff7702276afed70cfa58a2bf2e2f82b85195ccbf.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/c9/e9/c9e9ea07a36b56b5000a9e31003146d89979cabb6f8a5badc68340d921fc720d.webp"
        },
        {
          "w": 453,
          "url": "http://localhost:9000/brs-assets/sha256/16/1e/161e60063dd1f3e058415538b72f7bb0200701c610b1237ec57f57c68aaf3dbb.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "Machine Learning Mastery: From Basics to Advanced Techniques — BUET Robotics Society archive",
        "width": 1536,
        "height": 2048,
        "lqip": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACwBACdASoUABsAPzmEt1OvKCU8sAgDkCcJYgCdMyGC+/YyXsNz/DZn37HGH3bAAP7jQwyNWbfHxPG4j6ofagaxdu9p5nzlD5GvhZVbB6wQLm+ZTsDekK/lM25w1iziaUuVx3TsDF/5dqb9bKjmNLMM8MkNh85CfU0rK7HnnZoYAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/f8/11/f811997b07c19b3ce29ec04275362bc2adba8cc3e13206182d4c4412aa502ef3.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/aa/bf/aabffccf6351429c281800ebbc323e449a2d4f9bb319795e092a51bd9d01b521.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/86/47/864780f35339918f5c42d6597ef312673d935cd10045733a15bec3a6e50a5a49.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/c1/b8/c1b896435164195da56e6eb845ff2703ccaaba234dd073399ef81a46c3810f13.avif"
          },
          {
            "w": 1536,
            "url": "http://localhost:9000/brs-assets/sha256/b7/ee/b7ee158cb675caf5db78a3cbb958154a9862b3542d14ee57cb836784c7c2d5ab.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/7f/a8/7fa870bf350daacd80e5da0979d6527f533d9db81d1a96ded42aeefa64d3a87e.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ca/7c/ca7c8613b55670fb51331d40ef51a5d194d8b75f82362468925e8843ead84cf3.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/44/3c/443c256fa0acb7acaa2f8d1892c4781d3169c246913ee54b7a41907de9f2f8b9.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/4a/4f/4a4f539d79233028d410969c994e34cdb7eee3032d6a3d927a1508e6ce526922.webp"
          },
          {
            "w": 1536,
            "url": "http://localhost:9000/brs-assets/sha256/b5/5d/b55d30b45bd3d245b9bf2377ba9732ef818cb0877afb2270614d35861fcc00f5.webp"
          }
        ]
      },
      {
        "alt": "Machine Learning Mastery: From Basics to Advanced Techniques — BUET Robotics Society archive",
        "width": 960,
        "height": 597,
        "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwAwCdASoUAAwAPzmEuVOvKKWisAgB4CcJbAC7AA+LigD7hw68QAD+0O++cBMsLXp+77vDWc0oHT4ZmFQafh1okxMdUPl28ioe3W8NIV/SLdlvc1Xe5m/+rziAK7P/vYVQsr4tfIkR3oix7AA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/59/d3/59d36b561778ecaacb51817893c56a5676cc5ff3e8394a2d123d941cf203418b.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/60/1d/601d2360772cb4746b0b7330089ad656c152b1e44ea526a1d2b71fe47d691bf9.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/8f/30/8f30fc978a0e4472381f3f1fe57c728cc75cbcd237e4f08a88ae0c4730ce4135.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/ff/e6/ffe686fe058016c636689a48cc36a4a77ab4f49f917fb8436eb2a0d780d35ffd.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/e9/85/e98535443d4925c940af95cb7ab4865c43515aa7b1f7f5386d8ded4d0ea02785.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/95/85/95856422634ad5e46fa596b6682d1325b363077cfc16699579cbc27d602f5d6a.webp"
          }
        ]
      }
    ]
  };
