/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-v8-0
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-v8-0",
    "title": "Basic Workshop V8.0 by BUET Robotics Society",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "v8.0",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society presented 'Basic Workshop V8.0'! The workshop was held over four days, spread across two weeks, providing participants with a hands-on experience in the world of robotics. Here's what was covered:</p>\n<p>Workshop Schedule:</p>\n<p>Day 1: Basic Arduino Interfacing Day 2: Introduction to the Line Follower Bot (LFR) Day 3: Building the LFR and Implementing Basic Code Day 4: Advanced Code Development</p>\n<p>The first two topics were covered in the first week, followed by assignments on Google Classroom. Participants completed these tasks during the mid-break. The last two topics were covered in the second week after the break. Upon completing this workshop, participants became capable of participating in robotics competitions!</p>\n<p>Eligibility: Newcomers from batch 23 and students from batch 22 of BUET were encouraged to attend.</p>",
    "plain": "BUET Robotics Society presented 'Basic Workshop V8.0'! The workshop was held over four days, spread across two weeks, providing participants with a hands-on experience in the world of robotics. Here's what was covered: Workshop Schedule: Day 1: Basic Arduino Interfacing Day 2: Introduction to the Line Follower Bot (LFR) Day 3: Building the LFR and Implementing Basic Code Day 4: Advanced Code Development The first two topics were covered in the first week, followed by assignments on Google Classroom. Participants completed these tasks during the mid-break. The last two topics were covered in the second week after the break. Upon completing this workshop, participants became capable of participating in robotics competitions! Eligibility: Newcomers from batch 23 and students from batch 22 of BUET were encouraged to attend.",
    "cover": {
      "alt": "Basic Workshop V8.0 by BUET Robotics Society — BUET Robotics Society archive",
      "width": 1920,
      "height": 1080,
      "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJbAB3AANawyOBHm4nDAAA/rw5htSSHEwBt1sSqhzcH1Ue2B44Mnn12LjlRHPDOf87hJhEDO76SG/OtJ9EX8BdHVdifcqP0wX0vqRzBlBsP7iUU7rOb3g2errCPdAA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/53/e5/53e5730b2fc5c5a833ce15279b10934a9a9a937336981f586ecf9d1bef9528ef.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/b9/9c/b99cf4a558e6f4605b1d9cfd325efc0c036287e3250b11a45fc31d3169d5de4e.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/71/d7/71d775d2f135aea81ee117d3b8dbee68daedff6e3e5d5a298e6f0328293e8392.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/7c/15/7c1531f41892e3fbd71ee83606b0bffd99cd903cb3f0371be8a21e4e64d57b77.avif"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/d7/2f/d72f16f458b8a841da1e311a4f61219243f3d04fde2993786fcf23f745ee5dcb.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/80/02/8002466b548a76e2c659494d5df7b57d77b5ca07723a6a6f070c5466863c4106.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/cd/19/cd1994c5c0d3a6a17062cf2c848422a0992331f3a8ee8e1cdce96d691707489d.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/6a/d5/6ad5441bec58a8cdfcab592431ffd8718224cdc5c067ee3b0476b1c4c46bcfba.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/9a/97/9a970214eeb5424bfe445121d9756f0b0c4cf0b4787b2e7607036d10f25c5ccf.webp"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/f6/9e/f69e1798ba9b0814f953a0dce3473875682a54cf3ef7312bf6ee98ff1b25bb47.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "Basic Workshop V8.0 by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1536,
        "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACQAwCdASoUAA8APzmGulQvKSWjMAgB4CcJZQAAUoqaJ/tqzP7YAPxcgefw/bzaubEwaIGSBN2mAA77EqbrcFf6QzVZJDA4OIY4hYJRHGpUAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/1f/b2/1fb20fd78e48248e9c7210a2ccb568eac2b78f5c51e94f156f175b4dce732581.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/09/9e/099e9ca6a6482d09deedfdbe114d5e1924d026c03f072e99b2dc0347eb1d12f7.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/0f/25/0f258da41372d4b629a8f86636ad4e3a935dfb59a0b128fe7de03e366fb7d507.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/c8/c5/c8c53570b6e9dd27418c2298011cbc584d9f23286dc9fb9e7ea6b158b1dc0657.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/ca/40/ca408cb9c0fe5de728f61b5087ace12014019367e35db81ed96fcb6c21025517.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/32/16/3216a6c4db21521ef038387d92873f4261a922630786dc9533e769c015adae1f.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c7/c9/c7c9706be213c929d4c5af2a219dee79eedcb255a9848b3331b289f9e3139fec.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/99/ea/99ea163300e9d790996ac96a674375b58fef87910e3490c7c6eb1cd91f98aed8.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/26/0c/260cb6fd62788c8248cf3a871166e12a7dbbcf3b74febe06d81b1f4980e120d6.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/2a/0a/2a0a3cc102eb56cb7294b69146563573b1698204a9cbb323b34065543dd44535.webp"
          }
        ]
      }
    ]
  };
