/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-v1-0-2016
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-v1-0-2016",
    "title": "Basic Robotics Workshop by BUET Robotics Society",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "v1.0 - 2016",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society organized its first-ever basic robotics workshop, aimed at BUET students with some prior experience in robotics or those interested in robotics but lacking the opportunity to dive in.</p>\n<p>Workshop Details: The workshop was divided into two phases over four days:</p>\n<p>Phase 1 (May 13th and 26th): Focused on circuit building and programming, covering Arduino, sensor interfacing, and basic robotics algorithms.</p>\n<p>Phase 2 (May 19th and 20th): Focused on mechanical design, teaching Computer-Aided Design (SolidWorks) and mechanical structure fabrication.</p>\n<p>Eligibility: Only BUET Robotics Society members could register for the workshop.</p>",
    "plain": "BUET Robotics Society organized its first-ever basic robotics workshop, aimed at BUET students with some prior experience in robotics or those interested in robotics but lacking the opportunity to dive in. Workshop Details: The workshop was divided into two phases over four days: Phase 1 (May 13th and 26th): Focused on circuit building and programming, covering Arduino, sensor interfacing, and basic robotics algorithms. Phase 2 (May 19th and 20th): Focused on mechanical design, teaching Computer-Aided Design (SolidWorks) and mechanical structure fabrication. Eligibility: Only BUET Robotics Society members could register for the workshop.",
    "cover": {
      "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
      "width": 1702,
      "height": 630,
      "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAABwAwCdASoUAAcAPzmEuVOvKKWisAgB4CcJYgAAW5tCmeP6M4AA/nTNRipvprBeoc5uqqgXOT+gjnr8v+r7KG/PUcuMrJqhhRgl3TzHt5BVpgAA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/e9/94/e994280a1cb40e5ee828c660b1085d932400eac1b9ea8a85d0e38d94935497b6.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/85/8d/858d9b04bbb62cbb66a5a6c47840ffd8ee2f73ab0c4b7f7eb214a1e3a2d98ac4.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/90/07/9007145ee90e53e96ce97cb01a055006d5368acaa8e32f9ddac499991546c47f.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/e9/24/e924eccd89037125a88a07c24d107246c5e8b1640b7a1eeebd2ee5c83b716cbb.avif"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/2d/b8/2db8eb1a26a1a05e74a9e69cb446cec9a0421c3ae3f79036f40fd4a6056c76db.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/17/9f/179f0485e9edddc95acb98e8bac7f3af0b3305b9bdc749e96732f5e27fe5f58f.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/51/3c/513ccdd31fd7dc788d65ce2f6e619fd66ee5dae36f65f31d2d83d583b249f763.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/63/ac/63ac4525430e916528f0bac283343bdb8f5ed6c7523f5a26a6572b46c55492ce.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/e1/ee/e1eeb9783090f1c7d0387cfd7e9e3a7cd600fdb3392f3af7f7816fad0abf3349.webp"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/31/57/3157517cf9cdb9b053da8e28386c153dc3f572c0821184e7629e67f966915237.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 960,
        "height": 720,
        "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACwAwCdASoUAA8APzmGulOvKKWisAgB4CcJZQAAKbXINNsuQnmFAAD9RANdutrSfqza3FRj9aPmpjioN7ts6DFAU/KL6FV1nPg9/HMGABtzqRcJn5W21wXWJWKsOhQAAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/a1/40/a140f8d0f29c39d998011fa528006fd0d2d5ec265d5f96ee28534eaa46e0662d.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/03/47/034781fa778dd77de238b4dc3047b3c9279e5510ccc9b205793c8a33e77d9c6b.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/0e/7f/0e7fe8ddfa3cf919f65d8387e4c7468e13daf2ab19662838a5da16456cd832f8.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/e0/62/e0620815f433b709aa69e088cacb9847a11f4ae0af28b537d5524c84dca0bff6.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/1e/fa/1efa343744f7677064b0a68db2f3ed1c93d74fbeb91d5cac11f03a0bfcb80abc.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/44/79/4479341e3871324e9d0ab61df399ff557a6c61524b2aaf00cad6f4956357eb16.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 960,
        "height": 720,
        "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADQAwCdASoUAA8APzmEuVOvKKWisAgB4CcJYwC/OCEj+E3H6bTMvYAAyzJm2+pjoVCPq50EA60G6HbALyujQhQU5GpP9rZ7+jD5CKngn4YzSq/RnsmrKmk5hCY3wG7X+05ySFdlm/UdM6cJG8cCngAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/59/58/59587a4ae6dddde7d45e442e1550b57aa3527d75066098120c29297576eff17f.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/bc/d6/bcd6393b07522188ff4225c4d38b5843c49e8ad9c71a5b1b113ab3ba39f96d85.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/30/6e/306e22ce137973ac97a4366c05612519bfdbc401a4aeb798eff223b28a1e7585.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/92/ee/92ee8f1c4944e0838e00dca9d59923a87f793ed91cb3364bc59499efe85d111c.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/2a/88/2a88f488867f26e598efce2b5069cf13ba6a5e020250454070d64950c60fb9c4.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/32/05/3205bec5a31349477559a6ae03ae4a7f6a8cd3c221ca0e5577d3061770165739.webp"
          }
        ]
      }
    ]
  };
