/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-pcb-21
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-pcb-21",
    "title": "A Beginner's Guide to PCB Designing",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "pcb_21",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society (BRS) and Engineers Hub proudly presented a joint workshop, 'A Beginner's Guide to PCB Designing', aimed at introducing students to the world of Printed Circuit Boards (PCBs). This workshop explored the essentials of PCB design, which are vital in connecting electrical and electronic components on a single board.</p>\n<p>The workshop was divided into two engaging online sessions and utilized the Proteus Design Suite for a hands-on learning experience. Participants had the chance to design a PCB from scratch, guided by the instructor's expertise.</p>\n<p>Workshop Highlights:</p>\n<p>Introduction to PCB design and its applications. Practical sessions on circuit design and schematic development using Proteus. Participants got to work on designing a 555 timer IC simulation. Step-by-step guidance on placing components, routing, modifying routes, and exporting designs.</p>\n<p>A PCB Design Challenge was held, where participants could submit their designs within 24 hours for a chance to win the Best Design certificate and a special prize.</p>\n<p>Instructor Bio: Mir Sayeed Mohammad, a final-year undergraduate student in the Department of EEE at BUET, led the workshop. A robotics enthusiast with a passion for both hardware and software, Mir Sayeed is a former winner of the IEEE VIP Cup and BRS Robo Carnival's 'Industrial Automation Challenge.' He is currently serving as the Assistant General Secretary of BUET Robotics Society.</p>\n<p>Event Details:</p>\n<p>Date: March 25, 2021 Time: 7:00 PM – 9:00 PM Platform: Google Meet (Link provided via email)</p>\n<p>This workshop was an excellent opportunity for participants to learn PCB designing from scratch and enhance their technical skills in electronics!</p>",
    "plain": "BUET Robotics Society (BRS) and Engineers Hub proudly presented a joint workshop, 'A Beginner's Guide to PCB Designing', aimed at introducing students to the world of Printed Circuit Boards (PCBs). This workshop explored the essentials of PCB design, which are vital in connecting electrical and electronic components on a single board. The workshop was divided into two engaging online sessions and utilized the Proteus Design Suite for a hands-on learning experience. Participants had the chance to design a PCB from scratch, guided by the instructor's expertise. Workshop Highlights: Introduction to PCB design and its applications. Practical sessions on circuit design and schematic development using Proteus. Participants got to work on designing a 555 timer IC simulation. Step-by-step guidance on placing components, routing, modifying routes, and exporting designs. A PCB Design Challenge was held, where participants could submit their designs within 24 hours for a chance to win the Best Design certificate and a special prize. Instructor Bio: Mir Sayeed Mohammad, a final-year undergraduate student in the Department of EEE at BUET, led the workshop. A robotics enthusiast with a passion for both hardware and software, Mir Sayeed is a former winner of the IEEE VIP Cup and BRS Robo Carnival's 'Industrial Automation Challenge.' He is currently serving as the Assistant General Secretary of BUET Robotics Society. Event Details: Date: March 25, 2021 Time: 7:00 PM – 9:00 PM Platform: Google Meet (Link provided via email) This workshop was an excellent opportunity for participants to learn PCB designing from scratch and enhance their technical skills in electronics!",
    "cover": {
      "alt": "A Beginner's Guide to PCB Designing — BUET Robotics Society archive",
      "width": 2048,
      "height": 2048,
      "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUABQAPzmQu1gvKaWjqAqp4CcJYgC2yAGMWqFTuxPnbDi8APbzdPzoTbElZ+vSnKui03wPwQEjdMBiPSKi3qUDHlICv2+4nvR9vb3KtMNJ+NAcGZPMced8FfNgjaZ/T/AAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/a6/d3/a6d3028ed88d2aaa5c79d975a5d7ece47d119db193f5be49677b32fb8d3b04c3.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/fe/85/fe850dc5868f6e22bbc7ce16c81d5cd44f9b7e0ab5101f41ec0d334633d29724.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/1c/f8/1cf86bd829624d1cbfe0459fab85eee6bdffd73c3256b333d898b5f81f525de0.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/a2/10/a2107ee8c36f07af0783dc52de8d0b5bb735f1e5f74c99e11f9d1bf6ee5980c6.avif"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/d0/2c/d02cd69248e49ef2d3e5b10e1250b75a93e78a0c6277035e919584032feaf13b.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/98/c3/98c34a9501008dde0b5bd6bc331252c45addde19ef1fd1de2a98d7df4a5b98f6.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/e2/f3/e2f36eebba95ed6520c9fc9a2343914bf30961acdc1e24aab0777ff654b40802.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/c9/04/c90475aae2670caf37fcb0f47f15e3b883bf8ef74276ee3302e1391251062a0a.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/65/3b/653bc655fe492c68a269db2cc886e50fdf69e1f371b647be8946240dcd63e96b.webp"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/10/12/1012e444c1482afabd3bb1db79018b835f3403cf8b6ea8d7a781ad3e0eff6dc1.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "A Beginner's Guide to PCB Designing — BUET Robotics Society archive",
        "width": 2048,
        "height": 2048,
        "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQBACdASoUABQAPzmOvFgvKaWjqAqp4CcJZACsMw6BBTu5xBvg6eS8+7kAAPbzdPzoTbEiYO/pB7CxjECApj+lkQEkSROTsG3s/hAiJeBe1AFUwoHUMZTxmZVTCfevkupJebn4K+ZcNPHrZkMAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/e2/f0/e2f0cf9341a5fb6d69f18329b7518ef7892ed369ed5240af45d0bbe604803d76.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/2e/6c/2e6c212ded23c6c9371b5383076ad94d015b9ad2597cf704bc741bbc6b84985d.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/d8/ec/d8ecad25c53e1bfb1563be34f3141f994b3ea7edf7c32d493a7577b0ac496691.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/fa/7f/fa7f998d2c41893b3f9d650c19769adc26bc09893df47e2b41b86f0b1284f77b.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/da/9d/da9d822bb4ab3ae0493395d5041df6223f99e34504354c5659d780d97e2e3a07.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/d9/fe/d9fe4036cc97345659c9dbee6572912f5e7801e5d94f4ddc490662c296a0f191.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/67/6b/676b46286ee5d6fb7b26cab6b86f2d73d969e10065d5ad1d96eeaf9897f6eef1.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/00/81/008170c2e10efd8ce43eebf52d69703db7675194ffd1bbf9da1d85c3a70b03a5.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/4a/8f/4a8fb5a9d9144b3d47e2c13dd6a989ae9435632218fb11c43248e5fa3ed526f8.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/76/6d/766d48eb88bfe1e41dc171f5efa195cb1bd6767e39aa28243206450a1ae2eb74.webp"
          }
        ]
      },
      {
        "alt": "A Beginner's Guide to PCB Designing — BUET Robotics Society archive",
        "width": 2048,
        "height": 2048,
        "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBACdASoUABQAPzmOvFgvKaWjqAqp4CcJYgCdMvuAQS31LGeC84IeAAD283XnguTEZepGTLW/pg1I3bVcQnGiEWZT+PHYNo5G1HpH8beGA7lYMwTrxy7jYjaiBwT1g//G4OTiZ40T5hXGf14gAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/61/42/6142e227247c762cc5bd5e94d99744a3e239aae9b3fa8a76e5b365f569877757.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/01/67/016754993228b70cc70f5830b1abdd9e1cb32a19ea26b2d98a8a5f8ad0234ffa.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/44/f0/44f0ce6a0c974d0b8027f1400a36257a8382099733194b8111893a55a446d26b.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/da/d1/dad138550c2f4aaa40e0c3b2016b38de005dccb21ba03c4241446af84399eafe.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/8d/af/8dafb4a755c6c929338f47da7a75131b40d1fd6979ee280ddb420d2410ca6464.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/10/ed/10edfba0b08eeed4f34d58ed1e0c675891c6a5f99a323093bcbf7b85ea99b7ba.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/db/a4/dba45ca43c7e6bf7321de98724dec355fb2b392f06cae1b2df95aa73e8c89459.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/bc/76/bc7696d0f4d54c7fca6e1fd5ae0ae13a44169e8ed00cacbcc5956527e1dbd931.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/0e/16/0e16527e0b049e8c9175032c3176e5f34bb8a3aaa6e374476fb728d89e4b1559.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/92/23/9223dda0bf2af26a014a6141abd6b1134abebda23329a37d8a8af340db97e0b4.webp"
          }
        ]
      },
      {
        "alt": "A Beginner's Guide to PCB Designing — BUET Robotics Society archive",
        "width": 960,
        "height": 540,
        "lqip": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZQCsAB6IxdDLUir99oAA/rsPdkUm+HVJK/w0p66l4Dxa6cma6uUxjIfWWQMVE7xyki1BqCP4ob/q6+R7kwgAAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/81/bb/81bb7a44234e5973a47452bf6e38a5fbee95749deb3146c87a8279229895a99d.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/2a/4b/2a4b5f2b8a152efbb8a17f84a8e439b0039a48e11686dc8675adc3387d9b6a81.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/ce/5c/ce5c6fcaf3b90bdd2b8d939578b47b0b088074ff6b5f1148853de03a890f4697.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/88/83/88832a3482ab9fc1e59b189de703850361e5e6c5efcc75076e6626fafbcecfd4.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/a8/d3/a8d3fab91362e08c5984ce64682e95b7f5edd91ca8d7ba478c976b2d55822ebd.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/e3/92/e392f1cea4e1d05de1d6b2d3845edbf18c5b9a7a5109eb574e8b99101ea195ec.webp"
          }
        ]
      }
    ]
  };
