/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-robotics-simulation-software-2023
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-robotics-simulation-software-2023",
    "title": "Workshop on Robotics Simulation Software – Part of Robo Carnival 2023",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "robotics simulation software 2023",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society hosted a hands-on workshop on robotics simulation software as part of Robo Carnival 2023, featuring Mir Sayeed Mohammed, an expert instructor in the field.</p>\n<p>About the Workshop: In this interactive session, participants learned how to use CoppeliaSim to simulate robots, sensors, environments, and algorithms efficiently. CoppeliaSim is a powerful simulation platform for robotic systems, offering an intuitive interface to experiment and test robotic designs.</p>\n<p>Workshop Contents:</p>\n<p>Introduction to CoppeliaSim Simulating robots, sensors, and environments Implementing algorithms within the simulation</p>\n<p>Participants had the opportunity to dive into the world of robotic simulations and expand their knowledge and skills.</p>",
    "plain": "BUET Robotics Society hosted a hands-on workshop on robotics simulation software as part of Robo Carnival 2023, featuring Mir Sayeed Mohammed, an expert instructor in the field. About the Workshop: In this interactive session, participants learned how to use CoppeliaSim to simulate robots, sensors, environments, and algorithms efficiently. CoppeliaSim is a powerful simulation platform for robotic systems, offering an intuitive interface to experiment and test robotic designs. Workshop Contents: Introduction to CoppeliaSim Simulating robots, sensors, and environments Implementing algorithms within the simulation Participants had the opportunity to dive into the world of robotic simulations and expand their knowledge and skills.",
    "cover": {
      "alt": "Workshop on Robotics Simulation Software – Part of Robo Carnival 2023 — BUET Robotics Society archive",
      "width": 1595,
      "height": 2048,
      "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACQBACdASoUABoAPzmOv1evKaajqAqp4CcJbACpFQdBWy2Y3btUATxX7U2zB4AA/nFANQlFWNH9x75HAqCimWyfzMcQdciSepPDOsDXrgc/u/kzlnisDczyF3QML4jo0KdOM2lgaouKR/rubg32Xvwom5bfQzeRrRTP/pxfCnU0N4yp268SBqh4AAA=",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/94/83/94837100f7456da5faabd3a73dee05588bd9cb18e46e35fba9f4a88094102a8d.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/64/82/64822af9efe4d9ba41626c237fc02f7fa7f869dae8aa7c77e11476fa479d641e.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/c6/8d/c68d708f133ce2133ecaa9d6bdc82380ce554d4e937480cee5434b02130e5463.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/77/2f/772f1d45016647ddf7b5f78844d96badeca066aead78f547f6db9fe723d11090.avif"
        },
        {
          "w": 1595,
          "url": "http://localhost:9000/brs-assets/sha256/9b/b0/9bb0abdf356fe732ac5e7137b077dced308631bb070f89a6a6874edd3b698bd7.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/a8/7c/a87c41e57fb00806e7e47a9f5ae2e114468077b430d81db2874defa0a091d60b.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/6d/f4/6df43f332e436322beb1da37e5eba7b6e42acdf7086b4560b6e73981650d6225.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/1a/b2/1ab2c78fe0e2d5f92f4fef3bf4df18c78637193137710d5f8088292ec3f33927.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/c2/64/c264af2f48da3bcf5e0453da5770702038230d70643f520c7c2a80dc37182ddd.webp"
        },
        {
          "w": 1595,
          "url": "http://localhost:9000/brs-assets/sha256/07/ea/07eaa73ba4076c8dd8fdd631daee3cb71843c85ae360381d777220fa9820e0fc.webp"
        }
      ]
    },
    "gallery": []
  };
