/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-pcb-17
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-pcb-17",
    "title": "Workshop on PCB Design and Prototyping",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "pcb_17",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society (BRS) hosted an exclusive workshop on PCB Design and Prototyping, conducted by Shimanto Chowdhury, Vice President of BRS and Chair of IEEE BUET SB. The workshop provided hands-on experience in PCB design and prototyping, offering valuable insights into the process.</p>\n<p>Event Details:</p>\n<p>Date: 28 April, 2017 Time: 03:00 PM Venue: Room No. 535, ECE Building, BUET</p>\n<p>The workshop offered participants a unique opportunity to enhance their PCB design skills with BRS!</p>",
    "plain": "BUET Robotics Society (BRS) hosted an exclusive workshop on PCB Design and Prototyping, conducted by Shimanto Chowdhury, Vice President of BRS and Chair of IEEE BUET SB. The workshop provided hands-on experience in PCB design and prototyping, offering valuable insights into the process. Event Details: Date: 28 April, 2017 Time: 03:00 PM Venue: Room No. 535, ECE Building, BUET The workshop offered participants a unique opportunity to enhance their PCB design skills with BRS!",
    "cover": {
      "alt": "Workshop on PCB Design and Prototyping — BUET Robotics Society archive",
      "width": 960,
      "height": 540,
      "lqip": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAAsAPzmEuVOvKKWisAgB4CcJZAAAVJdPL/MTcF3OAAD+0HCXVbJliloDAKHrg1gCpY1AOcXk5WdIbTOhi+LztjIF2nuxHk3uvYAA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/f8/cd/f8cd28804e0a64ea0827a6fb3ab6aa73383989be3e7cdfe0b0bfca2a6e852852.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/3a/cb/3acb45586bf6fd500960b68f64f47f7de1d4bf187fca1d2499f34e58cf7685a3.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/e7/3b/e73bdaf7a2d8b8abec63b9d76c37b43fca1d61113f743a4130a3d52b04fc519b.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/ab/97/ab971f0278c600c1f2567d2ce6512460c34947d39cb5a7803c2deadde046b8f6.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/16/82/1682db50aeeebccc7f92e588c460e8b6675852d944194d9bd5a60124d086ffb3.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/12/bc/12bc13592234531fe5a39f08ff3138e78266e18507c78a81ec7766fd53eaea66.webp"
        }
      ]
    },
    "gallery": []
  };
