/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-v2-0
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-v2-0",
    "title": "Basic Robotics Workshop by BUET Robotics Society",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "v2.0",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society organized its second basic robotics workshop for BUET students with some prior experience in robotics or those interested in robotics but lacking the opportunity to engage.</p>\n<p>Workshop Details: The workshop was held over two days on May 11th and 12th, 2017, and was divided into two phases:</p>\n<p>Phase 1: Focused on circuit building and programming, covering Arduino, sensor interfacing, and basic robotics algorithms.</p>\n<p>Phase 2: Focused on circuit and mechanical design, covering basic electronics and mechanical structure fabrication.</p>\n<p>Eligibility: Only BUET Robotics Society members could register. Priority was given to students from the '15 and '16 batches.</p>",
    "plain": "BUET Robotics Society organized its second basic robotics workshop for BUET students with some prior experience in robotics or those interested in robotics but lacking the opportunity to engage. Workshop Details: The workshop was held over two days on May 11th and 12th, 2017, and was divided into two phases: Phase 1: Focused on circuit building and programming, covering Arduino, sensor interfacing, and basic robotics algorithms. Phase 2: Focused on circuit and mechanical design, covering basic electronics and mechanical structure fabrication. Eligibility: Only BUET Robotics Society members could register. Priority was given to students from the '15 and '16 batches.",
    "cover": {
      "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
      "width": 2048,
      "height": 1192,
      "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAABwBACdASoUAAwAPzmGulQvKSWjMAgB4CcJZgCdEf/3YABXLgRJ1+NPkyyHgAD+dYW2o10UpJ8nAvdttGSMvu7RpWYbEkbOzQEymOr5Vkl3QZphhorvBRRCBI8UjBjSoA+AUM3z8AA=",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/77/27/7727b10e933aa18368503741b8c9379a23303b60cf1bfedddfeb5dfc845f11ee.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/fd/e3/fde3167765edcd010d2cb6034ddb577bd1ad4c56fb66ee937f4b0e1f488e84ad.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/70/51/705118ef0480f70dc5cf931c36239a8c47f6057c6e0d9f5a45c1cb26b42c226c.avif"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/ec/0b/ec0bf9ef8fa8543a7b747323614f4a41053888c1be4010ffc6c6819ccc8a9688.avif"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/d5/e9/d5e92e8ef912cb72762c3b7781a3f5912f11d5188a258d42c0aa9be9586627e4.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/cc/4e/cc4e09c49ae5c54b748b9dd648a956e34c77e382efd1b06b640c02eac4e0cfc2.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/11/fa/11fa16b6f8fbdd5e9eb54670c5fa75ab3c02c064753c1bf91c481b752174054d.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/6b/fa/6bfae703582a01f62b5dcc4fe6182accb8441c9fa64cf05c906d37006ffaba06.webp"
        },
        {
          "w": 1280,
          "url": "http://localhost:9000/brs-assets/sha256/38/53/385332abedc9f6ba1a41e11cdea8b180071f26d2454b7730f090577b2a8f8c86.webp"
        },
        {
          "w": 1600,
          "url": "http://localhost:9000/brs-assets/sha256/db/ad/dbad128caf52d2f1e179ba3937d33479cc99366427b31ba5f5ab341c1e212ef1.webp"
        }
      ]
    },
    "gallery": [
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADwAwCdASoUAA0APzmIu1QvKSYjMAgB4CcJZQDMHCIGqjfhxOHI1i2AAP5B3R1w+yF1pCkvDMuspyv3iPhk/+B/GYCyA1/tNr678P5oOjtN5Bj6wvdoAAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/4d/a1/4da115180294d722334b3e02e6eb8e7fa37d4bf0729a83312fb3132c42a172a7.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/0f/14/0f1486b11e8f23aa9a22ceae3600ad58b1a4a87e1e8735d3fb2b4e819a05e6a8.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/05/72/05727f90ddfd1b2dd595fe11ae76de6312c3b6269a18d8ba7cf0c45f54ffe201.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/4e/60/4e60490365fffd7b9ec9e679bde1c614ff1a9fb69cc910dda2b5f42bbd221991.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/05/74/0574493ebdce90879433ab71952ebd6a3fb475130940ab2c4903dc3fe9880c04.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/50/49/50497fa4208d14d4bd961b211fc8fd5eff1fb7bae31adbaeef3c62c4112e09df.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/c8/73/c873269c6da64ba9fbadfa54013b0e47826f7ec16d655c50dd5cfcd2c6ec8ce8.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/41/72/4172389e605e088d9c6a6cfba77c9d16b7ef5d4a5b7e14d6a51af3dd55aab9d3.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/4f/51/4f51567697f2683f710b312767b86786f8d84c7282b61ff94daa193f4e4e8d72.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/f0/33/f033cb48d912f8679b28265bc1ba03c60546b3b2f4b5cd70a77b964fa88116f5.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZADE2CL3UTj3ICIzJFQgAP6jBap5cQ/Tx0VvzHBkXePeWXIcY9xsQTJZdprTB1j5jKKbV+1NyKuSJw79nZ2cq0N/tpb5e7UPLVxY7cOahiF3Q2dI1AAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/1a/fd/1afdfc86744bcccb9ba8d7cf09c74642da709153ffe09bfd8e81e7f5f79c2976.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/04/f7/04f71ff58ed112a7060ba7c06deed3d527c144ff192af314a7ed5be95d0979b3.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/9e/fd/9efd2fa97f9fa41b56298a9b1d6db122e289553d28252cdc14a4808143d4eae7.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/4c/6c/4c6c2944cd663f2c1dc65619686483f62498a0544c0f6e9145d58da4acad4208.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/91/df/91dfbf334aedecca47780242f515ed387f02a576390f0313e1073d88971a41e7.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/f7/3c/f73ce1c533769a359583923f8eece0dc265c5ebf34f2e89b9be3eba95ea3567f.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/30/e4/30e43c4d2118565c0ec45b9f1772cf96f53145ce9f4361d53bd105f81dd9c98a.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/d2/58/d25808b99649f574dc80424ce534ecf3c610929dcd117d10e3dbaff76996ca32.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e7/8a/e78a1e6d615bea6a370304d94c47c0f45ee366e94309ed95241c51cc21563fc0.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/c4/ae/c4ae2b7effb9da5a41a0e7b959d76b3bd749d01f56d5242b9358722e8ef7f872.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAACQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZAAARMvd1svfQRCAAP4IutSc7aKcwnlH5PRqQVO29QUgMNg903LVl4uj8mEQVT459/MXTt3UfDnndvyEpZBZ9F6d5E2uG8752QGXbk/ZzU9xiFPPtDKCWSu2ZgAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/3d/65/3d651b4273c369559f7094c510363bb9f21847667cf9cc19eba8ce8c3e9671ef.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/4a/45/4a45beaf3a742d82ae4d004d4a4d82113d8857503fd080eb6133ba3e64e552c8.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/49/e0/49e00b72de2de646ec3f75e7787b4928c8e3663427d4bfcd62372cd1da674a05.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/51/25/51254bfb911e4203c5e313754441c30c0023a7ddc653cfd4b67dbd0394682fc8.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/ca/fc/cafce83c575cb58092c1f2c96841a9708510233c6d17d671b2231ddd146c74cb.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/f9/cf/f9cf0f650e966940d1c3fb6e03fc05c71dc5b024c1f111b2091a43de51941a6f.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/6b/d5/6bd5cb474716859db5c72406b92edbfaf892156df2fd3fe75a987f96090a6542.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/03/df/03df2f386fa1abf8a2b760fe2103be08bfaafcd0354d69aad47fc7279f26255a.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/3f/72/3f721cdf686a5c4ae84f8e6189b4147f70b84d3198766b8be07e9615b9c26020.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/af/93/af9340231748aab9806e9eb9529ade266043d9178082e0e5d633c3be3c78d0e1.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJQBjeg0Y/KxecRW7zfAD+taumYqXU2VEUk97q5c6V/05yo62oy7ZcEB4HX1J6NVet6/qVycZHWDgCQjtBKZxhukSvve+ttCy/sG1nyTOrBD+weDwKS3iensKsxbqxcpAAAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/26/8f/268f44370179407cd00f7f30251b3bfd4d861fe44965d0378a3e70771f0d904c.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/59/9a/599a2811c66cc5a24d61f9ec72e0e65a3caebc888da7cb338f8df796d17c3840.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/9b/d3/9bd3a8466746e70fcac01b94bdfc3271341c432e84035f7cc31eab4b7275340b.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ca/e0/cae0b6100b257867e986225eaf16d7b9e768eed47e7431a0fc0ef0a8a7babd92.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/ef/36/ef365272270c6f17287e02e8939bcf84f4d3ae0b03c50f2d27a7459942322ad6.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/2c/79/2c79e3fbcd39300f0c6e4b49ec7901f552197e0fcd0c3e33dada4099a981db64.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/d1/7e/d17e3105d92f3aba2fd604e57322bd633cab18bab5529203a5c259e5b350df3d.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/82/8f/828f0539a2ddff736c499341fc8aea3984f583dd8b7d733a687900e410099d97.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/06/9c/069c92f59094ceaca16a43cfd610e143abfe4a654ea44acf812e35c21702ca6b.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/e1/7d/e17db9b817ad87feeb9ad80a4b49d3e4cae77c1e0e2f16fe073292a0e8e45a51.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZQBUfoY0Y4ZsY4iFUreAAOFZZbfBpmVyUwNe7MDFuGa5BAt07CBR8nzIwy5EIUHLOyR42WSbkw0S8vSybPBIzbrBj7tjJAxL7CgAAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/63/57/635752cdc3f1d1c27a7ecc61cae817092102bdcc82deb2e86b746e324040c8ad.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/8f/e7/8fe7b8be69d186e300378ea8ba131873b544c596a39d7b7724742007231af0a1.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/74/ac/74ac9d233df2bc4866bdb4f6e7cf0e23e7fa745567bb1552694542916529dee0.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/81/d9/81d9e4f459787015dccbf764a519d41eb2a6f27e93daff6f4e47306f796c5962.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/b5/59/b559da6aca7cfe6ef337409efb4f4b0c377640149b69d18d846bbace53a4aa50.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/49/19/491902adeeac898c143fed477ba62effe6f3a38896b403533efded9536440163.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/f3/61/f36120cf181a5c55d7347790459c559fefb03d8937123f084f1b225f3bb8926a.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/5a/7a/5a7a1622c53d4069387f42e0a1ca87ddaff1837635912037d6adbec4e4bda4b8.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/98/28/9828b70e3f358db58bb3aeaaa56a7400c48e35adc8d4e7195815372bc30a018a.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/ba/e1/bae1184cc40ef6446ddb8ac6ec23ca39296ec5811fa01e7221f57a436170f66c.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAwCdASoUAA0APzmGuVQvKSWjMAgB4CcJQAAJRa5n1CVQU8AA94suhvB0R0vOAhWFaAWAlsgTeGpeV2lTcWUILQQIFZomD4oZvo0K79luvjcDc/Uq3CGpQVOL+uPWfJFx5wLCl8bnoUAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/29/ad/29ad56f80ef2d82b829877477bd5a8148320c67c27904821f4ec04ea610aeea3.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/d8/eb/d8eb4ac86d31f8f57d353e1bbfb6313978b5ddc2727e82586dca0d479a2a03d6.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/d8/68/d8688effbc7c1402503d8f79b12f571437348c88fb06d9a86eafd1334bff910c.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ec/9a/ec9ac698e5f81839196f1d0dd541800fca91a80ad7a517be5c481f08e5eb9bbd.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/a9/ff/a9ffa9fe73e11a67fd6a736b74b3dffbc4f4c09ffcf5ec09dabd077621c8be86.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/28/7a/287a661c4f856b9297b2b024d2a2d925d0278a503a940036401a60e4d7f732a0.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/1b/f2/1bf2dfd0ee153284771308b6fa33f67b94622d6c47154284eed935032d595407.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/11/7a/117a2ea09136625803ffbdfa126b0037e4429874c760842d641836875771e13a.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/51/f3/51f380b58d8d7e7b8244b06d9a4d4fa9f71d5c78014cc842a290db55bc707c3f.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/17/e1/17e1f1750b78845bf66cbdca360c1e2a688240343d3d775635aca3319db038f9.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAwCdASoUAA0APzmGulOvKSWisAgB4CcJQApgABVwJfRAAP4WJ6wLHG2LqsAXArWXRFeEzM4mOG3LbD/QOZJ1eZQHCbLC1rhSJDB7hMu6sv03qw78bemejSBT6orx8fRRCAAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/76/74/7674202f71be9f5c3e76979adce720b95c519610df22c15e4aed525090425672.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ce/88/ce881c75ad932e58f834ce9a1781ca9f0a712568a7a34df4910dde38d1dd6fa2.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/b0/81/b081a2ad356083be0a0956cf58af2bbd815f32a6647e3d4a78376ecef2dd3cc7.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/a2/b5/a2b5606e15f593d40035a94546dcf67a193b99df381131b749ebd324eebfe15e.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/52/c1/52c16cbe3dab300dbe910bd6daa23afe0c1bcba7719aa1ebdcbbb687516e03b7.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/94/1b/941b8318f8e01f377d7ab3f4d3f0eb67d9ce73a29adf583785c11b5d3f524dc7.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/91/64/9164dbd6540b528a4211f8f3835573f648126512722bc50e5e1e546b3ecad150.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/71/2f/712f99bbe52921785f70e5945cc17bace2a15faa15fb5cfee9e9dff7bf4a0043.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/df/8e/df8efc4b185ad5b4f58593c81d6c815fe31c75aaf26b2803cb7fd0a8afacbf9c.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/d2/9a/d29a4fc8bc9123a558bfdb2d9d650472a05f19cb48b37025b33be0f6db72bd2d.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJQAAEQ1Lq09dgAPhgOkL/+8ATT8ygyezJ6Tah+3vlnMvHpSWtfuk3HdjY42aKPyvBCvtw+9atLqcDB4qzeIKulViAQMD9M95aBwAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/9f/95/9f95ef60fb961d9b4d0d3281c027886d545d6171319fb185e9c8dccf085c3e06.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/16/7b/167b5690e946ba59f06ffdbec335c438bbe94250e0627ede20eba5633aba1ba4.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/8f/38/8f3826419ee64aaf6a56348d5d5ada9626df05a45357298434c05fdcce38c63c.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/6e/94/6e940f8685a4f37d85fac105081ba8abde2181bb7483be06e11d4b3586fba7a9.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/cf/ac/cfacb9314926db9ee8bb9d8fc868426e4e05ba1083b4cd980e24e587bcd8a562.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/8b/77/8b77909f1d940cd6cd4e3eb950c926b31deba1d36e2701a632c32a49d7e2f608.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/3e/2b/3e2b41054cf7f9cd5ffd566f7455d72faa5e0544f25b4c7a091e15ee21033100.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/fb/e5/fbe515d6027660fe3681bf5a8544d458caec43b92d87c0e5850e4b0a496dde74.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/a3/57/a357119800f529bc307a4b689eca702be21189839c5b4dd93e9cfd0f5ee2e3d8.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/94/9a/949a8106f6b8fea2a5c4f94b1fa85937e8b4b0c6222e41bb3b8e9f4ddcb72926.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABQAwCdASoUAA0APzmGuVOvKSWisAgB4CcJYgAAKRWYcBT9VAD+Jfh58U6PzVMFKYO479SrWLAkKRYRM9Eb5pQrfD5hntdwuwD4KH6JCQ3nQ5ixzjwHrixLpMbX1pCW5IoLKfHyEo0dwyRI1p3NzBRsnyYFphJrq8KwAA==",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/15/3d/153dd5c708b8f05a78fc18941cc3dfddc81aed33bf5623a5d54993abc8e20050.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/43/64/4364113f8bd67307830c52d5468bb685977a321a0d887dd4f53da1c2c624ff9f.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/5b/78/5b78a920d10a41de087bdbf43bfc2e2ace3a3f225a93aa13112ff17544dc92f1.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/a6/20/a620ea6170c61129a32a6defd6474f050d726d94bbf81b87183b776adc251f77.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/8e/55/8e55c091072f2107b7862c38f9e683ef9ce6a3549b42b9b3a42399e9d031e587.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/26/00/2600adbe225be52c1ab282b215f7e94c8e9d60a4a17dc31ca88b7442bb96f1f1.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/2c/1b/2c1b6d41011b8c7277297f47827ebc91a165b9077dfd33ca7a6f2b7e52154ed0.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/67/f3/67f397d17de83b1bbb21f6bb843c22098cde7eeccd5128dc1ec19b1c203cb25b.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/ec/09/ec09a6641f2da24629d0f0749609c19bcce0bacd150a0fb5d9c368ee99b9b873.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/41/0d/410d44c00a65112b6e2e3497c7fa1a66b606834c85efef5d3ed9e634d9a75bc6.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADwAwCdASoUAA0APzmGulQvKSWjMAgB4CcJYgAAPIgtcbUZp2FokoAAAN4ylr96aTHuZMMJQaCUJxO1RPkhaFd3QqXzgtBn4aa8O1pqrghrCHwDYtHMG7Z1p4QApa0xXV/1H5iH7hKP1QAA",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/79/dd/79dd53413e7543ca4daebd721520032951b54ca6f11ab13cd87616ff4b2f0ed8.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/6e/00/6e0065975c0d1d6a6d3493613bc16f89d87dca3a42ba8c3a7146e2f0e01758ed.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/dc/d7/dcd745162b1933a49fea75eae1405035460e03a776627b466fe9229a3a56ab55.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/a7/86/a786dd37c43206329e42a81bbb30d960303876e3cd31f96bd15c629b4a7fed96.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/d9/a7/d9a7c956aab28e55a3cf29f558e1435dd3d29d1d3816ad6665873a700d20c579.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/d1/7c/d17c2fd2b9849542e622c524152bd0d06dacf506c9f473e57a1ffd2a4af4db9f.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/01/74/0174778954916a38075bacc9ee0ba588e9021ee2eee86954806e7694dbeab27e.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/4b/6f/4b6faa5876f9ff4ae30aa461c08409cd2308faca90aca285502cde73562994ed.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/f6/46/f646efb2d64401b26290e1afe58ad9c3a5736505f825dd1b86bf218072a35931.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/65/be/65beb1a75bc6ad7103513975a0e7964a17c1f182d1108888190b5b286235b0a2.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACQAwCdASoUAA0APzmEuVOvKKWisAgB4CcJZAAAPb7VIzmSrB+gAP7U+a+uckG1V5u+nclWPK70NBKuI2DDUVy69MjjBrxFWNdJEAFKIByY6+NJo0+b2EqNLwy0B9Bt0tfGZIzy849cRDSJIEJ6rgqVrAsDGsczcGoqrCRtuJMLJj0AAAA=",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/14/ae/14ae35728c45e25e57f75535a15486b7cd115d3cc4b7b993412251ef15e82323.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/ad/2d/ad2d060bc97884905e50d79e62967c33dcf6a25674b606a8f35d6375d3c31954.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/38/36/383604abfd2af666430a8b9902080f3e49b381cc1aabd37965410725e48dfdf8.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/c8/93/c89364997af2b1b4241d41f213cbe2cc8efdbf8fc6efb21b2e84ee44e824b4bf.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/be/ae/beae024bb56d6b6bac233b1560df77bfbe5cb7842fc0cf90a6fa1aca7c7f8439.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/ff/0b/ff0b2dcf35c2c11c0cf48a78302e463cd7a8b0669996085b16d35b0d43acfefa.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/8b/0d/8b0d85009c307b07bd5c99613cc3748fbe8cfb2c7f26f7bca00030045487cab1.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/a9/4d/a94dca2a24b8fdf06c36255e00dec02bea49c71692b716cddd2df0568c042fe7.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/e3/e7/e3e7ef71d5bd9136a6c068397e9e1e47793ab2ee5655589b196e7df790e781ed.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/15/67/1567bfd6f22e6b2f19acbabfffa1f6dfc6c257d8e707eb4e7c70ec412465bb4c.webp"
          }
        ]
      },
      {
        "alt": "Basic Robotics Workshop by BUET Robotics Society — BUET Robotics Society archive",
        "width": 2048,
        "height": 1365,
        "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAABwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJYwAAMOZ1OVRu7YgA/gBEiu1w22x+uvrG/oFdhXY/FHvny7mi6dd9e84AYG754vvhg6pFVw07tRYyIJvcZN1vplupWXkvPklYQMmdv15FyA4A",
        "avif": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/56/ab/56aba11fb8cbc63a2d61fb7df8158a8ba7744818c3f310cac2cd164b0740b343.avif"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/d7/67/d767c00f9be6119b8aa66551d2072efa93a16ff976ee45a35b4dcb0b9128360b.avif"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/fe/da/feda862558bb718fb0597ff219605431bc3bb4f3c690b88f8ebee9c536cb9630.avif"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/9d/67/9d672f7ba8c626541c2dd8461c10ccdb5adc0dcc34a4bf16a8c7986c44193f67.avif"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/1d/23/1d235e7c317e5b7733f34e08a256f88b71b4ebfb776722dfec2c301c258583e9.avif"
          }
        ],
        "webp": [
          {
            "w": 320,
            "url": "http://localhost:9000/brs-assets/sha256/62/0c/620c7b968cc4f4367bbdd3b00e967e3fe2f33d4969375e4b4bb26d60835dee45.webp"
          },
          {
            "w": 640,
            "url": "http://localhost:9000/brs-assets/sha256/60/f6/60f6f034681bb84f91631436d5d2e620a1f3cd92607b5d70f47aa54bd0ff6c25.webp"
          },
          {
            "w": 960,
            "url": "http://localhost:9000/brs-assets/sha256/ca/e5/cae5fe3d53d8b452cbcd7e6f8ccd960504858edec3a0deb3ffa6af14dafb63a1.webp"
          },
          {
            "w": 1280,
            "url": "http://localhost:9000/brs-assets/sha256/77/ff/77ff64a7351d67934aaf922f95de99c711548359d7b9c0d7d460d4dc24fb3639.webp"
          },
          {
            "w": 1600,
            "url": "http://localhost:9000/brs-assets/sha256/33/28/33289c1114a5c8df6ffa022cee2d71897e1d34cbc796601c274fd8b684ff4aea.webp"
          }
        ]
      }
    ]
  };
