/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-hands-on-trash-collector
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-hands-on-trash-collector",
    "title": "Hands-on Trash Collector Workshop",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "hands on trash collector",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society, in collaboration with IEEE BUET Student Branch and IEEE Robotics &amp; Automation Society BUET SB Chapter, organized the Hands-on Trash Collector workshop. This interactive session provided participants with the opportunity to design, build, and program a robot capable of collecting trash from the environment, promoting both technical learning and environmental responsibility.</p>\n<p>Workshop Topics Covered: 🔹 Introduction to Arduino &amp; Basics of Digital, Analog, and PWM Pins 🔹 Interfacing with Analog &amp; Digital Sensors 🔹 Driving DC &amp; Servo Motors 🔹 Building an Advanced Line Follower Robot 🔹 Applying the PID Algorithm 🔹 Modifying an LFR into a Trash Collector Robot</p>\n<p>Event Details: 📅 Date: 15-16 June 2023 ⏰ Time: 9:00 AM - 4:00 PM 📍 Venue: ECE Building, 5th Floor, BUET</p>\n<p>This workshop was exclusively for BUET students, with a special focus on Batch 20 and Batch 21. Participants registered individually or in teams, gaining hands-on experience in robotics and automation.</p>\n<p>Attendees also had the option to purchase components from BRS, including a handmade chassis for the trash collector robot. The event successfully inspired future innovators to explore the potential of robotics in environmental sustainability.</p>",
    "plain": "BUET Robotics Society, in collaboration with IEEE BUET Student Branch and IEEE Robotics & Automation Society BUET SB Chapter, organized the Hands-on Trash Collector workshop. This interactive session provided participants with the opportunity to design, build, and program a robot capable of collecting trash from the environment, promoting both technical learning and environmental responsibility. Workshop Topics Covered: 🔹 Introduction to Arduino & Basics of Digital, Analog, and PWM Pins 🔹 Interfacing with Analog & Digital Sensors 🔹 Driving DC & Servo Motors 🔹 Building an Advanced Line Follower Robot 🔹 Applying the PID Algorithm 🔹 Modifying an LFR into a Trash Collector Robot Event Details: 📅 Date: 15-16 June 2023 ⏰ Time: 9:00 AM - 4:00 PM 📍 Venue: ECE Building, 5th Floor, BUET This workshop was exclusively for BUET students, with a special focus on Batch 20 and Batch 21. Participants registered individually or in teams, gaining hands-on experience in robotics and automation. Attendees also had the option to purchase components from BRS, including a handmade chassis for the trash collector robot. The event successfully inspired future innovators to explore the potential of robotics in environmental sustainability.",
    "cover": {
      "alt": "Hands-on Trash Collector Workshop — BUET Robotics Society archive",
      "width": 1128,
      "height": 710,
      "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACQAwCdASoUAAwAPzmGuVOvKSWisAgB4CcJQAAKVAfbGD2+18AAAP7ZdqjBUtdkNvx19YzEZCa3dfiRIL3B5XIFpPtkUDm0ziqRXWKDRSgWXRG5DZF1kEDPofAAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/75/08/7508be7279d30abb61d0741ddc355bde3fa26c47e042fda1faa70e000625175d.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/6e/55/6e55e1cae1065e668f18f3946cf8f0f8d6eec1b3791de85b4a9cee153733bddb.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/2d/4b/2d4b570fd65939e3e381ec192a7f6c479f4ebc845ee464c7a0008ad7d17b35a7.avif"
        },
        {
          "w": 1128,
          "url": "http://localhost:9000/brs-assets/sha256/80/14/8014db11cedd53fbad80a8f4c9b7168442dfd12724fbb05e4d91e6c4d812cc08.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/d6/76/d676f86580d4c273a35771a0c13f2920ed801c65c2058f09a3dc89314c4cdb55.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/ba/ef/baef95f61977d04d91e4df1993fbc254c3d6f413f898dcbf96b5337af0eb267a.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/06/a0/06a009e96a8593bcaf87bc5c6860f554e9126861b901298524ee0b5cdf9d781b.webp"
        },
        {
          "w": 1128,
          "url": "http://localhost:9000/brs-assets/sha256/82/a7/82a7975cd6645cb8f412e6a88ec9137cf62d67a8f201efbfc7c3071e5f36e804.webp"
        }
      ]
    },
    "gallery": []
  };
