/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-image-processing-with-python
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-image-processing-with-python",
    "title": "Workshop on Introduction to Image Processing with Python",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "image processing with python",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society (BRS) hosted an online workshop on Introduction to Image Processing with Python, designed to introduce BUET students to the fundamentals of image and video processing. The interactive session provided hands-on experience with essential techniques used in computer vision and automation.</p>\n<p>Workshop Topics Covered: 🔹 Reading &amp; Writing Images and Videos 🔹 Image Cropping &amp; Scaling 🔹 Color Modes (RGB, Grayscale, HSV) &amp; Color Picker 🔹 Shape Drawing &amp; Detection 🔹 Feature Detection &amp; Marker Recognition (QR, Barcode, Aruco) 🔹 Motion &amp; Object Detection</p>\n<p>Event Details: 📅 Date: July 13, 2023 ⏰ Time: 10:00 AM - 1:00 PM 💻 Platform: Microsoft Teams</p>\n<p>The workshop was exclusively for BUET students, requiring a working PC with Python installed. Participants explored various image processing techniques, enhancing their skills in Python-based computer vision.</p>",
    "plain": "BUET Robotics Society (BRS) hosted an online workshop on Introduction to Image Processing with Python, designed to introduce BUET students to the fundamentals of image and video processing. The interactive session provided hands-on experience with essential techniques used in computer vision and automation. Workshop Topics Covered: 🔹 Reading & Writing Images and Videos 🔹 Image Cropping & Scaling 🔹 Color Modes (RGB, Grayscale, HSV) & Color Picker 🔹 Shape Drawing & Detection 🔹 Feature Detection & Marker Recognition (QR, Barcode, Aruco) 🔹 Motion & Object Detection Event Details: 📅 Date: July 13, 2023 ⏰ Time: 10:00 AM - 1:00 PM 💻 Platform: Microsoft Teams The workshop was exclusively for BUET students, requiring a working PC with Python installed. Participants explored various image processing techniques, enhancing their skills in Python-based computer vision.",
    "cover": {
      "alt": "Workshop on Introduction to Image Processing with Python — BUET Robotics Society archive",
      "width": 960,
      "height": 540,
      "lqip": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACQAwCdASoUAAsAPzmGuVOvKSWisAgB4CcJZwAAW8MP5C39rUAAAP7erNY6TFPukV2k0M8q8cssQuEkClcottNaxYwqIUf0UxsLENTAAAA=",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/5d/0c/5d0cc3650916198b9822a7bc262bb62a4e296517e27c943c0d6e464ca26607b5.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/c5/52/c55290dc293d1fc3ae99f9314d42df392fbe0fab5cb0e38a53868132edc80e94.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/29/4d/294d866e3e80d866beb23c9dd9c7c1c1857675bbeaa475950c03f7d0423fbf88.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/e3/14/e3147c1801985ac132dbc1f533f4c92a555ebc2b4421f86e5d348f61b17f4690.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/b4/0f/b40f1f9367d85be6f926677fd5ef115960a5e71fa188ec18ac7205bd476e8435.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/2b/8d/2b8d5f87526f1ff2acb558fc2b5053ae5273e9b2bd1293adad0b475dd760133a.webp"
        }
      ]
    },
    "gallery": []
  };
