/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-on-basic-robotics-2016
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-on-basic-robotics-2016",
    "title": "Workshop on Basic Robotics",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "on basic robotics 2016",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society (BRS) hosted an exclusive hands-on robotics workshop for college students, offering a unique opportunity to explore basic electronics, microcontrollers, and project building.</p>\n<p>Workshop Highlights: 🔹 Introduction to Basic Electronics 🔹 Microcontroller Basics 🔹 Hands-on Project Development</p>\n<p>Registration Details: ✅ Team Formation: Max 4 members per team. ✅ Fee: BDT 600 per team (includes component costs). ✅ Eligibility:</p>\n<p>Open to college students (HSC ’16 batch included).</p>\n<p>Students from different colleges could form a team. ✅ Special Offer: BUET ’16 batch could become BRS members at a 50% discount.</p>\n<p>Workshop Schedule: 📅 Date: November 30, 2016 📍 Venue: ECE Building, BUET 💻 Requirements: At least one laptop, power adapter, and multi-plug per team.</p>\n<p>This day-long workshop provided hands-on experience with necessary robotics components, fostering innovation and technical skills among young robotics enthusiasts!</p>",
    "plain": "BUET Robotics Society (BRS) hosted an exclusive hands-on robotics workshop for college students, offering a unique opportunity to explore basic electronics, microcontrollers, and project building. Workshop Highlights: 🔹 Introduction to Basic Electronics 🔹 Microcontroller Basics 🔹 Hands-on Project Development Registration Details: ✅ Team Formation: Max 4 members per team. ✅ Fee: BDT 600 per team (includes component costs). ✅ Eligibility: Open to college students (HSC ’16 batch included). Students from different colleges could form a team. ✅ Special Offer: BUET ’16 batch could become BRS members at a 50% discount. Workshop Schedule: 📅 Date: November 30, 2016 📍 Venue: ECE Building, BUET 💻 Requirements: At least one laptop, power adapter, and multi-plug per team. This day-long workshop provided hands-on experience with necessary robotics components, fostering innovation and technical skills among young robotics enthusiasts!",
    "cover": {
      "alt": "Workshop on Basic Robotics — BUET Robotics Society archive",
      "width": 1256,
      "height": 826,
      "lqip": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAA0APzmGuVOvKSWisAgB4CcJZAAAYXexm/BxFkxjBXgAAP6/gf60FPZ32TTvgO1d1sNFQ/HzHqoDxml/DfI+cLH4JdwedHOQkxf5uU8VnA9+dZ5V4k29YphLpd6HFQAAAA==",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/c2/1d/c21dca106e0bab34cdf81638a44aba57ee7e0e74470278a12fa2b4f1b35559c3.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/15/e8/15e8c17ef0ba65ee3448294462149aca2c63d467be9bf7bb1aa8f80a2057f469.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/c8/81/c88107de25dce584c0a0a6aaa22356f971bb6329cae10355b41ee6e785337453.avif"
        },
        {
          "w": 1256,
          "url": "http://localhost:9000/brs-assets/sha256/8e/7e/8e7eedc60ae8c88e6d3d04499e76171209872fb859b82700fb6fc69adfc9a8f9.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/b6/a0/b6a0bd0f38d280d4f754b67bada45532102585edaba81cec89e30299ce293eb6.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/37/e9/37e9efbdc1fb3ce01797f362bf8d22b6d5c44aea1ccd6f9ebde17bcb4dea7adf.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/e9/ff/e9fff546ac60afba0e62b7d48a4033ed4df96cef7df327fba9f57aa31a209d07.webp"
        },
        {
          "w": 1256,
          "url": "http://localhost:9000/brs-assets/sha256/b9/0f/b90f4ee32b422ea00c8dd892d35d5a05d3523eea4020bd3460a43c095e5c8c84.webp"
        }
      ]
    },
    "gallery": []
  };
