/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/workshops-v7-0
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "workshops-v7-0",
    "title": "Basic Workshop V7.0 by BUET Robotics Society",
    "category": "workshop",
    "series": "Basic Workshop",
    "edition": "v7.0",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "web-ready",
    "html": "<p>BUET Robotics Society organized 'Basic Workshop V7.0', a two-day workshop aimed at providing enthusiasts with hands-on experience in the world of robotics. The workshop featured four sessions covering the following topics:</p>\n<p>Basics of Robotics Basics of Arduino Coding Sensor Interfacing Motor Interfacing Introduction to Line Follower Robot</p>\n<p>Eligibility: Newcomers from batch 22 and students from batch 21 of BUET were encouraged to attend.</p>",
    "plain": "BUET Robotics Society organized 'Basic Workshop V7.0', a two-day workshop aimed at providing enthusiasts with hands-on experience in the world of robotics. The workshop featured four sessions covering the following topics: Basics of Robotics Basics of Arduino Coding Sensor Interfacing Motor Interfacing Introduction to Line Follower Robot Eligibility: Newcomers from batch 22 and students from batch 21 of BUET were encouraged to attend.",
    "cover": {
      "alt": "Basic Workshop V7.0 by BUET Robotics Society — BUET Robotics Society archive",
      "width": 940,
      "height": 788,
      "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABwBACdASoUABEAPzmUwVmvKicjqAgB4CcJQBdgAb9M+XfohnvSQ43OazXwoADOLpjFS3id44n9F7VS/fpftgCSS8uTwws7gJQsUQauaSYajc3e6UJ5n+qN14iLkQInXE/CYQJwoIeuHBistoj2PKRD8AvBtkMMGHYAAAAA",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/aa/1a/aa1a8376767e9befc6e302b93817c5d102d2cd14a7be5158b7beb72f2537c55f.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/c8/c5/c8c5ffda1c2c9ce615bef74eb220ae866a6532b768533593dc0a2a87350b1bf0.avif"
        },
        {
          "w": 940,
          "url": "http://localhost:9000/brs-assets/sha256/69/34/6934b7e2cb071dd25b7c62bd2566c50c9da214466b7188d72c33292ccbe968d1.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/e0/a2/e0a2e8320a7f2b8c24e1daa9a5848b41bba3a543225c11e9c697b40cacfa901f.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/59/48/59481eb685afc686b415f4900929ecddc4d5d55c188e42dfa01f3a31844043e0.webp"
        },
        {
          "w": 940,
          "url": "http://localhost:9000/brs-assets/sha256/72/49/7249d591bf8f0fd113deca7d5a1e087c092d6edc1b55e51fcbdd01238867cbae.webp"
        }
      ]
    },
    "gallery": []
  };
