/**
 * GENERATED by scripts/fetch-content.ts — do not edit by hand.
 *
 * Source: /v1/events/wow
 *
 * Until Phase B4 this file was generated from image files on disk. It is
 * now generated from Postgres, through the /v1 contract, with every URL
 * pointing at object storage. The export shapes are unchanged, which is
 * why no component needed touching.
 *
 * To change what appears here, edit the collection — not this file.
 */

import type { EventImage } from "../events.generated";

export type EventSegment = { name: string; description: string; eligibility?: string };

export type EventArticle = {
  slug: string;
  title: string;
  category: string;
  /** The display name — "Member recruitment", not "recruitment". Carried
   *  rather than derived: title-casing a slug turns "agm" into "Agm",
   *  and a category the club adds itself can be spelled any way it
   *  likes. See migration 0015. */
  categoryName: string;
  /** Present only when the category is a subcategory. */
  categoryParent?: { slug: string; name: string };
  series?: string;
  edition?: string;
  year: string | null;
  date?: string;
  endDate?: string;
  venue?: string;
  platform?: string;
  theme?: string;
  presentedBy?: string;
  eligibility?: string;
  segments?: EventSegment[];
  copySource: "web-ready" | "derived" | "authored";
  /** Already escaped and rendered at build time. */
  html: string;
  plain: string;
  cover: EventImage;
  gallery: EventImage[];
};

export const EVENT: EventArticle = {
    "slug": "wow",
    "title": "wow",
    "category": "workshop",
    "year": null,
    "categoryName": "Workshop",
    "copySource": "authored",
    "html": "<p><strong>asdfa</strong> this is name</p>",
    "plain": "asdfa this is name",
    "cover": {
      "alt": "IRC 2013 — BUET Robotics Society archive",
      "width": 960,
      "height": 639,
      "lqip": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQAwCdASoUAA0APzmGulQvKSWjMAgB4CcJbACdMoGv/gBXZYuAAP7o8F55sdl9+zoXb6VZnh10zxfQb/sDfFC7ArNPD+t60/tFAvJYuRQ4cTeRFwjlrpvUzZPYrsQd3b9IOcUm7OspyqD5hMxCWdS2+gv3Ybx3sEZ11kcRwAA=",
      "avif": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/63/2f/632fdb6a4e729e98e2fa4b3b43187b51c3700b2c4ea58496663cc7e265f1dd18.avif"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/de/d9/ded97e13aa7d9ed11ff5374c20b51a602966b5aecaeff45d71596591b06f5e4e.avif"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/c7/0e/c70eb5065f49ae9673f2ffbdb856bb3cdc89889f7a99775b47644639c6a49c33.avif"
        }
      ],
      "webp": [
        {
          "w": 320,
          "url": "http://localhost:9000/brs-assets/sha256/26/9e/269e9e1a919c8557d289e22f2d82b68a92ca93112af82efd3c1688ba45d6955b.webp"
        },
        {
          "w": 640,
          "url": "http://localhost:9000/brs-assets/sha256/a5/bd/a5bd3ac51743dfb9c2710b4a8326f6343f40c960a97d1e6a0bf5ae93ea588c49.webp"
        },
        {
          "w": 960,
          "url": "http://localhost:9000/brs-assets/sha256/de/ea/deeac5edd0c705e8700820c4bcf35d3978c550c84cfe332272d50fe3b19786b4.webp"
        }
      ]
    },
    "gallery": []
  };
